/**
 * Built-in deck: Animal Kingdom (NEET Biology, Chapter 4)
 * 156 high-yield NCERT cards with NEET traps and NCERT hooks.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const animalKingdomDeck: BuiltinDeck = {
  id: "builtin-animal-kingdom",
  name: "Animal Kingdom",
  description:
    "156 high-yield NCERT cards covering all animal phyla from Porifera to Mammalia — with NEET traps and NCERT hooks on every card.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Concept",
      title: "Levels of organisation",
      front:
        "Sequence the levels of organization from simplest to most complex.",
      back: "Cellular → Tissue → Organ → Organ-system",
      trap: "All animals are multicellular, but not all have the same level of organization.",
      hook: "Reflects evolutionary complexity",
    },
    {
      id: 2,
      cardType: "Example",
      title: "Porifera",
      front: "Which level of organization is found in Porifera?",
      back: "Cellular level",
      trap: "They lack true tissues despite being multicellular.",
      hook: "Most primitive multicellular animals",
    },
    {
      id: 3,
      cardType: "Example",
      title: "Cnidaria",
      front: "Cnidaria represents which level of organization?",
      back: "Tissue level",
      trap: "They have tissues but no organs.",
      hook: "First true tissues",
    },
    {
      id: 4,
      cardType: "Example",
      title: "Platyhelminthes",
      front: "Identify the level of organization in Platyhelminthes.",
      back: "Organ level",
      trap: "They have organs but not a complete organ-system.",
      hook: "Tissues form organs",
    },
    {
      id: 5,
      cardType: "Example",
      title: "Annelida",
      front: "Annelida exhibits which level of organization?",
      back: "Organ-system level",
      trap: "Don't confuse with organ level; functional systems are present.",
      hook: "Advanced functional systems",
    },
    {
      id: 6,
      cardType: "Concept",
      title: "Body symmetry",
      front: "What does body symmetry determine in an animal?",
      back: "Arrangement of body parts",
      trap: "Symmetry is not the same in all animals.",
      hook: "Correlates with locomotion pattern",
    },
    {
      id: 7,
      cardType: "Example",
      title: "Porifera",
      front: "What is the typical symmetry of Porifera?",
      back: "Asymmetrical",
      trap: "No plane can divide the body into two equal halves.",
      hook: "Irregular body form",
    },
    {
      id: 8,
      cardType: "Example",
      title: "Cnidaria",
      front: "Identify the symmetry found in Cnidaria.",
      back: "Radial symmetry",
      trap: "It is not bilateral symmetry.",
      hook: "Any plane through the central axis works",
    },
    {
      id: 9,
      cardType: "Example",
      title: "Echinodermata (adult)",
      front: "What is the symmetry of an adult Echinoderm?",
      back: "Radial symmetry",
      trap: "The larva is bilateral, not radial.",
      hook: "Key developmental change",
    },
    {
      id: 10,
      cardType: "Example",
      title: "Annelida",
      front: "Identify the symmetry in Annelida.",
      back: "Bilateral symmetry",
      trap: "It is not radial.",
      hook: "Enables directional movement",
    },
    {
      id: 11,
      cardType: "Concept",
      title: "Diploblastic animals",
      front: "Define 'Diploblastic'.",
      back: "Animals with two germ layers (Ectoderm and Endoderm).",
      trap: "There is no mesoderm layer.",
      hook: "Tissue-level body plan",
    },
    {
      id: 12,
      cardType: "Example",
      title: "Cnidaria",
      front: "True or False: Cnidarians are Triploblastic.",
      back: "False (Diploblastic)",
      trap: "They are not triploblastic.",
      hook: "Mesoglea present between layers",
    },
    {
      id: 13,
      cardType: "Concept",
      title: "Triploblastic animals",
      front: "What characterizes Triploblastic animals?",
      back: "Possession of three germ layers (Ecto, Meso, Endo).",
      trap: "Absent in lower phyla like Porifera and Cnidaria.",
      hook: "Leads to organ complexity",
    },
    {
      id: 14,
      cardType: "Example",
      title: "Platyhelminthes",
      front: "Identify the germ layer status of Platyhelminthes.",
      back: "Triploblastic",
      trap: "Body is still simple (Acoelomate).",
      hook: "First appearance of mesoderm",
    },
    {
      id: 15,
      cardType: "Concept",
      title: "Coelom",
      front: "What is a true coelom?",
      back: "A body cavity lined by mesoderm.",
      trap: "Just a space does not equal a coelom.",
      hook: "Necessary for organ suspension",
    },
    {
      id: 16,
      cardType: "Example",
      title: "Platyhelminthes",
      front: "Are Platyhelminthes coelomates?",
      back: "No, they are Acoelomate.",
      trap: "They lack a body cavity.",
      hook: "Solid mesoderm",
    },
    {
      id: 17,
      cardType: "Example",
      title: "Aschelminthes",
      front: "Identify the coelom type in Aschelminthes.",
      back: "Pseudocoelomate",
      trap: "It is not a true coelom.",
      hook: "Mesoderm does not line the cavity",
    },
    {
      id: 18,
      cardType: "Example",
      title: "Annelida",
      front: "Annelida belongs to which coelom category?",
      back: "True coelomate",
      trap: "It is not pseudo.",
      hook: "Allows efficient organ function",
    },
    {
      id: 19,
      cardType: "Concept",
      title: "Porifera",
      front: "What is the defining feature of Phylum Porifera?",
      back: "Pore-bearing animals with a Canal system.",
      trap: "They possess no tissues.",
      hook: "Unique canal system",
    },
    {
      id: 20,
      cardType: "Example",
      title: "Sycon (Scypha)",
      front: "Describe Sycon.",
      back: "A marine sponge.",
      trap: "It is not a freshwater organism.",
      hook: "Cellular organization",
    },
    {
      id: 21,
      cardType: "Example",
      title: "Spongilla",
      front: "What makes Spongilla a unique Poriferan?",
      back: "It is a freshwater sponge.",
      trap: "Most Porifera are marine.",
      hook: "Exception example",
    },
    {
      id: 22,
      cardType: "Example",
      title: "Euspongia",
      front: "What is Euspongia commonly called?",
      back: "Bath sponge",
      trap: "Skeleton is made of spongin fibres, not spicules.",
      hook: "Spongin fibres",
    },
    {
      id: 23,
      cardType: "Concept",
      title: "Cnidaria",
      front: "What is the diagnostic cell of Cnidaria?",
      back: "Cnidoblasts (Cnidocytes).",
      trap: "Do not confuse with comb plates (Ctenophora).",
      hook: "Used for defense and prey capture",
    },
    {
      id: 24,
      cardType: "Example",
      title: "Hydra",
      front: "Which body form does Hydra represent?",
      back: "Polyp form",
      trap: "It does not have a medusa stage.",
      hook: "Sessile cnidarian",
    },
    {
      id: 25,
      cardType: "Example",
      title: "Adamsia",
      front: "What is Adamsia and its body form?",
      back: "Sea anemone; Polyp form only.",
      trap: "No medusa stage present.",
      hook: "Polyp only",
    },
    {
      id: 26,
      cardType: "Example",
      title: "Aurelia",
      front: "Identify Aurelia.",
      back: "Jellyfish; Medusa form.",
      trap: "It is not a polyp.",
      hook: "Free-swimming jellyfish",
    },
    {
      id: 27,
      cardType: "Example",
      title: "Obelia",
      front: "What is unique about Obelia's life cycle?",
      back: "Metagenesis (Alternation of generations).",
      trap: "It does not exist in a single form.",
      hook: "Polyp ↔ Medusa",
    },
    {
      id: 28,
      cardType: "Example",
      title: "Physalia",
      front: "What is Physalia commonly known as?",
      back: "Portuguese man-of-war",
      trap: "It is a colonial organism, not a single individual.",
      hook: "Colonial cnidarian",
    },
    {
      id: 29,
      cardType: "Example",
      title: "Pennatula",
      front: "Identify Pennatula.",
      back: "Sea pen",
      trap: "It is a colonial form, not solitary.",
      hook: "Colonial form",
    },
    {
      id: 30,
      cardType: "Example",
      title: "Gorgonia",
      front: "What is the common name for Gorgonia?",
      back: "Sea fan",
      trap: "It is not soft coral.",
      hook: "Fan-shaped colony",
    },
    {
      id: 31,
      cardType: "Example",
      title: "Meandrina",
      front: "Identify Meandrina.",
      back: "Brain coral",
      trap: "Has a calcium carbonate skeleton.",
      hook: "Skeletal structure",
    },
    {
      id: 32,
      cardType: "Concept",
      title: "Ctenophora",
      front: "What is the key feature of Ctenophora?",
      back: "Comb-bearing animals with 8 ciliary plates.",
      trap: "They have no cnidoblasts.",
      hook: "Exclusively marine",
    },
    {
      id: 33,
      cardType: "Example",
      title: "Pleurobrachia",
      front: "What is Pleurobrachia commonly called?",
      back: "Comb jelly",
      trap: "It is not a cnidarian.",
      hook: "Shows bioluminescence",
    },
    {
      id: 34,
      cardType: "Example",
      title: "Ctenoplana",
      front: "Describe the locomotion of Ctenoplana.",
      back: "Ciliary locomotion.",
      trap: "It has no nematocysts.",
      hook: "Marine ctenophore",
    },
    {
      id: 35,
      cardType: "Concept",
      title: "Platyhelminthes",
      front: "Why are they called Platyhelminthes?",
      back: "Dorso-ventrally flattened body (Flatworms).",
      trap: "They are not round.",
      hook: "Acoelomate",
    },
    {
      id: 36,
      cardType: "Example",
      title: "Planaria",
      front: "What is a notable feature of Planaria?",
      back: "High regeneration capacity.",
      trap: "It is free-living, not parasitic.",
      hook: "Regeneration",
    },
    {
      id: 37,
      cardType: "Example",
      title: "Taenia",
      front: "How does Taenia (Tapeworm) get nutrition?",
      back: "Absorptive nutrition through body surface.",
      trap: "Lacks a digestive system.",
      hook: "Absorptive nutrition",
    },
    {
      id: 38,
      cardType: "Example",
      title: "Fasciola",
      front: "Where is Fasciola (Liver fluke) found?",
      back: "Sheep liver.",
      trap: "It is not an intestinal parasite.",
      hook: "Liver parasite",
    },
    {
      id: 39,
      cardType: "Concept",
      title: "Aschelminthes",
      front: "Common name for Aschelminthes?",
      back: "Roundworms",
      trap: "They are not segmented.",
      hook: "Pseudocoelomate",
    },
    {
      id: 40,
      cardType: "Example",
      title: "Ascaris",
      front: "Does Ascaris show sexual dimorphism?",
      back: "Yes, it is dioecious.",
      trap: "Male and female are different.",
      hook: "Intestinal parasite",
    },
    {
      id: 41,
      cardType: "Example",
      title: "Wuchereria",
      front: "What disease does Wuchereria cause?",
      back: "Elephantiasis (Filariasis).",
      trap: "It is not a gut parasite.",
      hook: "Filarial worm",
    },
    {
      id: 42,
      cardType: "Example",
      title: "Ancylostoma",
      front: "Common name and impact of Ancylostoma?",
      back: "Hookworm; causes Anaemia.",
      trap: "It is not harmless.",
      hook: "Anemia factor",
    },
    {
      id: 43,
      cardType: "Concept",
      title: "Annelida",
      front: "What is the diagnostic trait of Annelids?",
      back: "Metameric segmentation.",
      trap: "Segmentation is true, not pseudo.",
      hook: "True coelom",
    },
    {
      id: 44,
      cardType: "Example",
      title: "Nereis",
      front: "Describe Nereis's locomotion and sex.",
      back: "Parapodia for swimming; Dioecious.",
      trap: "It is a marine annelid.",
      hook: "Parapodia",
    },
    {
      id: 45,
      cardType: "Example",
      title: "Pheretima",
      front: "Common name for Pheretima?",
      back: "Earthworm",
      trap: "It is Monoecious, not dioecious.",
      hook: "Monoecious",
    },
    {
      id: 46,
      cardType: "Example",
      title: "Hirudinaria",
      front: "Identify Hirudinaria.",
      back: "Blood-sucking leech",
      trap: "Lacks parapodia.",
      hook: "Blood-sucking",
    },
    {
      id: 47,
      cardType: "Concept",
      title: "Arthropoda",
      front: "Key feature of Phylum Arthropoda?",
      back: "Jointed appendages.",
      trap: "They are not annelids.",
      hook: "Largest phylum in Animalia",
    },
    {
      id: 48,
      cardType: "Example",
      title: "Apis",
      front: "What is Apis?",
      back: "Honey bee",
      trap: "It is a social insect, not solitary.",
      hook: "Social insect",
    },
    {
      id: 49,
      cardType: "Example",
      title: "Bombyx",
      front: "What is the use of Bombyx?",
      back: "Silkworm (Sericulture).",
      trap: "The adult does not produce silk.",
      hook: "Sericulture",
    },
    {
      id: 50,
      cardType: "Example",
      title: "Laccifer",
      front: "What does Laccifer produce?",
      back: "Lac (Resin secretion).",
      trap: "It does not produce wax.",
      hook: "Resin secretion",
    },
    {
      id: 51,
      cardType: "Example",
      title: "Anopheles",
      front: "Vector role of Anopheles?",
      back: "Malaria vector.",
      trap: "It does not transmit dengue.",
      hook: "Female bites",
    },
    {
      id: 52,
      cardType: "Example",
      title: "Culex",
      front: "Vector role of Culex?",
      back: "Filariasis vector.",
      trap: "It does not transmit malaria.",
      hook: "Polluted water breeder",
    },
    {
      id: 53,
      cardType: "Example",
      title: "Aedes",
      front: "Vector role of Aedes?",
      back: "Dengue vector.",
      trap: "Bites during the day.",
      hook: "Clean water breeder",
    },
    {
      id: 54,
      cardType: "Example",
      title: "Locusta",
      front: "Impact of Locusta (Locust)?",
      back: "Gregarious pest; crop destruction.",
      trap: "Not a solitary insect.",
      hook: "Crop destruction",
    },
    {
      id: 55,
      cardType: "Example",
      title: "Limulus",
      front: "Common name and status of Limulus?",
      back: "King crab; Living fossil.",
      trap: "It is not a true crab.",
      hook: "Living fossil",
    },
    {
      id: 56,
      cardType: "Concept",
      title: "Mollusca",
      front: "General characteristics of Mollusca?",
      back: "Soft-bodied, unsegmented with mantle and shell.",
      trap: "Body is not segmented.",
      hook: "Mantle + shell",
    },
    {
      id: 57,
      cardType: "Example",
      title: "Pila",
      front: "Common name and habitat of Pila?",
      back: "Apple snail; Freshwater.",
      trap: "It is a gastropod.",
      hook: "Gastropod",
    },
    {
      id: 58,
      cardType: "Example",
      title: "Pinctada",
      front: "Economic importance of Pinctada?",
      back: "Pearl formation (Pearl oyster).",
      trap: "It is not a snail.",
      hook: "Pearl formation",
    },
    {
      id: 59,
      cardType: "Example",
      title: "Sepia",
      front: "Common name for Sepia and shell type?",
      back: "Cuttlefish; Internal shell.",
      trap: "Cuttlebone present.",
      hook: "Cuttlebone",
    },
    {
      id: 60,
      cardType: "Example",
      title: "Loligo",
      front: "Common name for Loligo?",
      back: "Squid",
      trap: "Has ten arms; fast swimmer.",
      hook: "Fast swimmer",
    },
    {
      id: 61,
      cardType: "Example",
      title: "Octopus",
      front: "Common name and shell status of Octopus?",
      back: "Devil fish; No shell.",
      trap: "Known for being intelligent.",
      hook: "Intelligent mollusc",
    },
    {
      id: 62,
      cardType: "Example",
      title: "Aplysia",
      front: "Common name for Aplysia?",
      back: "Sea hare",
      trap: "It is a marine gastropod.",
      hook: "Gastropod",
    },
    {
      id: 63,
      cardType: "Example",
      title: "Dentalium",
      front: "Common name and shell shape for Dentalium?",
      back: "Tusk shell; Tubular shell.",
      trap: "Belongs to Scaphopoda.",
      hook: "Scaphopod",
    },
    {
      id: 64,
      cardType: "Example",
      title: "Chaetopleura",
      front: "Identify Chaetopleura.",
      back: "Chiton; 8 shell plates.",
      trap: "Belongs to Polyplacophora.",
      hook: "8 shell plates",
    },
    {
      id: 65,
      cardType: "Concept",
      title: "Echinodermata",
      front: "Distinctive trait of Echinodermata?",
      back: "Spiny skin and water vascular system.",
      trap: "Adults are radial, but they are marine only.",
      hook: "Marine only",
    },
    {
      id: 66,
      cardType: "Example",
      title: "Asterias",
      front: "What is Asterias?",
      back: "Starfish",
      trap: "It is not a true fish.",
      hook: "High regeneration",
    },
    {
      id: 67,
      cardType: "Example",
      title: "Echinus",
      front: "Common name for Echinus?",
      back: "Sea urchin",
      trap: "Globular body with spines.",
      hook: "Globular with spines",
    },
    {
      id: 68,
      cardType: "Example",
      title: "Antedon",
      front: "Common name for Antedon?",
      back: "Sea lily",
      trap: "It is an animal, not a plant.",
      hook: "Feather arms",
    },
    {
      id: 69,
      cardType: "Example",
      title: "Cucumaria",
      front: "Common name for Cucumaria?",
      back: "Sea cucumber",
      trap: "Body is soft and elongated.",
      hook: "Soft body",
    },
    {
      id: 70,
      cardType: "Example",
      title: "Ophiura",
      front: "Common name for Ophiura?",
      back: "Brittle star",
      trap: "Has slender arms.",
      hook: "Fast movement",
    },
    {
      id: 71,
      cardType: "Concept",
      title: "Hemichordata",
      front: "Phylogenetic status of Hemichordates?",
      back: "Separate non-chordate phylum.",
      trap: "They are not true chordates.",
      hook: "Stomochord present",
    },
    {
      id: 72,
      cardType: "Concept",
      title: "Stomochord",
      front: "What is a Stomochord?",
      back: "Notochord-like structure in the collar region.",
      trap: "It is not a true notochord.",
      hook: "Collar region feature",
    },
    {
      id: 73,
      cardType: "Concept",
      title: "Hemichordate body plan",
      front: "Name the three body parts of Hemichordates.",
      back: "Proboscis, Collar, and Trunk.",
      trap: "They are not segmented.",
      hook: "Diagnostic feature",
    },
    {
      id: 74,
      cardType: "Example",
      title: "Balanoglossus",
      front: "What is Balanoglossus commonly called?",
      back: "Acorn worm",
      trap: "It is not an annelid.",
      hook: "Gill slits present",
    },
    {
      id: 75,
      cardType: "Example",
      title: "Saccoglossus",
      front: "Describe Saccoglossus.",
      back: "Worm-like marine hemichordate.",
      trap: "It is not a chordate.",
      hook: "Worm-like body",
    },
    {
      id: 76,
      cardType: "Concept",
      title: "Chordata",
      front: "What is the defining character of Chordates?",
      back: "Presence of a Notochord.",
      trap: "Absent in non-chordates.",
      hook: "Key defining character",
    },
    {
      id: 77,
      cardType: "Concept",
      title: "Dorsal nerve cord",
      front: "Describe the Chordate nerve cord.",
      back: "Hollow and dorsal.",
      trap: "It is not ventral (non-chordates are ventral).",
      hook: "CNS feature",
    },
    {
      id: 78,
      cardType: "Concept",
      title: "Pharyngeal gill slits",
      front: "Do all chordates have gill slits?",
      back: "Present at some stage of life.",
      trap: "In adults, they may be replaced by lungs.",
      hook: "Respiration feature",
    },
    {
      id: 79,
      cardType: "Concept",
      title: "Post-anal tail",
      front: "Is the tail present in all chordates?",
      back: "Yes, present (at least in embryonic stage).",
      trap: "Absent in non-chordates.",
      hook: "Movement aid",
    },
    {
      id: 80,
      cardType: "Concept",
      title: "Urochordata",
      front: "Where is the notochord in Urochordates?",
      back: "Only in the larval tail.",
      trap: "Lost in the adult stage.",
      hook: "Tunicates",
    },
    {
      id: 81,
      cardType: "Example",
      title: "Ascidia",
      front: "Common name and larval change for Ascidia?",
      back: "Sea squirt; Retrogressive metamorphosis.",
      trap: "Adult looks non-chordate.",
      hook: "Retrogressive metamorphosis",
    },
    {
      id: 82,
      cardType: "Example",
      title: "Salpa",
      front: "Identify Salpa.",
      back: "Pelagic tunicate.",
      trap: "It is not sessile; it's free-swimming.",
      hook: "Free-swimming",
    },
    {
      id: 83,
      cardType: "Example",
      title: "Doliolum",
      front: "Shape of Doliolum?",
      back: "Barrel-shaped tunicate.",
      trap: "It is not a fish.",
      hook: "Marine chordate",
    },
    {
      id: 84,
      cardType: "Concept",
      title: "Cephalochordata",
      front: "Where is the notochord in Cephalochordates?",
      back: "Extends from head to tail; persists for life.",
      trap: "Does not disappear like in Urochordates.",
      hook: "Primitive chordate",
    },
    {
      id: 85,
      cardType: "Example",
      title: "Branchiostoma",
      front: "Common name for Branchiostoma?",
      back: "Amphioxus or Lancelet.",
      trap: "It is not a vertebrate.",
      hook: "Lancelet",
    },
    {
      id: 86,
      cardType: "Concept",
      title: "Vertebrata",
      front: "What replaces the notochord in Vertebrates?",
      back: "Vertebral column.",
      trap: "Notochord is only present in embryos.",
      hook: "Replaces notochord",
    },
    {
      id: 87,
      cardType: "Concept",
      title: "Cyclostomata",
      front: "General classification of Cyclostomes?",
      back: "Jawless vertebrates (Agnatha).",
      trap: "They are not true fishes.",
      hook: "Agnatha",
    },
    {
      id: 88,
      cardType: "Concept",
      title: "Cyclostomata mouth",
      front: "Describe the mouth of a Cyclostome.",
      back: "Circular, sucking, and jawless.",
      trap: "They have no jaws.",
      hook: "Ectoparasitic lifestyle",
    },
    {
      id: 89,
      cardType: "Example",
      title: "Petromyzon",
      front: "Common name for Petromyzon?",
      back: "Lamprey",
      trap: "It is an ectoparasite on fishes.",
      hook: "Fish parasite",
    },
    {
      id: 90,
      cardType: "Example",
      title: "Myxine",
      front: "Common name and secretion of Myxine?",
      back: "Hagfish; Slime.",
      trap: "Lacks true vertebrae.",
      hook: "Slime secretion",
    },
    {
      id: 91,
      cardType: "Concept",
      title: "Chondrichthyes",
      front: "What type of skeleton do Chondrichthyes have?",
      back: "Cartilaginous skeleton.",
      trap: "They have no bony skeleton.",
      hook: "Exclusively marine",
    },
    {
      id: 92,
      cardType: "Concept",
      title: "Placoid scales",
      front: "Identify the scales in Sharks.",
      back: "Placoid scales (dermal denticles).",
      trap: "They are not cycloid.",
      hook: "Shark skin",
    },
    {
      id: 93,
      cardType: "Concept",
      title: "Swim bladder (Chondrichthyes)",
      front: "Do cartilaginous fish have swim bladders?",
      back: "No, absent.",
      trap: "They must swim constantly to avoid sinking.",
      hook: "Buoyancy regulation",
    },
    {
      id: 94,
      cardType: "Concept",
      title: "Chondrichthyes heart",
      front: "Describe the heart of Chondrichthyes.",
      back: "Two-chambered (1 Auricle, 1 Ventricle).",
      trap: "It is not three-chambered.",
      hook: "Single circulation",
    },
    {
      id: 95,
      cardType: "Example",
      title: "Scoliodon",
      front: "Common name for Scoliodon?",
      back: "Dogfish shark.",
      trap: "It is a cartilaginous fish, not bony.",
      hook: "Shark",
    },
    {
      id: 96,
      cardType: "Example",
      title: "Pristis",
      front: "Common name for Pristis?",
      back: "Sawfish",
      trap: "It is not a ray.",
      hook: "Rostrum present",
    },
    {
      id: 97,
      cardType: "Example",
      title: "Carcharodon",
      front: "Common name for Carcharodon?",
      back: "Great white shark.",
      trap: "Apex predator.",
      hook: "Powerful jaws",
    },
    {
      id: 98,
      cardType: "Example",
      title: "Trygon",
      front: "Common name and defense of Trygon?",
      back: "Sting ray; Venomous spine.",
      trap: "Possesses a poison sting.",
      hook: "Poison sting",
    },
    {
      id: 99,
      cardType: "Concept",
      title: "Osteichthyes",
      front: "Skeletal feature of Osteichthyes?",
      back: "Bony endoskeleton.",
      trap: "They are not cartilaginous.",
      hook: "Endoskeleton is bone",
    },
    {
      id: 100,
      cardType: "Concept",
      title: "Operculum",
      front: "What is an Operculum?",
      back: "A bony gill cover.",
      trap: "Absent in sharks/cartilaginous fish.",
      hook: "Gill protection",
    },
    {
      id: 101,
      cardType: "Concept",
      title: "Air bladder",
      front: "Function of the air bladder in bony fish?",
      back: "Regulates buoyancy.",
      trap: "It is not primarily for respiration.",
      hook: "Float regulation",
    },
    {
      id: 102,
      cardType: "Concept",
      title: "Osteichthyes heart",
      front: "Heart chamber count in bony fish?",
      back: "Two-chambered.",
      trap: "They are cold-blooded.",
      hook: "Single circulation",
    },
    {
      id: 103,
      cardType: "Example",
      title: "Exocoetus",
      front: "Common name and mode of movement for Exocoetus?",
      back: "Flying fish; Gliding.",
      trap: "It does not truly fly like a bird.",
      hook: "Gliding",
    },
    {
      id: 104,
      cardType: "Example",
      title: "Hippocampus",
      front: "Common name and unique male trait of Hippocampus?",
      back: "Seahorse; Male pregnancy.",
      trap: "Males have a bucket pouch.",
      hook: "Brood pouch",
    },
    {
      id: 105,
      cardType: "Example",
      title: "Labeo",
      front: "Common name for Labeo?",
      back: "Rohu",
      trap: "It is a freshwater fish.",
      hook: "Food fish",
    },
    {
      id: 106,
      cardType: "Example",
      title: "Catla",
      front: "Identify Catla.",
      back: "Katla (Indian carp).",
      trap: "It is a herbivore.",
      hook: "Indian carp",
    },
    {
      id: 107,
      cardType: "Example",
      title: "Clarias",
      front: "Common name and feature of Clarias?",
      back: "Magur; Air-breathing.",
      trap: "Has accessory respiration.",
      hook: "Accessory respiration",
    },
    {
      id: 108,
      cardType: "Example",
      title: "Betta",
      front: "Common name for Betta?",
      back: "Siamese fighting fish.",
      trap: "Males are highly aggressive.",
      hook: "Aquarium fish",
    },
    {
      id: 109,
      cardType: "Example",
      title: "Pterophyllum",
      front: "Common name for Pterophyllum?",
      back: "Angel fish.",
      trap: "Ornamental.",
      hook: "Aquarium",
    },
    {
      id: 110,
      cardType: "Concept",
      title: "Amphibia",
      front: "What does 'Amphibian' mean?",
      back: "Dual life (Water + Land).",
      trap: "They are not fully terrestrial (need water for breeding).",
      hook: "Dual life",
    },
    {
      id: 111,
      cardType: "Concept",
      title: "Amphibian skin",
      front: "Describe amphibian skin.",
      back: "Moist and scaleless.",
      trap: "It is not dry.",
      hook: "Used for cutaneous respiration",
    },
    {
      id: 112,
      cardType: "Concept",
      title: "Amphibian heart",
      front: "How many chambers in an amphibian heart?",
      back: "Three-chambered (2 Atria, 1 Ventricle).",
      trap: "Separation of blood is incomplete.",
      hook: "Double circulation",
    },
    {
      id: 113,
      cardType: "Example",
      title: "Bufo",
      front: "Common name and skin of Bufo?",
      back: "Toad; Dry skin.",
      trap: "More terrestrial than Rana.",
      hook: "Terrestrial",
    },
    {
      id: 114,
      cardType: "Example",
      title: "Rana",
      front: "Common name for Rana?",
      back: "Frog",
      trap: "Skin must stay moist.",
      hook: "Aquatic",
    },
    {
      id: 115,
      cardType: "Example",
      title: "Hyla",
      front: "Common name and feature of Hyla?",
      back: "Tree frog; Adhesive pads.",
      trap: "Lives in trees (arboreal).",
      hook: "Arboreal",
    },
    {
      id: 116,
      cardType: "Example",
      title: "Salamandra",
      front: "Identify Salamandra.",
      back: "Salamander",
      trap: "It is not a lizard; it is a tailed amphibian.",
      hook: "Tailed amphibian",
    },
    {
      id: 117,
      cardType: "Example",
      title: "Ichthyophis",
      front: "Identify Ichthyophis.",
      back: "Limbless amphibian (Caecilian).",
      trap: "It is not a snake.",
      hook: "Caecilian",
    },
    {
      id: 118,
      cardType: "Concept",
      title: "Reptilia",
      front: "Skin characteristic of Reptiles?",
      back: "Dry cornified skin with scales.",
      trap: "No cutaneous respiration.",
      hook: "Epidermal scales",
    },
    {
      id: 119,
      cardType: "Concept",
      title: "Reptilian heart",
      front: "Heart chamber count in reptiles?",
      back: "Three-chambered (mostly).",
      trap: "Crocodiles are an exception (4 chambers).",
      hook: "Partial separation",
    },
    {
      id: 120,
      cardType: "Example",
      title: "Chelone",
      front: "Common name for Chelone?",
      back: "Turtle",
      trap: "It is an aquatic reptile.",
      hook: "Hard shell",
    },
    {
      id: 121,
      cardType: "Example",
      title: "Testudo",
      front: "Common name for Testudo?",
      back: "Tortoise",
      trap: "It is terrestrial.",
      hook: "Dome shell",
    },
    {
      id: 122,
      cardType: "Example",
      title: "Calotes",
      front: "Common name for Calotes?",
      back: "Garden lizard",
      trap: "It is not poisonous.",
      hook: "Colour change",
    },
    {
      id: 123,
      cardType: "Example",
      title: "Chameleon",
      front: "Common name for Chameleon?",
      back: "Tree lizard",
      trap: "Famous for camouflage.",
      hook: "Colour adaptation",
    },
    {
      id: 124,
      cardType: "Example",
      title: "Crocodilus",
      front: "Heart exception in Crocodiles?",
      back: "Four-chambered heart.",
      trap: "The only reptile with a fully 4-chambered heart.",
      hook: "Reptile exception",
    },
    {
      id: 125,
      cardType: "Example",
      title: "Alligator",
      front: "Identify the Alligator.",
      back: "Alligator; Broader snout.",
      trap: "Found in freshwater.",
      hook: "Freshwater",
    },
    {
      id: 126,
      cardType: "Example",
      title: "Hemidactylus",
      front: "Common name for Hemidactylus?",
      back: "Wall lizard",
      trap: "Has adhesive pads.",
      hook: "Climbing",
    },
    {
      id: 127,
      cardType: "Example",
      title: "Naja",
      front: "Common name and venom of Naja?",
      back: "Cobra; Neurotoxic.",
      trap: "Possesses a hood.",
      hook: "Hood present",
    },
    {
      id: 128,
      cardType: "Example",
      title: "Bangarus",
      front: "Common name for Bangarus?",
      back: "Krait",
      trap: "Highly venomous; lacks a hood.",
      hook: "No hood",
    },
    {
      id: 129,
      cardType: "Example",
      title: "Vipera",
      front: "Common name and head shape of Vipera?",
      back: "Viper; Triangular head.",
      trap: "Venom is hemotoxic.",
      hook: "Triangular head",
    },
    {
      id: 130,
      cardType: "Concept",
      title: "Aves",
      front: "Identifying feature of Aves?",
      back: "Presence of feathers.",
      trap: "Not all birds can fly (e.g., Ostrich).",
      hook: "Flight adaptation",
    },
    {
      id: 131,
      cardType: "Concept",
      title: "Bird bones",
      front: "What are 'Pneumatic bones'?",
      back: "Hollow bones with air cavities.",
      trap: "Makes the body lightweight.",
      hook: "Air cavities",
    },
    {
      id: 132,
      cardType: "Concept",
      title: "Bird heart",
      front: "Describe the bird heart.",
      back: "Four-chambered and efficient.",
      trap: "Enables Endothermy (warm-bloodedness).",
      hook: "Endothermy",
    },
    {
      id: 133,
      cardType: "Example",
      title: "Corvus",
      front: "Common name for Corvus?",
      back: "Crow",
      trap: "An intelligent omnivore.",
      hook: "Intelligent bird",
    },
    {
      id: 134,
      cardType: "Example",
      title: "Columba",
      front: "Common name for Columba?",
      back: "Pigeon",
      trap: "Famous for homing ability.",
      hook: "Navigation",
    },
    {
      id: 135,
      cardType: "Example",
      title: "Psittacula",
      front: "Common name for Psittacula?",
      back: "Parrot",
      trap: "Capable of mimicry.",
      hook: "Vocal mimicry",
    },
    {
      id: 136,
      cardType: "Example",
      title: "Struthio",
      front: "Identify Struthio.",
      back: "Ostrich",
      trap: "It is flightless.",
      hook: "Largest bird",
    },
    {
      id: 137,
      cardType: "Example",
      title: "Pavo",
      front: "Common name for Pavo?",
      back: "Peacock",
      trap: "Shows sexual dimorphism.",
      hook: "National bird",
    },
    {
      id: 138,
      cardType: "Example",
      title: "Aptenodytes",
      front: "Identify Aptenodytes.",
      back: "Penguin",
      trap: "It is an aquatic bird; cannot fly.",
      hook: "Cannot fly",
    },
    {
      id: 139,
      cardType: "Example",
      title: "Neophron",
      front: "Common name for Neophron?",
      back: "Vulture",
      trap: "It is a scavenger.",
      hook: "Bone-eating",
    },
    {
      id: 140,
      cardType: "Concept",
      title: "Mammalia",
      front: "Unique feature of Mammals?",
      back: "Mammary glands (milk-producing).",
      trap: "Hairs are also unique, but mammary glands are the defining name.",
      hook: "Milk feeding",
    },
    {
      id: 141,
      cardType: "Concept",
      title: "Mammalian skin",
      front: "Identifying trait of mammalian skin?",
      back: "Presence of hair.",
      trap: "They do not have feathers.",
      hook: "Insulation",
    },
    {
      id: 142,
      cardType: "Concept",
      title: "Mammalian heart",
      front: "Heart chamber count in mammals?",
      back: "Four-chambered.",
      trap: "Complete separation of oxygenated and deoxygenated blood.",
      hook: "Warm-blooded",
    },
    {
      id: 143,
      cardType: "Example",
      title: "Ornithorhynchus",
      front: "What is unique about the Platypus?",
      back: "Oviparous (egg-laying) mammal.",
      trap: "It is a rare exception to viviparity.",
      hook: "Egg-laying exception",
    },
    {
      id: 144,
      cardType: "Example",
      title: "Macropus",
      front: "Common name and type of Macropus?",
      back: "Kangaroo; Marsupial.",
      trap: "Has a pouch for young ones.",
      hook: "Pouch",
    },
    {
      id: 145,
      cardType: "Example",
      title: "Pteropus",
      front: "Common name for Pteropus?",
      back: "Flying fox (Fruit bat).",
      trap: "Capable of true flight.",
      hook: "Largest bat",
    },
    {
      id: 146,
      cardType: "Example",
      title: "Camelus",
      front: "Common name for Camelus?",
      back: "Camel",
      trap: "Stores fat in the hump.",
      hook: "Desert adaptation",
    },
    {
      id: 147,
      cardType: "Example",
      title: "Macaca",
      front: "Identify Macaca.",
      back: "Monkey",
      trap: "A primate with opposable thumbs.",
      hook: "Opposable thumb",
    },
    {
      id: 148,
      cardType: "Example",
      title: "Rattus",
      front: "Identify Rattus.",
      back: "Rat",
      trap: "A rodent with gnawing incisors.",
      hook: "Gnawing incisors",
    },
    {
      id: 149,
      cardType: "Example",
      title: "Canis",
      front: "Common name for Canis?",
      back: "Dog",
      trap: "A carnivore.",
      hook: "Loyalty",
    },
    {
      id: 150,
      cardType: "Example",
      title: "Felis",
      front: "Identify Felis.",
      back: "Cat",
      trap: "Has retractile claws.",
      hook: "Predator",
    },
    {
      id: 151,
      cardType: "Example",
      title: "Elephas",
      front: "Identify Elephas.",
      back: "Elephant",
      trap: "Largest land mammal.",
      hook: "Trunk",
    },
    {
      id: 152,
      cardType: "Example",
      title: "Equus",
      front: "Identify Equus.",
      back: "Horse",
      trap: "A fast-running herbivore.",
      hook: "Speed",
    },
    {
      id: 153,
      cardType: "Example",
      title: "Delphinus",
      front: "Common name for Delphinus?",
      back: "Dolphin",
      trap: "It is a mammal, not a fish.",
      hook: "Aquatic mammal",
    },
    {
      id: 154,
      cardType: "Example",
      title: "Balaenoptera",
      front: "Identify Balaenoptera.",
      back: "Blue whale",
      trap: "Largest animal ever.",
      hook: "Marine mammal",
    },
    {
      id: 155,
      cardType: "Example",
      title: "Panthera tigris",
      front: "Identify Panthera tigris.",
      back: "Tiger",
      trap: "A solitary predator.",
      hook: "Apex predator",
    },
    {
      id: 156,
      cardType: "Example",
      title: "Panthera leo",
      front: "Identify Panthera leo.",
      back: "Lion",
      trap: "Social; lives in a pride.",
      hook: "Pride structure",
    },
  ],
};
