/**
 * Built-in deck: NEET Biomolecules (NEET Biology, Chapter 9)
 * 120 high-yield NCERT cards with NEET traps and pro-tips.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const biomoleculesDeck: BuiltinDeck = {
  id: "builtin-biomolecules",
  name: "NEET Biomolecules",
  description:
    "120 high-yield NCERT cards covering Chemical Analysis, Amino Acids, Lipids, Nucleotides, Enzymes, and more — with NEET traps and pro-tips.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Chemical Analysis",
      title: "Acid used to grind living tissue",
      front: "Acid used to grind living tissue",
      back: "Trichloroacetic acid (TCA)",
      trap: "HCl is NOT used here.",
      hook: "This is a specific NCERT reagent for chemical analysis.",
    },
    {
      id: 2,
      cardType: "Chemical Analysis",
      title: "Purpose of grinding tissue in TCA",
      front: "Purpose of grinding tissue in TCA",
      back: "To break cells and extract biomolecules into a slurry.",
      trap: "It is NOT for 'digestion' of the tissue.",
      hook: "Standard lab method for separation.",
    },
    {
      id: 3,
      cardType: "Chemical Analysis",
      title: "Physical state of the product after grinding",
      front: "Physical state of the product after grinding",
      back: "Thick slurry",
      trap: "It's not a clear 'solution' yet.",
      hook: "Semi-solid mixture ready for filtration.",
    },
    {
      id: 4,
      cardType: "Chemical Analysis",
      title: "Method used to separate the slurry",
      front: "Method used to separate the slurry",
      back: "Filtration through cheesecloth or cotton.",
      trap: "It is NOT centrifugation in this specific NCERT experiment.",
      hook: "Simple gravity filtration.",
    },
    {
      id: 5,
      cardType: "Chemical Analysis",
      title: "Names of the two fractions obtained",
      front: "Names of the two fractions obtained",
      back: "Acid-soluble pool (Filtrate) & Acid-insoluble fraction (Retentate).",
      trap: "Don't swap names; Filtrate = Soluble.",
      hook: "Soluble = what passes through; Insoluble = what stays behind.",
    },
    {
      id: 6,
      cardType: "Chemical Analysis",
      title: "Contents of the Acid-soluble pool",
      front: "Contents of the Acid-soluble pool",
      back: "Small organic molecules (Micromolecules).",
      trap: "Does NOT contain polymers.",
      hook: "Molecular weight < 800 Daltons.",
    },
    {
      id: 7,
      cardType: "Chemical Analysis",
      title: "Contents of the Acid-insoluble fraction",
      front: "Contents of the Acid-insoluble fraction",
      back: "Macromolecules (Proteins, Nucleic Acids, Polysaccharides) and Lipids.",
      trap: "Lipids are here, but they aren't 'true' macromolecules.",
      hook: "Structural components and aggregates.",
    },
    {
      id: 8,
      cardType: "Chemical Analysis",
      title: "NCERT Definition of Biomolecules",
      front: "NCERT Definition of Biomolecules",
      back: "All carbon compounds found in living tissues.",
      trap: "CO2 and inorganic carbons are usually excluded in this context.",
      hook: "Organic compounds only.",
    },
    {
      id: 9,
      cardType: "Chemical Analysis",
      title: "Why thousands of compounds are in the filtrate?",
      front: "Why thousands of compounds are in the filtrate?",
      back: "Reflects diverse cellular metabolism.",
      trap: "It's not contamination; it's the 'Metabolic Pool'.",
      hook: "Cellular diversity at work.",
    },
    {
      id: 10,
      cardType: "Chemical Analysis",
      title: "What represents the cytoplasmic composition?",
      front: "What represents the cytoplasmic composition?",
      back: "The Acid-soluble pool.",
      trap: "It doesn't represent the 'whole' cell, just mostly cytosol.",
      hook: "Small molecules reflect current metabolic state.",
    },
    {
      id: 11,
      cardType: "Chemical Analysis",
      title: "Where are organellar components found?",
      front: "Where are organellar components found?",
      back: "Acid-insoluble fraction.",
      trap: "They are NOT in the soluble pool.",
      hook: "Membranes and organelles are structural and large.",
    },
    {
      id: 12,
      cardType: "Chemical Analysis",
      title: "Why are lipids found in the insoluble fraction?",
      front: "Why are lipids found in the insoluble fraction?",
      back: "Hydrophobic nature causes them to form vesicles/aggregates.",
      trap: "It's NOT because they are large polymers (they aren't).",
      hook: "Lipids have long hydrocarbon chains.",
    },
    {
      id: 13,
      cardType: "Wet/Dry Weight",
      title: "What is 'Wet Weight'?",
      front: "What is 'Wet Weight'?",
      back: "Weight of fresh tissue containing water.",
      trap: "Not the same as dry mass.",
      hook: "Initial measurement before processing.",
    },
    {
      id: 14,
      cardType: "Wet/Dry Weight",
      title: "What is 'Dry Weight'?",
      front: "What is 'Dry Weight'?",
      back: "Weight of tissue after all water has evaporated.",
      trap: "This is NOT the ash.",
      hook: "Used to measure organic + inorganic content sans water.",
    },
    {
      id: 15,
      cardType: "Wet/Dry Weight",
      title: "Result of burning tissue ('Ashing')",
      front: "Result of burning tissue ('Ashing')",
      back: "Organic compounds are oxidized (released as CO2/H2O); inorganic remains.",
      trap: "Burning doesn't remove minerals.",
      hook: "Oxidation removes the 'carbon' part.",
    },
    {
      id: 16,
      cardType: "Wet/Dry Weight",
      title: "Definition of 'Ash'",
      front: "Definition of 'Ash'",
      back: "Inorganic residue remaining after burning.",
      trap: "Ash contains NO carbon.",
      hook: "Think of it as the 'Mineral' content.",
    },
    {
      id: 17,
      cardType: "Wet/Dry Weight",
      title: "Elements found in Ash",
      front: "Elements found in Ash",
      back: "Ca, Mg, Na, K, etc.",
      trap: "No organic compounds like glucose.",
      hook: "Inorganic ions only.",
    },
    {
      id: 18,
      cardType: "Wet/Dry Weight",
      title: "Purpose of Ash analysis",
      front: "Purpose of Ash analysis",
      back: "To study the mineral/elemental composition of tissue.",
      trap: "Not used for biomolecule study.",
      hook: "Inorganic chemistry of life.",
    },
    {
      id: 19,
      cardType: "Composition",
      title: "Most abundant element in the human body?",
      front: "Most abundant element in the human body?",
      back: "Oxygen",
      trap: "Students often guess Carbon.",
      hook: "Body is ~65-70% water (H2O), hence Oxygen dominates mass.",
    },
    {
      id: 20,
      cardType: "Composition",
      title: "Carbon percentage in human body?",
      front: "Carbon percentage in human body?",
      back: "~18.5%",
      trap: "Often underestimated compared to Earth's crust.",
      hook: "Foundation of organic life.",
    },
    {
      id: 21,
      cardType: "Composition",
      title: "Hydrogen percentage in human body?",
      front: "Hydrogen percentage in human body?",
      back: "~0.5%",
      trap: "Appears low because H is very light.",
      hook: "Though low by mass, H atoms are extremely numerous.",
    },
    {
      id: 22,
      cardType: "Composition",
      title: "Oxygen percentage in Earth's crust?",
      front: "Oxygen percentage in Earth's crust?",
      back: "~46.6%",
      trap: "Context differs; in crust, it's in rocks/silicates.",
      hook: "Oxygen is abundant in both crust and life.",
    },
    {
      id: 23,
      cardType: "Composition",
      title: "Abundance of Silicon in life?",
      front: "Abundance of Silicon in life?",
      back: "Negligible / Trace",
      trap: "Crucial in crust, but not in biology.",
      hook: "Life is Carbon-based, not Silicon-based.",
    },
    {
      id: 24,
      cardType: "Composition",
      title: "Why does Carbon dominate life?",
      front: "Why does Carbon dominate life?",
      back: "Ability to form stable covalent bonds (Tetravalency).",
      trap: "Not because it's the most abundant element (Oxygen is).",
      hook: "Versatility in structure.",
    },
    {
      id: 25,
      cardType: "Composition",
      title: "What does elemental analysis provide?",
      front: "What does elemental analysis provide?",
      back: "Percentage composition of elements (C, H, O, N, etc.).",
      trap: "It does NOT tell you the compounds/molecules.",
      hook: "Atomic level study.",
    },
    {
      id: 26,
      cardType: "Composition",
      title: "What does compound analysis provide?",
      front: "What does compound analysis provide?",
      back: "Identifies organic/inorganic molecules present.",
      trap: "Doesn't just give atomic ratios.",
      hook: "Molecular level study.",
    },
    {
      id: 27,
      cardType: "Amino Acids",
      title: "Type of Amino Acids found in proteins?",
      front: "Type of Amino Acids found in proteins?",
      back: "alpha-amino acids",
      trap: "Beta or Gamma amino acids are not used in protein synthesis.",
      hook: "NH2 and COOH are on the same Carbon (alpha-C).",
    },
    {
      id: 28,
      cardType: "Amino Acids",
      title: "Four groups attached to alpha-carbon in AA?",
      front: "Four groups attached to alpha-carbon in AA?",
      back: "Amino (-NH2), Carboxyl (-COOH), Hydrogen (-H), and Variable Group (-R).",
      trap: "All four must be identified correctly.",
      hook: "Think of it as a 'Substituted Methane'.",
    },
    {
      id: 29,
      cardType: "Amino Acids",
      title: "Number of standard AAs in proteins?",
      front: "Number of standard AAs in proteins?",
      back: "20",
      trap: "Don't confuse with total AAs in nature (hundreds).",
      hook: "The 'Standard 20'.",
    },
    {
      id: 30,
      cardType: "Amino Acids",
      title: "R-group of Glycine?",
      front: "R-group of Glycine?",
      back: "Hydrogen (-H)",
      trap: "It is NOT chiral (it's achiral).",
      hook: "Simplest and smallest amino acid.",
    },
    {
      id: 31,
      cardType: "Amino Acids",
      title: "R-group of Alanine?",
      front: "R-group of Alanine?",
      back: "Methyl group (-CH3)",
      trap: "Don't confuse with Serine's -OH.",
      hook: "Basic aliphatic R-group.",
    },
    {
      id: 32,
      cardType: "Amino Acids",
      title: "R-group of Serine?",
      front: "R-group of Serine?",
      back: "Hydroxyl-methyl (-CH2OH)",
      trap: "It is polar due to -OH.",
      hook: "Think 'S' for 'Serine' and 'Sugar-like' (-OH).",
    },
    {
      id: 33,
      cardType: "Amino Acids",
      title: "Example of an Acidic Amino Acid?",
      front: "Example of an Acidic Amino Acid?",
      back: "Glutamic acid (or Aspartic acid).",
      trap: "Extra -COOH group makes it acidic.",
      hook: "Look for 'Acid' in the name.",
    },
    {
      id: 34,
      cardType: "Amino Acids",
      title: "Example of a Basic Amino Acid?",
      front: "Example of a Basic Amino Acid?",
      back: "Lysine (or Arginine/Histidine).",
      trap: "Histidine is tricky at different pH.",
      hook: "Extra -NH2 group.",
    },
    {
      id: 35,
      cardType: "Amino Acids",
      title: "Example of a Neutral Amino Acid?",
      front: "Example of a Neutral Amino Acid?",
      back: "Valine",
      trap: "Neutral means no charge on R-group.",
      hook: "Aliphatic chains are usually neutral.",
    },
    {
      id: 36,
      cardType: "Amino Acids",
      title: "The three Aromatic Amino Acids?",
      front: "The three Aromatic Amino Acids?",
      back: "Tyrosine, Phenylalanine, Tryptophan.",
      trap: "Histidine is NOT technically in this NCERT trio list.",
      hook: "Remember: YFW (Yellow Flowers Wilt).",
    },
    {
      id: 37,
      cardType: "Amino Acids",
      title: "Ionizable groups in Amino Acids?",
      front: "Ionizable groups in Amino Acids?",
      back: "Amino (-NH2) and Carboxyl (-COOH).",
      trap: "Some R-groups ionize too, but primary are these.",
      hook: "Charge depends on pH.",
    },
    {
      id: 38,
      cardType: "Amino Acids",
      title: "What is a Zwitterion?",
      front: "What is a Zwitterion?",
      back: "Dipolar form with both positive and negative charges.",
      trap: "It is electrically neutral overall but has ions.",
      hook: "Occurs at specific pH.",
    },
    {
      id: 39,
      cardType: "Amino Acids",
      title: "What is the Isoelectric Point (pI)?",
      front: "What is the Isoelectric Point (pI)?",
      back: "The pH at which the net charge of an AA is zero.",
      trap: "It's NOT always pH 7.",
      hook: "Specific for each amino acid.",
    },
    {
      id: 40,
      cardType: "Amino Acids",
      title: "Proteins are polymers of...?",
      front: "Proteins are polymers of...?",
      back: "Amino Acids",
      trap: "They are NOT polymers of nucleotides.",
      hook: "They form 'Polypeptides'.",
    },
    {
      id: 41,
      cardType: "Amino Acids",
      title: "Peptide bond is formed between...?",
      front: "Peptide bond is formed between...?",
      back: "Carboxyl group of one AA and Amino group of the next.",
      trap: "R-groups do NOT participate in peptide bonding.",
      hook: "Dehydration/Condensation reaction.",
    },
    {
      id: 42,
      cardType: "Amino Acids",
      title: "Standard direction of a polypeptide?",
      front: "Standard direction of a polypeptide?",
      back: "N-terminal to C-terminal",
      trap: "Never C to N.",
      hook: "Sequence starts at NH2 and ends at COOH.",
    },
    {
      id: 43,
      cardType: "Amino Acids",
      title: "Source of Essential Amino Acids?",
      front: "Source of Essential Amino Acids?",
      back: "Diet",
      trap: "Our body CANNOT synthesize them.",
      hook: "Nutrition is the only link.",
    },
    {
      id: 44,
      cardType: "Amino Acids",
      title: "What are Non-essential Amino Acids?",
      front: "What are Non-essential Amino Acids?",
      back: "Synthesized by our body.",
      trap: "Doesn't mean they aren't needed; just means we make them.",
      hook: "Metabolism produces these.",
    },
    {
      id: 45,
      cardType: "Lipids",
      title: "Solubility of Lipids?",
      front: "Solubility of Lipids?",
      back: "Water-insoluble (Hydrophobic).",
      trap: "They are found in the acid-insoluble fraction.",
      hook: "Oil and water don't mix.",
    },
    {
      id: 46,
      cardType: "Lipids",
      title: "Structure of a Fatty Acid?",
      front: "Structure of a Fatty Acid?",
      back: "A carboxyl group attached to an R-group (Hydrocarbon chain).",
      trap: "Fatty acids are NOT glycerol.",
      hook: "Long chains ending in COOH.",
    },
    {
      id: 47,
      cardType: "Lipids",
      title: "Saturated Fatty Acid?",
      front: "Saturated Fatty Acid?",
      back: "No double bonds in the hydrocarbon chain.",
      trap: "Usually solid at room temp (fats).",
      hook: "Animal fats are mostly saturated.",
    },
    {
      id: 48,
      cardType: "Lipids",
      title: "Unsaturated Fatty Acid?",
      front: "Unsaturated Fatty Acid?",
      back: "One or more double bonds (C=C).",
      trap: "Liquid at room temp (oils).",
      hook: "Plant oils are mostly unsaturated.",
    },
    {
      id: 49,
      cardType: "Lipids",
      title: "Carbons in Palmitic Acid?",
      front: "Carbons in Palmitic Acid?",
      back: "16 (including the carboxyl carbon).",
      trap: "Don't count just the R-group.",
      hook: "Very common saturated fatty acid.",
    },
    {
      id: 50,
      cardType: "Lipids",
      title: "Carbons in Arachidonic Acid?",
      front: "Carbons in Arachidonic Acid?",
      back: "20 (including carboxyl carbon).",
      trap: "Arachidic is 20 (sat), Arachidonic is 20 (unsat).",
      hook: "Polyunsaturated (PUFA).",
    },
    {
      id: 51,
      cardType: "Lipids",
      title: "Chemical nature of Glycerol?",
      front: "Chemical nature of Glycerol?",
      back: "Trihydroxy propane.",
      trap: "It's a simple alcohol, not a complex lipid itself.",
      hook: "The backbone for fats.",
    },
    {
      id: 52,
      cardType: "Lipids",
      title: "Bond found in Lipids?",
      front: "Bond found in Lipids?",
      back: "Ester Bond",
      trap: "Not peptide or glycosidic.",
      hook: "Formed between Fatty Acid and Alcohol (Glycerol).",
    },
    {
      id: 53,
      cardType: "Lipids",
      title: "What is a Triglyceride?",
      front: "What is a Triglyceride?",
      back: "Glycerol esterified with three fatty acids.",
      trap: "Main form of energy storage.",
      hook: "High calorie density.",
    },
    {
      id: 54,
      cardType: "Lipids",
      title: "Difference between Oils and Fats?",
      front: "Difference between Oils and Fats?",
      back: "Melting point.",
      trap: "They are chemically similar (esters).",
      hook: "Oils have lower melting points.",
    },
    {
      id: 55,
      cardType: "Lipids",
      title: "Why do oils remain liquid in winter?",
      front: "Why do oils remain liquid in winter?",
      back: "Low melting point due to unsaturation.",
      trap: "Not because they are smaller.",
      hook: "Gingelly oil is a classic example.",
    },
    {
      id: 56,
      cardType: "Lipids",
      title: "What do Phospholipids contain?",
      front: "What do Phospholipids contain?",
      back: "Phosphate group and an organic/nitrogenous base.",
      trap: "They are not simple triglycerides.",
      hook: "Major component of cell membranes.",
    },
    {
      id: 57,
      cardType: "Lipids",
      title: "NCERT example of a Phospholipid?",
      front: "NCERT example of a Phospholipid?",
      back: "Lecithin",
      trap: "Memorize this specific name.",
      hook: "Found in egg yolk and cell membranes.",
    },
    {
      id: 58,
      cardType: "Lipids",
      title: "Why are lipids in the insoluble fraction if they are small?",
      front: "Why are lipids in the insoluble fraction if they are small?",
      back: "They form large membrane vesicles that don't pass through filter.",
      trap: "Their molecular weight is < 800 Da (Micromolecule).",
      hook: "Insolubility is due to structure/aggregation.",
    },
    {
      id: 59,
      cardType: "Nucleotides",
      title: "List the Nitrogenous Bases.",
      front: "List the Nitrogenous Bases.",
      back: "Adenine, Guanine, Cytosine, Thymine, Uracil.",
      trap: "Uracil is RNA only; Thymine is DNA only.",
      hook: "A, G, C, T, U.",
    },
    {
      id: 60,
      cardType: "Nucleotides",
      title: "Which are Purines?",
      front: "Which are Purines?",
      back: "Adenine (A) and Guanine (G).",
      trap: "Double ring structures.",
      hook: "Pure As Gold (Purine = A, G).",
    },
    {
      id: 61,
      cardType: "Nucleotides",
      title: "Which are Pyrimidines?",
      front: "Which are Pyrimidines?",
      back: "Cytosine, Thymine, Uracil.",
      trap: "Single ring structures.",
      hook: "CUT the Pie (Pyrimidines = C, U, T).",
    },
    {
      id: 62,
      cardType: "Nucleotides",
      title: "Composition of a Nucleoside?",
      front: "Composition of a Nucleoside?",
      back: "Nitrogen Base + Pentose Sugar.",
      trap: "No phosphate here.",
      hook: "Base + Sugar = Nucleoside.",
    },
    {
      id: 63,
      cardType: "Nucleotides",
      title: "Composition of a Nucleotide?",
      front: "Composition of a Nucleotide?",
      back: "Nitrogen Base + Pentose Sugar + Phosphate.",
      trap: "One phosphate is enough to be called a nucleotide.",
      hook: "Nucleoside + P = Nucleotide.",
    },
    {
      id: 64,
      cardType: "Nucleotides",
      title: "Sugar in DNA?",
      front: "Sugar in DNA?",
      back: "2'-deoxyribose",
      trap: "Lacks Oxygen at the 2' position.",
      hook: "More stable than ribose.",
    },
    {
      id: 65,
      cardType: "Nucleotides",
      title: "Sugar in RNA?",
      front: "Sugar in RNA?",
      back: "Ribose",
      trap: "Has -OH at 2' position.",
      hook: "Makes RNA more reactive/less stable.",
    },
    {
      id: 66,
      cardType: "Nucleotides",
      title: "Primary role of DNA/RNA?",
      front: "Primary role of DNA/RNA?",
      back: "Genetic material / Information storage.",
      trap: "They are NOT primarily for energy (that's ATP).",
      hook: "Central dogma of life.",
    },
    {
      id: 67,
      cardType: "Metabolites",
      title: "What are Primary Metabolites?",
      front: "What are Primary Metabolites?",
      back: "Essential for basic physiological processes (energy, growth).",
      trap: "Found universally in all living organisms.",
      hook: "Examples: Glucose, Amino Acids.",
    },
    {
      id: 68,
      cardType: "Metabolites",
      title: "Where are Secondary Metabolites found?",
      front: "Where are Secondary Metabolites found?",
      back: "Plants, fungi, and microbes.",
      trap: "Usually NOT found in animals.",
      hook: "Ecological role.",
    },
    {
      id: 69,
      cardType: "Metabolites",
      title: "Examples of Secondary Metabolites?",
      front: "Examples of Secondary Metabolites?",
      back: "Alkaloids, Flavonoids, Antibiotics, Pigments.",
      trap: "Not directly required for immediate survival.",
      hook: "Useful for human welfare (medicines).",
    },
    {
      id: 70,
      cardType: "Metabolites",
      title: "Function of Secondary Metabolites?",
      front: "Function of Secondary Metabolites?",
      back: "Ecological advantage (Defense, attraction).",
      trap: "Function in host is often unknown.",
      hook: "Adaptation to environment.",
    },
    {
      id: 71,
      cardType: "Macromolecules",
      title: "Molecular weight range of Acid-soluble pool?",
      front: "Molecular weight range of Acid-soluble pool?",
      back: "18 to 800 Daltons.",
      trap: "Exact NCERT range.",
      hook: "These are Biomicromolecules.",
    },
    {
      id: 72,
      cardType: "Macromolecules",
      title: "Molecular weight of Macromolecules?",
      front: "Molecular weight of Macromolecules?",
      back: "> 10,000 Daltons.",
      trap: "Lipids are the exception (< 800 Da).",
      hook: "Usually polymers.",
    },
    {
      id: 73,
      cardType: "Macromolecules",
      title: "Four major classes in the Insoluble fraction?",
      front: "Four major classes in the Insoluble fraction?",
      back: "Proteins, Nucleic Acids, Polysaccharides, and Lipids.",
      trap: "Lipids are technically NOT macromolecules.",
      hook: "Membrane components.",
    },
    {
      id: 74,
      cardType: "Macromolecules",
      title: "Which are the 'True Polymers'?",
      front: "Which are the 'True Polymers'?",
      back: "Proteins, Polysaccharides, Nucleic Acids.",
      trap: "Lipids are NOT polymers.",
      hook: "Made of repeating monomer units.",
    },
    {
      id: 75,
      cardType: "Macromolecules",
      title: "Percentage of Water in a cell?",
      front: "Percentage of Water in a cell?",
      back: "70% - 90%",
      trap: "Highest component by mass.",
      hook: "Universal biological solvent.",
    },
    {
      id: 76,
      cardType: "Macromolecules",
      title: "Percentage of Protein in a cell?",
      front: "Percentage of Protein in a cell?",
      back: "10% - 15%",
      trap: "Second most abundant after water.",
      hook: "The main structural/functional solid.",
    },
    {
      id: 77,
      cardType: "Macromolecules",
      title: "Percentage of Carbohydrates in a cell?",
      front: "Percentage of Carbohydrates in a cell?",
      back: "~3%",
      trap: "Lower than proteins/water.",
      hook: "Energy reserve.",
    },
    {
      id: 78,
      cardType: "Macromolecules",
      title: "Percentage of Lipids in a cell?",
      front: "Percentage of Lipids in a cell?",
      back: "~2%",
      trap: "Found in membranes, but total % is low.",
      hook: "Structural lipids dominate.",
    },
    {
      id: 79,
      cardType: "Enzymes",
      title: "Chemical nature of Enzymes?",
      front: "Chemical nature of Enzymes?",
      back: "Mostly Proteins.",
      trap: "Not ALL enzymes are proteins.",
      hook: "Functional 3D shape is key.",
    },
    {
      id: 80,
      cardType: "Enzymes",
      title: "What are Ribozymes?",
      front: "What are Ribozymes?",
      back: "Catalytic RNA molecules.",
      trap: "Non-protein enzymes.",
      hook: "Evidence of an 'RNA World'.",
    },
    {
      id: 81,
      cardType: "Enzymes",
      title: "What is an Active Site?",
      front: "What is an Active Site?",
      back: "A crevice or pocket where the substrate binds.",
      trap: "Shape is highly specific.",
      hook: "Lock-and-Key mechanism.",
    },
    {
      id: 82,
      cardType: "Enzymes",
      title: "Why are enzymes highly specific?",
      front: "Why are enzymes highly specific?",
      back: "Unique Tertiary (3D) structure.",
      trap: "Primary structure alone isn't enough.",
      hook: "Folding creates the active site.",
    },
    {
      id: 83,
      cardType: "Enzymes",
      title: "Optimum temperature for human enzymes?",
      front: "Optimum temperature for human enzymes?",
      back: "~37°C",
      trap: "High heat (>40°C) denatures most.",
      hook: "Corresponds to body temp.",
    },
    {
      id: 84,
      cardType: "Enzymes",
      title: "Stability of Thermophilic enzymes?",
      front: "Stability of Thermophilic enzymes?",
      back: "80°C - 90°C",
      trap: "Special proteins from extremophiles.",
      hook: "Example: Taq Polymerase.",
    },
    {
      id: 85,
      cardType: "Enzymes",
      title: "Definition of Reaction Rate?",
      front: "Definition of Reaction Rate?",
      back: "Amount of product formed per unit time (dP/dt).",
      trap: "Not just total product.",
      hook: "Kinetics measurement.",
    },
    {
      id: 86,
      cardType: "Enzymes",
      title: "Effect of Temperature on Rate?",
      front: "Effect of Temperature on Rate?",
      back: "Rate doubles or halves for every 10°C change.",
      trap: "Only until the optimum is reached.",
      hook: "Q10 rule of thumb.",
    },
    {
      id: 87,
      cardType: "Enzymes",
      title: "Primary role of an enzyme?",
      front: "Primary role of an enzyme?",
      back: "To lower the Activation Energy (Ea).",
      trap: "It does NOT change Delta G (Gibbs Free Energy).",
      hook: "Lowers the 'Energy Barrier'.",
    },
    {
      id: 88,
      cardType: "Enzymes",
      title: "Effect of Carbonic Anhydrase?",
      front: "Effect of Carbonic Anhydrase?",
      back: "Speeds up CO2 + H2O reaction by 10 million times.",
      trap: "One of the fastest enzymes known.",
      hook: "Essential for respiration.",
    },
    {
      id: 90,
      cardType: "Enzymes",
      title: "Enzymes in Glycolysis (Glucose to Pyruvate)?",
      front: "Enzymes in Glycolysis (Glucose to Pyruvate)?",
      back: "10 different enzymes.",
      trap: "It is a multi-step pathway.",
      hook: "Central energy pathway.",
    },
    {
      id: 91,
      cardType: "Enzymes",
      title: "Definition of a Substrate (S)?",
      front: "Definition of a Substrate (S)?",
      back: "The chemical which is converted into product.",
      trap: "Specific to the enzyme's active site.",
      hook: "The reactant.",
    },
    {
      id: 92,
      cardType: "Enzymes",
      title: "The ES Complex?",
      front: "The ES Complex?",
      back: "Enzyme-Substrate complex; mandatory intermediate.",
      trap: "Transient and unstable (short-lived).",
      hook: "Required for catalysis.",
    },
    {
      id: 93,
      cardType: "Enzymes",
      title: "Order of Enzyme action?",
      front: "Order of Enzyme action?",
      back: "E+S -> ES -> EP -> E+P",
      trap: "Must follow this sequence.",
      hook: "Enzyme is released unchanged.",
    },
    {
      id: 94,
      cardType: "Enzymes",
      title: "Transition State (TS)?",
      front: "Transition State (TS)?",
      back: "High energy, unstable state where bonds break/form.",
      trap: "Highest energy peak in the reaction.",
      hook: "The 'Climax' of the reaction.",
    },
    {
      id: 95,
      cardType: "Enzymes",
      title: "What is Activation Energy?",
      front: "What is Activation Energy?",
      back: "Difference in energy between Substrate and Transition state.",
      trap: "Enzymes lower this peak.",
      hook: "The 'Hill' the substrate must climb.",
    },
    {
      id: 96,
      cardType: "Enzymes",
      title: "Effect of pH on Enzyme activity?",
      front: "Effect of pH on Enzyme activity?",
      back: "Narrow range of optimum pH.",
      trap: "Extremes cause denaturation/charge change.",
      hook: "Pepsin (pH 2) vs Trypsin (pH 8).",
    },
    {
      id: 97,
      cardType: "Enzymes",
      title: "Effect of Low Temperature?",
      front: "Effect of Low Temperature?",
      back: "Temporarily inactivates the enzyme.",
      trap: "Does NOT denature it (reversible).",
      hook: "Why we refrigerate food.",
    },
    {
      id: 98,
      cardType: "Enzymes",
      title: "Effect of High Temperature?",
      front: "Effect of High Temperature?",
      back: "Denaturation (Loss of 3D structure).",
      trap: "Irreversible (permanent damage).",
      hook: "Proteins 'unfold'.",
    },
    {
      id: 99,
      cardType: "Enzymes",
      title: "Definition of Vmax?",
      front: "Definition of Vmax?",
      back: "Maximum velocity achieved when enzyme is saturated.",
      trap: "Adding more substrate won't increase rate beyond this.",
      hook: "Enzyme becomes the limiting factor.",
    },
    {
      id: 100,
      cardType: "Enzymes",
      title: "What is Km (Michaelis Constant)?",
      front: "What is Km (Michaelis Constant)?",
      back: "Substrate concentration at which rate is half Vmax.",
      trap: "Lower Km means HIGHER affinity.",
      hook: "Measures how well E binds S.",
    },
    {
      id: 101,
      cardType: "Enzymes",
      title: "Competitive Inhibitor feature?",
      front: "Competitive Inhibitor feature?",
      back: "Closely resembles the substrate in structure.",
      trap: "Competes for the Active Site.",
      hook: "Substrate-mimicry.",
    },
    {
      id: 102,
      cardType: "Enzymes",
      title: "How to overcome Competitive Inhibition?",
      front: "How to overcome Competitive Inhibition?",
      back: "Increase substrate concentration.",
      trap: "Does NOT work for non-competitive inhibition.",
      hook: "Out-compete the inhibitor.",
    },
    {
      id: 103,
      cardType: "Enzymes",
      title: "NCERT Example of Competitive Inhibition?",
      front: "NCERT Example of Competitive Inhibition?",
      back: "Malonate inhibiting Succinate Dehydrogenase.",
      trap: "Malonate mimics Succinate.",
      hook: "Used to control bacterial pathogens.",
    },
    {
      id: 104,
      cardType: "Enzymes",
      title: "Basis of Enzyme Classification?",
      front: "Basis of Enzyme Classification?",
      back: "Type of reaction they catalyze.",
      trap: "Not based on substrate name.",
      hook: "The IUBMB system.",
    },
    {
      id: 105,
      cardType: "Enzymes",
      title: "Total number of Enzyme Classes?",
      front: "Total number of Enzyme Classes?",
      back: "6 Classes.",
      trap: "Fixed number in NCERT.",
      hook: "Each class has sub-classes.",
    },
    {
      id: 106,
      cardType: "Enzymes",
      title: "Oxidoreductases function?",
      front: "Oxidoreductases function?",
      back: "Catalyze oxidation-reduction (Redox).",
      trap: "Also called dehydrogenases.",
      hook: "Transfer of electrons/H.",
    },
    {
      id: 107,
      cardType: "Enzymes",
      title: "Transferases function?",
      front: "Transferases function?",
      back: "Transfer of a group (other than Hydrogen).",
      trap: "Specific to functional groups.",
      hook: "Moving groups between molecules.",
    },
    {
      id: 108,
      cardType: "Enzymes",
      title: "Hydrolases function?",
      front: "Hydrolases function?",
      back: "Bond cleavage using Water (Hydrolysis).",
      trap: "Includes digestive enzymes.",
      hook: "Water is a reactant.",
    },
    {
      id: 109,
      cardType: "Enzymes",
      title: "Lyases function?",
      front: "Lyases function?",
      back: "Removal of groups without hydrolysis, forming double bonds.",
      trap: "Opposite of additions across double bonds.",
      hook: "Group elimination.",
    },
    {
      id: 110,
      cardType: "Enzymes",
      title: "Isomerases function?",
      front: "Isomerases function?",
      back: "Interconversion of optical/geometric/positional isomers.",
      trap: "No atoms are added or removed.",
      hook: "Molecular rearrangement.",
    },
    {
      id: 111,
      cardType: "Enzymes",
      title: "Ligases function?",
      front: "Ligases function?",
      back: "Joining of two molecules using ATP energy.",
      trap: "Requires energy input.",
      hook: "Glue-ing molecules (C-O, C-S, C-N).",
    },
    {
      id: 112,
      cardType: "Enzymes",
      title: "What is an Apoenzyme?",
      front: "What is an Apoenzyme?",
      back: "The protein part of a complex enzyme.",
      trap: "Inactive without its cofactor.",
      hook: "Protein shell.",
    },
    {
      id: 113,
      cardType: "Enzymes",
      title: "What is a Holoenzyme?",
      front: "What is a Holoenzyme?",
      back: "Active enzyme (Apoenzyme + Cofactor).",
      trap: "The complete, functional unit.",
      hook: "Total package.",
    },
    {
      id: 114,
      cardType: "Enzymes",
      title: "The three types of Cofactors?",
      front: "The three types of Cofactors?",
      back: "Prosthetic groups, Coenzymes, and Metal ions.",
      trap: "Be able to distinguish them.",
      hook: "The 'helper' molecules.",
    },
    {
      id: 115,
      cardType: "Enzymes",
      title: "What is a Prosthetic Group?",
      front: "What is a Prosthetic Group?",
      back: "Organic cofactor tightly/permanently bound to apoenzyme.",
      trap: "Not easily removed.",
      hook: "Part of the enzyme structure.",
    },
    {
      id: 116,
      cardType: "Enzymes",
      title: "NCERT Example of a Prosthetic Group?",
      front: "NCERT Example of a Prosthetic Group?",
      back: "Haem in Catalase and Peroxidase.",
      trap: "Haem contains Iron (Fe).",
      hook: "Essential for H2O2 breakdown.",
    },
    {
      id: 117,
      cardType: "Enzymes",
      title: "Nature of a Coenzyme?",
      front: "Nature of a Coenzyme?",
      back: "Organic, loosely/transiently bound to apoenzyme.",
      trap: "Usually vitamin-derived.",
      hook: "Temporary helpers.",
    },
    {
      id: 118,
      cardType: "Enzymes",
      title: "Vitamin found in NAD and NADP?",
      front: "Vitamin found in NAD and NADP?",
      back: "Niacin (Vitamin B3).",
      trap: "Don't confuse with Riboflavin (B2).",
      hook: "Essential for redox reactions.",
    },
    {
      id: 119,
      cardType: "Enzymes",
      title: "Role of Metal ion cofactors?",
      front: "Role of Metal ion cofactors?",
      back: "Form coordination bonds with substrate and active site.",
      trap: "Activity is lost if metal is removed.",
      hook: "Stabilization.",
    },
    {
      id: 120,
      cardType: "Enzymes",
      title: "NCERT Example of Metal ion cofactor?",
      front: "NCERT Example of Metal ion cofactor?",
      back: "Zinc (Zn2+) in Carboxypeptidase.",
      trap: "Specifically a proteolytic enzyme.",
      hook: "Zinc is common in many enzymes.",
    },
  ],
};
