/**
 * Built-in deck: Chemical Coordination & Integration (NEET Biology, Chapter 22)
 * 83 high-yield NCERT cards with NEET traps and NCERT hooks.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const chemicalCoordinationDeck: BuiltinDeck = {
  id: "builtin-chemical-coordination",
  name: "Chemical Coordination & Integration",
  description:
    "83 high-yield NCERT cards covering hormones, glands, disorders, and signaling mechanisms — with NEET traps and NCERT hooks on every card.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Gland",
      title: "Endocrine glands",
      front: "Define endocrine glands based on their physical structure.",
      back: "Ductless glands.",
      trap: "NEET Trap: No ducts present.",
      hook: "Hormones released directly into blood.",
    },
    {
      id: 2,
      cardType: "Hormone",
      title: "Hormones definition",
      front: "What is the NCERT definition of hormones?",
      back: "Non-nutrient chemical messengers.",
      trap: "NEET Trap: Act in trace amounts.",
      hook: "Intercellular communication.",
    },
    {
      id: 3,
      cardType: "Hormone",
      title: "Classical hormone",
      front: "State the 'classical' definition of a hormone.",
      back: "Secreted into blood and acts on distant target.",
      trap: "NEET Trap: Distance from source to target.",
      hook: "Endocrine signalling.",
    },
    {
      id: 4,
      cardType: "Comparison",
      title: "Neural vs Endocrine",
      front: "Compare Neural vs Endocrine coordination speeds.",
      back: "Neural: Fast & short-lived; Endocrine: Slow & long-lasting.",
      trap: "NEET Trap: Duration of effect.",
      hook: "Complementary systems.",
    },
    {
      id: 5,
      cardType: "Location",
      title: "Hypothalamus location",
      front: "Where is the hypothalamus located?",
      back: "At the basal part of diencephalon.",
      trap: "NEET Trap: Part of forebrain.",
      hook: "Neuroendocrine link.",
    },
    {
      id: 6,
      cardType: "Cell",
      title: "Neurosecretory nuclei",
      front: "What are the hormone-producing cells in the hypothalamus called?",
      back: "Neurosecretory nuclei.",
      trap: "NEET Trap: They are neurons, not typical glandular cells.",
      hook: "Produce hormones.",
    },
    {
      id: 7,
      cardType: "Hormone",
      title: "Hypothalamic hormones",
      front: "What are the two types of hormones produced by the hypothalamus?",
      back: "Releasing hormones (RH) and Inhibiting hormones (IH).",
      trap: "NEET Trap: They control the pituitary, not target organs directly.",
      hook: "RH & IH.",
    },
    {
      id: 8,
      cardType: "Hormone",
      title: "GnRH function",
      front: "What is the function of GnRH?",
      back: "Stimulates the pituitary to release LH and FSH.",
      trap: "NEET Trap: Acts on pituitary, not gonads directly.",
      hook: "Reproduction control.",
    },
    {
      id: 9,
      cardType: "Hormone",
      title: "Somatostatin",
      front: "How does Somatostatin affect growth?",
      back: "Inhibits the release of Growth Hormone (GH).",
      trap: "NEET Trap: It is inhibitory, not stimulating.",
      hook: "Growth regulation.",
    },
    {
      id: 10,
      cardType: "Transport",
      title: "Portal system",
      front: "How do hypothalamic hormones reach the anterior pituitary?",
      back: "Through the Hypothalamo-hypophyseal portal system.",
      trap: "NEET Trap: It is a blood pathway.",
      hook: "Direct hormone delivery.",
    },
    {
      id: 11,
      cardType: "Transport",
      title: "Posterior pituitary control",
      front: "How is the posterior pituitary regulated by the hypothalamus?",
      back: "Direct neural regulation.",
      trap: "NEET Trap: Not via portal blood; via axons.",
      hook: "Axonal transport.",
    },
    {
      id: 12,
      cardType: "Location",
      title: "Sella turcica",
      front: "In which bony cavity is the pituitary gland located?",
      back: "Sella turcica.",
      trap: "NEET Trap: Bony cavity in the skull.",
      hook: "Skull landmark.",
    },
    {
      id: 13,
      cardType: "Anatomy",
      title: "Pituitary divisions",
      front: "What are the two main anatomical divisions of the pituitary?",
      back: "Adenohypophysis and Neurohypophysis.",
      trap: "NEET Trap: Functional vs anatomical division.",
      hook: "Anterior & posterior.",
    },
    {
      id: 14,
      cardType: "Anatomy",
      title: "Adenohypophysis parts",
      front: "Name the two parts of the Adenohypophysis.",
      back: "Pars distalis and Pars intermedia.",
      trap: "NEET Trap: Pars tuberalis is minor/ignored in most questions.",
      hook: "Hormone secretion.",
    },
    {
      id: 15,
      cardType: "Hormone",
      title: "Pars distalis hormones",
      front: "List the 6 hormones of the Pars distalis (Anterior Pituitary).",
      back: "GH, PRL, TSH, ACTH, FSH, LH.",
      trap: "NEET Trap: MSH is NOT from pars distalis.",
      hook: "Tropic + direct.",
    },
    {
      id: 16,
      cardType: "Hormone",
      title: "Pars intermedia",
      front: "Which hormone is secreted by the Pars intermedia?",
      back: "Melanocyte Stimulating Hormone (MSH).",
      trap: "NEET Trap: It is the only hormone from this part.",
      hook: "Pigmentation.",
    },
    {
      id: 17,
      cardType: "Hormone",
      title: "Neurohypophysis hormones",
      front: "Which hormones are associated with the Neurohypophysis?",
      back: "Oxytocin and Vasopressin (ADH).",
      trap: "NEET Trap: These are stored only, not synthesized here.",
      hook: "Hypothalamic origin.",
    },
    {
      id: 18,
      cardType: "NEET Trap",
      title: "Oxytocin synthesis",
      front: "True/False: The posterior pituitary synthesises Oxytocin.",
      back: "False.",
      trap: "NEET Trap: It only stores and releases it.",
      hook: "Fundamental line.",
    },
    {
      id: 19,
      cardType: "Disorder",
      title: "Gigantism",
      front: "What does excess GH in childhood lead to?",
      back: "Gigantism.",
      trap: "NEET Trap: Occurs before epiphyseal fusion.",
      hook: "Height increase.",
    },
    {
      id: 20,
      cardType: "Disorder",
      title: "Acromegaly",
      front: "What is the result of excess GH in adults?",
      back: "Acromegaly.",
      trap: "NEET Trap: Severe facial disfigurement.",
      hook: "After bone fusion.",
    },
    {
      id: 21,
      cardType: "Disorder",
      title: "Pituitary dwarfism",
      front: "What is the result of GH deficiency in children?",
      back: "Pituitary dwarfism.",
      trap: "NEET Trap: The body remains proportionate.",
      hook: "Short stature.",
    },
    {
      id: 22,
      cardType: "Hormone",
      title: "TSH function",
      front: "What is the primary function of TSH?",
      back: "Stimulates synthesis and secretion of thyroid hormones.",
      trap: "NEET Trap: Acts on thyroid follicles.",
      hook: "T3/T4 control.",
    },
    {
      id: 23,
      cardType: "Hormone",
      title: "ACTH function",
      front: "What does ACTH stimulate?",
      back: "Adrenal cortex to produce glucocorticoids.",
      trap: "NEET Trap: Does not act on the adrenal medulla.",
      hook: "Stress hormone control.",
    },
    {
      id: 24,
      cardType: "Hormone",
      title: "Gonadotrophins",
      front: "Which two hormones are collectively called Gonadotrophins?",
      back: "LH (Luteinizing Hormone) and FSH (Follicle Stimulating Hormone).",
      trap: "NEET Trap: Both act on gonads.",
      hook: "Reproduction.",
    },
    {
      id: 25,
      cardType: "Male",
      title: "LH in males",
      front: "What is the role of LH in males?",
      back: "Stimulates secretion of androgens.",
      trap: "NEET Trap: Acts on Leydig cells.",
      hook: "Testosterone.",
    },
    {
      id: 26,
      cardType: "Male",
      title: "FSH in males",
      front: "What is the role of FSH in males?",
      back: "Regulates spermatogenesis.",
      trap: "NEET Trap: Requires androgens to function.",
      hook: "Sertoli support.",
    },
    {
      id: 27,
      cardType: "Female",
      title: "LH in females",
      front: "Name two functions of LH in females.",
      back: "Induces ovulation and maintains Corpus Luteum.",
      trap: "NEET Trap: Mid-cycle LH surge.",
      hook: "Progesterone production.",
    },
    {
      id: 28,
      cardType: "Hormone",
      title: "ADH action",
      front: "What is the primary action of Vasopressin (ADH)?",
      back: "Stimulates water reabsorption.",
      trap: "NEET Trap: Acts mainly on distal tubules and collecting ducts.",
      hook: "Osmoregulation.",
    },
    {
      id: 29,
      cardType: "Disorder",
      title: "Diabetes insipidus",
      front: "Which disease results from ADH deficiency?",
      back: "Diabetes insipidus.",
      trap: "NEET Trap: This is NOT the sugar-related diabetes.",
      hook: "Excess urine/dilute urine.",
    },
    {
      id: 30,
      cardType: "Comparison",
      title: "Diabetes types",
      front: "Compare Diabetes Insipidus vs Diabetes Mellitus.",
      back: "Insipidus: ADH deficiency; Mellitus: Insulin deficiency/resistance.",
      trap: "NEET Trap: Don't confuse the two in MCQ options.",
      hook: "Polyuria.",
    },
    {
      id: 31,
      cardType: "Anatomy",
      title: "Thyroid anatomy",
      front: "Describe the anatomy of the thyroid gland.",
      back: "Two lobes connected by an isthmus.",
      trap: "NEET Trap: Located on the trachea.",
      hook: "Butterfly shape.",
    },
    {
      id: 32,
      cardType: "Anatomy",
      title: "Thyroid synthesis site",
      front: "Where are thyroid hormones synthesized?",
      back: "In thyroid follicles by follicular cells.",
      trap: "NEET Trap: They store hormones in the colloid.",
      hook: "Hormone synthesis.",
    },
    {
      id: 33,
      cardType: "Hormone",
      title: "Thyroid hormones",
      front: "Name the two main thyroid hormones.",
      back: "T3 (Triiodothyronine) and T4 (Tetraiodothyronine/Thyroxine).",
      trap: "NEET Trap: They are iodinated amino acids.",
      hook: "Iodothyronines.",
    },
    {
      id: 34,
      cardType: "Disorder",
      title: "Iodine deficiency",
      front: "What happens during iodine deficiency?",
      back: "Hypothyroidism and Goitre (enlargement of thyroid).",
      trap: "NEET Trap: Goitre is a sign of hypothyroidism here.",
      hook: "Enlarged gland.",
    },
    {
      id: 35,
      cardType: "Disorder",
      title: "Cretinism",
      front: "What is Cretinism?",
      back: "Hypothyroidism during pregnancy affecting the baby.",
      trap: "NEET Trap: Causes mental retardation and stunted growth.",
      hook: "Pregnancy effect.",
    },
    {
      id: 36,
      cardType: "Disorder",
      title: "Hyperthyroidism",
      front: "List signs of Hyperthyroidism.",
      back: "Increased BMR, weight loss, rapid heart rate.",
      trap: "NEET Trap: High BMR despite eating.",
      hook: "Weight loss.",
    },
    {
      id: 37,
      cardType: "Disorder",
      title: "Graves' disease",
      front: "What is Graves' disease?",
      back: "Exophthalmic goitre (form of hyperthyroidism).",
      trap: "NEET Trap: Autoimmune disorder with bulging eyes.",
      hook: "Bulging eyes.",
    },
    {
      id: 38,
      cardType: "Hormone",
      title: "Thyrocalcitonin",
      front: "What is the function of Thyrocalcitonin (TCT)?",
      back: "Lowers blood calcium levels.",
      trap: "NEET Trap: Secreted by thyroid, not parathyroid.",
      hook: "Bone deposition.",
    },
    {
      id: 39,
      cardType: "Comparison",
      title: "PTH vs Calcitonin",
      front: "Contrast PTH and Calcitonin actions.",
      back: "PTH: Increases blood Ca²⁺; Calcitonin: Decreases blood Ca²⁺.",
      trap: "NEET Trap: They are antagonistic.",
      hook: "Calcium homeostasis.",
    },
    {
      id: 40,
      cardType: "Location",
      title: "Parathyroid location",
      front: "Where are the parathyroid glands located?",
      back: "On the posterior side of the thyroid gland (4 glands).",
      trap: "NEET Trap: One pair in each lobe of thyroid.",
      hook: "Calcium control.",
    },
    {
      id: 41,
      cardType: "Hormone",
      title: "PTH hypercalcemic",
      front: "Why is PTH called a hypercalcemic hormone?",
      back: "Because it raises blood Ca²⁺ levels.",
      trap: "NEET Trap: It does this by bone resorption (dissolution).",
      hook: "Bone resorption.",
    },
    {
      id: 42,
      cardType: "Control",
      title: "PTH regulation",
      front: "What regulates the secretion of PTH?",
      back: "Circulating levels of calcium ions.",
      trap: "NEET Trap: Not regulated by the pituitary.",
      hook: "Ion dependent feedback.",
    },
    {
      id: 43,
      cardType: "Target",
      title: "PTH target sites",
      front: "Name the three sites of PTH action.",
      back: "Bones, Kidneys, and Small Intestine.",
      trap: "NEET Trap: Multi-organ response to raise Ca²⁺.",
      hook: "Calcium balance.",
    },
    {
      id: 44,
      cardType: "Location",
      title: "Adrenal location",
      front: "Where are the adrenal glands located?",
      back: "On the anterior part of each kidney.",
      trap: "NEET Trap: Paired glands.",
      hook: "Suprarenal.",
    },
    {
      id: 45,
      cardType: "Anatomy",
      title: "Adrenal parts",
      front: "Name the two parts of the adrenal gland.",
      back: "Adrenal Cortex (outer) and Adrenal Medulla (inner).",
      trap: "NEET Trap: They have different embryonic origins.",
      hook: "Dual origin.",
    },
    {
      id: 46,
      cardType: "Hormone",
      title: "Catecholamines",
      front: "Name the catecholamines produced by the adrenal medulla.",
      back: "Adrenaline (Epinephrine) and Noradrenaline (Norepinephrine).",
      trap: "NEET Trap: Known as emergency hormones.",
      hook: "Catecholamines.",
    },
    {
      id: 47,
      cardType: "Effect",
      title: "Fight or Flight",
      front: "What are the effects of the 'Fight or Flight' response?",
      back: "Increased heart rate, blood pressure, and blood glucose.",
      trap: "NEET Trap: Rapid stress response.",
      hook: "Survival.",
    },
    {
      id: 48,
      cardType: "Anatomy",
      title: "Adrenal cortex layers",
      front: "Name the three layers of the adrenal cortex from outer to inner.",
      back: "Zona Glomerulosa, Zona Fasciculata, Zona Reticularis (GFR).",
      trap: "NEET Trap: Order is frequently asked.",
      hook: "Layer order.",
    },
    {
      id: 49,
      cardType: "Hormone",
      title: "Glucocorticoid",
      front: "What is the main Glucocorticoid in humans?",
      back: "Cortisol.",
      trap: "NEET Trap: Primary stress-coping hormone.",
      hook: "Metabolism regulation.",
    },
    {
      id: 50,
      cardType: "Hormone",
      title: "Mineralocorticoid",
      front: "What is the main Mineralocorticoid in humans?",
      back: "Aldosterone.",
      trap: "NEET Trap: Regulates Na⁺ and water retention.",
      hook: "BP control.",
    },
    {
      id: 51,
      cardType: "Disorder",
      title: "Addison's disease",
      front: "What is Addison's disease?",
      back: "Hyposecretion of adrenal cortex hormones.",
      trap: "NEET Trap: Leads to acute weakness and fatigue.",
      hook: "Low cortisol/aldosterone.",
    },
    {
      id: 52,
      cardType: "Gland",
      title: "Composite gland",
      front: "Why is the pancreas called a composite gland?",
      back: "It has both exocrine and endocrine functions.",
      trap: "NEET Trap: Heterocrine gland.",
      hook: "Dual function.",
    },
    {
      id: 53,
      cardType: "Anatomy",
      title: "Islets of Langerhans",
      front: "What represents the endocrine part of the pancreas?",
      back: "Islets of Langerhans.",
      trap: "NEET Trap: Only 1–2% of pancreatic tissue.",
      hook: "Hormone secretion.",
    },
    {
      id: 54,
      cardType: "Cell",
      title: "Alpha cells",
      front: "Which hormone is secreted by Alpha cells?",
      back: "Glucagon.",
      trap: "NEET Trap: It is hyperglycemic (raises blood sugar).",
      hook: "Raises glucose.",
    },
    {
      id: 55,
      cardType: "Cell",
      title: "Beta cells",
      front: "Which hormone is secreted by Beta cells?",
      back: "Insulin.",
      trap: "NEET Trap: It is hypoglycemic (lowers blood sugar).",
      hook: "Lowers glucose.",
    },
    {
      id: 56,
      cardType: "Mechanism",
      title: "Glucagon actions",
      front: "List two actions of Glucagon.",
      back: "Glycogenolysis and Gluconeogenesis.",
      trap: "NEET Trap: Acts primarily on liver cells.",
      hook: "Fasting hormone.",
    },
    {
      id: 57,
      cardType: "Mechanism",
      title: "Insulin action",
      front: "How does insulin lower blood glucose?",
      back: "Enhances cellular glucose uptake by hepatocytes and adipocytes.",
      trap: "NEET Trap: Moves sugar from blood into cells.",
      hook: "Fed state.",
    },
    {
      id: 58,
      cardType: "Disorder",
      title: "Diabetes Mellitus",
      front: "What characterizes Diabetes Mellitus?",
      back: "Prolonged hyperglycemia and glucose in urine (glycosuria).",
      trap: "NEET Trap: Often associated with ketone bodies.",
      hook: "Insulin problem.",
    },
    {
      id: 59,
      cardType: "NEET Trap",
      title: "Glucagon muscle",
      front: "Does Glucagon act on skeletal muscle?",
      back: "No.",
      trap: "NEET Trap: Glucagon acts mainly on the liver.",
      hook: "Crucial line for MCQ.",
    },
    {
      id: 60,
      cardType: "Mechanism",
      title: "Hormone receptors",
      front: "Where do hormones bind on target cells?",
      back: "On specific hormone receptors.",
      trap: "NEET Trap: Receptors are proteins.",
      hook: "Lock-key specificity.",
    },
    {
      id: 61,
      cardType: "Mechanism",
      title: "Peptide hormone action",
      front: "How do water-soluble hormones (peptide) act?",
      back: "Via membrane-bound receptors and second messengers.",
      trap: "NEET Trap: They do not enter the cell.",
      hook: "cAMP, IP₃, Ca²⁺.",
    },
    {
      id: 62,
      cardType: "Mechanism",
      title: "Steroid hormone action",
      front: "How do lipid-soluble hormones (steroids) act?",
      back: "Via intracellular receptors (mostly nuclear).",
      trap: "NEET Trap: They directly regulate gene expression.",
      hook: "Steroids & thyroid hormones.",
    },
    {
      id: 63,
      cardType: "Location",
      title: "Pineal gland",
      front: "Where is the pineal gland located?",
      back: "On the dorsal side of the forebrain.",
      trap: "NEET Trap: Very small gland.",
      hook: "Biological clock.",
    },
    {
      id: 64,
      cardType: "Hormone",
      title: "Melatonin function",
      front: "What is the primary function of Melatonin?",
      back: "Regulates the 24-hour (circadian) rhythm.",
      trap: "NEET Trap: Secreted during darkness.",
      hook: "Sleep-wake cycle.",
    },
    {
      id: 65,
      cardType: "Location",
      title: "Thymus location",
      front: "Where is the thymus located?",
      back: "Between the lungs behind the sternum.",
      trap: "NEET Trap: Located on the ventral side of the aorta.",
      hook: "Immune organ.",
    },
    {
      id: 66,
      cardType: "Hormone",
      title: "Thymosins function",
      front: "What is the role of Thymosins?",
      back: "Differentiation of T-lymphocytes.",
      trap: "NEET Trap: Crucial for cell-mediated immunity.",
      hook: "Immunity.",
    },
    {
      id: 67,
      cardType: "Aging",
      title: "Thymus aging",
      front: "What happens to the thymus with age?",
      back: "It degenerates in old individuals.",
      trap: "NEET Trap: Resulting in decreased immunity.",
      hook: "Aging effect.",
    },
    {
      id: 68,
      cardType: "Gland",
      title: "Testis dual role",
      front: "What is the dual role of the Testis?",
      back: "Primary sex organ and endocrine gland.",
      trap: "NEET Trap: Produces sperm and hormones.",
      hook: "Male gonad.",
    },
    {
      id: 69,
      cardType: "Cell",
      title: "Leydig cells",
      front: "Which cells in the testis produce Testosterone?",
      back: "Leydig cells (Interstitial cells).",
      trap: "NEET Trap: Stimulated by LH.",
      hook: "Androgens.",
    },
    {
      id: 70,
      cardType: "Hormone",
      title: "Androgen effects",
      front: "What are the effects of Androgens?",
      back: "Growth of facial hair, deepening of voice, male sexual behavior.",
      trap: "NEET Trap: Secondary sex characters.",
      hook: "Puberty.",
    },
    {
      id: 71,
      cardType: "Hormone",
      title: "Ovary hormones",
      front: "Name the two steroid hormones produced by the ovary.",
      back: "Estrogen and Progesterone.",
      trap: "NEET Trap: Both are essential for the menstrual cycle.",
      hook: "Female cycle.",
    },
    {
      id: 72,
      cardType: "Hormone",
      title: "Estrogen role",
      front: "What is the primary role of Estrogen?",
      back: "Development of growing ovarian follicles and female traits.",
      trap: "NEET Trap: Peaks during the proliferative phase.",
      hook: "Follicle growth.",
    },
    {
      id: 73,
      cardType: "Hormone",
      title: "Progesterone role",
      front: "What is the primary role of Progesterone?",
      back: "Maintains pregnancy.",
      trap: "NEET Trap: Secreted by the Corpus Luteum.",
      hook: "Secretory phase.",
    },
    {
      id: 74,
      cardType: "Hormone",
      title: "ANF",
      front: "Which heart hormone decreases blood pressure?",
      back: "Atrial Natriuretic Factor (ANF).",
      trap: "NEET Trap: Secreted by atrial walls when BP increases.",
      hook: "Natriuretic (salt-excreting).",
    },
    {
      id: 75,
      cardType: "Hormone",
      title: "Erythropoietin",
      front: "Which hormone stimulates RBC production and where is it from?",
      back: "Erythropoietin from the JGA of the kidney.",
      trap: "NEET Trap: Response to hypoxia.",
      hook: "RBC production.",
    },
    {
      id: 76,
      cardType: "Hormone",
      title: "GI hormones",
      front: "List the 4 major GI hormones.",
      back: "Gastrin, Secretin, CCK, GIP.",
      trap: "NEET Trap: They are local/tissue hormones.",
      hook: "Digestion.",
    },
    {
      id: 77,
      cardType: "Classification",
      title: "Hormone classes",
      front: "What are the three chemical classes of hormones?",
      back: "Peptide/Protein, Steroids, and Amino-acid derivatives.",
      trap: "NEET Trap: Chemistry determines the receptor type.",
      hook: "Exam favourite.",
    },
    {
      id: 78,
      cardType: "Characteristic",
      title: "Steroid solubility",
      front:
        "What is a characteristic of steroid hormones in terms of solubility?",
      back: "Lipid soluble.",
      trap: "NEET Trap: Cross the cell membrane easily.",
      hook: "Slow but lasting action.",
    },
    {
      id: 79,
      cardType: "Characteristic",
      title: "Peptide solubility",
      front:
        "What is a characteristic of peptide hormones in terms of solubility?",
      back: "Water soluble.",
      trap: "NEET Trap: Cannot cross the cell membrane; need receptors.",
      hook: "Fast action.",
    },
    {
      id: 80,
      cardType: "Integration",
      title: "Chemical coordination purpose",
      front: "What is the ultimate purpose of chemical coordination?",
      back: "Integration and homeostasis.",
      trap: "NEET Trap: Slower than nerves but covers all cells.",
      hook: "Hormonal integration.",
    },
    {
      id: 81,
      cardType: "Hormone",
      title: "Prolactin",
      front: "What does Prolactin (PRL) specifically stimulate?",
      back: "Growth of mammary glands and milk production.",
      trap: "NEET Trap: PRL produces milk; Oxytocin ejects milk.",
      hook: "Lactation.",
    },
    {
      id: 82,
      cardType: "Hormone",
      title: "Oxytocin",
      front: "What are the two key functions of Oxytocin?",
      back: "Stimulates uterine contractions during childbirth and milk ejection.",
      trap: "NEET Trap: It ejects milk but does NOT produce it.",
      hook: "Parturition & lactation.",
    },
    {
      id: 83,
      cardType: "Control",
      title: "Feedback regulation",
      front: "What type of feedback do most hormonal systems use?",
      back: "Negative feedback.",
      trap: "NEET Trap: Rising hormone levels suppress further secretion.",
      hook: "Homeostatic control.",
    },
  ],
};
