/**
 * Built-in deck: Discoveries & Key Concepts (NEET Biology)
 * 60 high-yield NCERT cards covering scientists, discoveries, and historical experiments.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const discoveriesKeyConceptsDeck: BuiltinDeck = {
  id: "builtin-discoveries-key-concepts",
  name: "Discoveries & Key Concepts",
  description:
    "60 high-yield NCERT historical facts covering scientists, experiments, and key biological discoveries — with NEET traps and NCERT hooks on every card.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Discovery",
      title: "Cell discovery",
      front: "Who discovered the cell and in which year?",
      back: "Robert Hooke (1665).",
      trap: "He observed dead cork cells (cell walls), not living protoplasm.",
      hook: "Honeycomb-like structures.",
    },
    {
      id: 2,
      cardType: "Discovery",
      title: "First living cell",
      front: "Who was the first to see and describe a live cell?",
      back: "Antonie van Leeuwenhoek.",
      trap: "Often confused with Robert Hooke who saw dead cells.",
      hook: "First living cells.",
    },
    {
      id: 3,
      cardType: "Theory",
      title: "Cell theory",
      front: "Who formulated the Cell Theory and what was its limitation?",
      back: "Schleiden (Botanist) & Schwann (Zoologist).",
      trap: "Their theory did not explain how new cells were formed.",
      hook: "All plants/animals are composed of cells.",
    },
    {
      id: 4,
      cardType: "Concept",
      title: "Omnis cellula e cellula",
      front: "Who gave the concept 'Omnis cellula e cellula'?",
      back: "Rudolf Virchow (1855).",
      trap: "He modified the cell theory, he didn't invent it.",
      hook: "New cells arise from pre-existing cells.",
    },
    {
      id: 5,
      cardType: "Discovery",
      title: "Nucleus discovery",
      front: "Who discovered the Nucleus?",
      back: "Robert Brown (1831).",
      trap: "Don't confuse with Robert Hooke (Cell).",
      hook: "Orchid roots.",
    },
    {
      id: 6,
      cardType: "Concept",
      title: "Protoplasm",
      front: "Who coined the term 'Protoplasm'?",
      back: "Purkinje (1839).",
      trap: "It refers to the living fluid, not just the cytoplasm.",
      hook: "Living substance.",
    },
    {
      id: 7,
      cardType: "Model",
      title: "Fluid Mosaic Model",
      front:
        "Name the current widely accepted model of the plasma membrane and its authors.",
      back: "Fluid Mosaic Model by Singer & Nicolson (1972).",
      trap: "Replaced the older Sandwich (Danielli-Davson) model.",
      hook: "Quasifluid nature of lipids.",
    },
    {
      id: 8,
      cardType: "Discovery",
      title: "Golgi apparatus",
      front: "Who discovered the Golgi apparatus?",
      back: "Camillo Golgi (1898).",
      trap: "In plants, these are often called Dictyosomes.",
      hook: "Reticular structures near nucleus.",
    },
    {
      id: 9,
      cardType: "Discovery",
      title: "Lysosomes",
      front: "Who discovered Lysosomes and what is their common nickname?",
      back: "Christian de Duve; 'Suicidal Bags'.",
      trap: "They contain hydrolytic enzymes active at acidic pH.",
      hook: "Digestive enzymes.",
    },
    {
      id: 10,
      cardType: "Discovery",
      title: "Ribosomes",
      front: "Who discovered Ribosomes and what are they also called?",
      back: "George Palade (1953); 'Palade particles'.",
      trap: "They are non-membrane bound organelles.",
      hook: "Protein factories.",
    },
    {
      id: 11,
      cardType: "Discovery",
      title: "Mitochondria",
      front: "Who first observed Mitochondria?",
      back: "Altmann (called them Bioblasts).",
      trap: "Benda later coined the term 'Mitochondria'.",
      hook: "Powerhouse of the cell.",
    },
    {
      id: 12,
      cardType: "Concept",
      title: "Plastid",
      front: "Who coined the term 'Plastid'?",
      back: "Schimper.",
      trap: "Not all plastids contain chlorophyll (e.g., Leucoplasts).",
      hook: "Found in plant cells/Euglenoids.",
    },
    {
      id: 13,
      cardType: "Structure",
      title: "Chloroplast parts",
      front: "Identify the two main parts of Chloroplast structure.",
      back: "Grana (sites of light reaction) and Stroma (site of dark reaction).",
      trap: "Thylakoids stack to form Grana.",
      hook: "Photosynthesis.",
    },
    {
      id: 14,
      cardType: "Model",
      title: "DNA double helix",
      front: "Who proposed the Double Helix model of DNA?",
      back: "Watson and Crick (1953).",
      trap: "Based on X-ray diffraction data by Maurice Wilkins and Rosalind Franklin.",
      hook: "Complementary base pairing.",
    },
    {
      id: 15,
      cardType: "Experiment",
      title: "Hershey-Chase",
      front:
        "Which experiment unequivocally proved DNA is the genetic material?",
      back: "Hershey and Chase experiment (1952).",
      trap: "Used radioactive S-35 (protein) and P-32 (DNA).",
      hook: "Bacteriophage/Blender experiment.",
    },
    {
      id: 16,
      cardType: "Discovery",
      title: "Transforming Principle",
      front: "Who discovered the 'Transforming Principle'?",
      back: "Frederick Griffith (1928).",
      trap: "He did not know the biochemical nature of the principle.",
      hook: "Streptococcus pneumoniae (S and R strains).",
    },
    {
      id: 17,
      cardType: "Discovery",
      title: "DNA as transformer",
      front:
        "Who determined the biochemical nature of Griffith's transforming principle?",
      back: "Avery, MacLeod, and McCarty.",
      trap: "Their work was not accepted by all biologists initially.",
      hook: "DNA is the transformer.",
    },
    {
      id: 18,
      cardType: "Example",
      title: "RNA as genetic material",
      front: "Name an example where RNA acts as genetic material.",
      back: "Tobacco Mosaic Virus (TMV) / QB Bacteriophage.",
      trap: "Most organisms use DNA; RNA is the exception here.",
      hook: "RNA genome.",
    },
    {
      id: 19,
      cardType: "Concept",
      title: "Central Dogma",
      front: "Who proposed the Central Dogma of molecular biology?",
      back: "Francis Crick.",
      trap: "Flow is DNA → RNA → Protein.",
      hook: "Information flow.",
    },
    {
      id: 20,
      cardType: "Concept",
      title: "Teminism",
      front: "What is 'Teminism'?",
      back: "Reverse Transcription (RNA → DNA).",
      trap: "Discovered by Temin and Baltimore in retroviruses.",
      hook: "Central Dogma exception.",
    },
    {
      id: 21,
      cardType: "Discovery",
      title: "Genetic code",
      front: "Who deciphered the Genetic Code (cracked the codons)?",
      back: "Marshall Nirenberg.",
      trap: "Khorana synthesized the molecules, Nirenberg read them.",
      hook: "Cell-free system.",
    },
    {
      id: 22,
      cardType: "Discovery",
      title: "Khorana contribution",
      front: "What was Har Gobind Khorana's contribution to genetics?",
      back: "Chemical synthesis of RNA with defined combinations of bases.",
      trap: "He synthesized homopolymers and copolymers.",
      hook: "Artificial RNA.",
    },
    {
      id: 23,
      cardType: "Model",
      title: "Operon model",
      front: "Who proposed the Operon model for gene regulation?",
      back: "Jacob (Geneticist) and Monod (Biochemist).",
      trap: "Based on the lac operon in E. coli (Prokaryotes).",
      hook: "Polycistronic genes.",
    },
    {
      id: 24,
      cardType: "Enzyme",
      title: "Transcription enzyme",
      front: "Which enzyme is primarily responsible for Transcription?",
      back: "DNA-dependent RNA polymerase.",
      trap: "It synthesizes RNA, but reads the DNA template.",
      hook: "RNA synthesis.",
    },
    {
      id: 25,
      cardType: "Experiment",
      title: "Meselson-Stahl",
      front: "Who proved the semi-conservative mode of DNA replication?",
      back: "Meselson and Stahl (1958).",
      trap: "Used N-15 (heavy isotope) in E. coli; Taylor used Vicia faba.",
      hook: "Equilibrium density gradient centrifugation.",
    },
    {
      id: 26,
      cardType: "Theory",
      title: "Mutation Theory",
      front: "Who proposed the 'Mutation Theory'?",
      back: "Hugo de Vries.",
      trap: "Based on Oenothera lamarckiana (Evening Primrose).",
      hook: "Saltation (single step large mutation).",
    },
    {
      id: 27,
      cardType: "Theory",
      title: "Natural Selection",
      front: "Who proposed the theory of Natural Selection?",
      back: "Charles Darwin.",
      trap: "Alfred Wallace reached similar conclusions independently.",
      hook: "Branching descent.",
    },
    {
      id: 28,
      cardType: "Theory",
      title: "Lamarck theory",
      front: "What was Lamarck's theory of evolution?",
      back: "Theory of Inheritance of Acquired Characters (Use and Disuse).",
      trap: "Example: Giraffe's neck elongation.",
      hook: "Rejected by modern genetics.",
    },
    {
      id: 29,
      cardType: "Theory",
      title: "Germplasm Theory",
      front: "Who proposed the Germplasm Theory to disprove Lamarck?",
      back: "August Weismann.",
      trap: "Cut tails of mice for 22 generations; didn't inherit short tails.",
      hook: "Soma vs Germ cells.",
    },
    {
      id: 30,
      cardType: "Classification",
      title: "Natural System",
      front:
        "Which scientists gave the most famous Natural System of classification?",
      back: "Bentham and Hooker.",
      trap: "Based on ultrastructure/morphology, NOT evolutionary relationships.",
      hook: "Seeded plants.",
    },
    {
      id: 31,
      cardType: "Classification",
      title: "Five Kingdom",
      front: "Who proposed the Five Kingdom Classification?",
      back: "R.H. Whittaker (1969).",
      trap: "Main criteria: Mode of nutrition and thallus organization.",
      hook: "Phylogenetic basis.",
    },
    {
      id: 32,
      cardType: "Taxonomy",
      title: "Binomial nomenclature",
      front:
        "Who is the 'Father of Taxonomy' and developer of Binomial Nomenclature?",
      back: "Carolus Linnaeus.",
      trap: "Author name is written in abbreviated form after species name (e.g., Linn.).",
      hook: "Systema Naturae.",
    },
    {
      id: 33,
      cardType: "Nomenclature",
      title: "ICBN and ICZN",
      front: "What do ICBN and ICZN stand for?",
      back: "International Code for Botanical Nomenclature / International Code of Zoological Nomenclature.",
      trap: "Rules ensure one name for one organism worldwide.",
      hook: "Nomenclature rules.",
    },
    {
      id: 34,
      cardType: "Discovery",
      title: "Photosynthesis light",
      front:
        "Who showed that light is essential for photosynthesis and O2 evolution?",
      back: "Jan Ingenhousz.",
      trap: "Used aquatic plants (Hydrilla) to show bubbles in light.",
      hook: "Oxygen evolution.",
    },
    {
      id: 35,
      cardType: "Discovery",
      title: "Oxygen discovery",
      front: "Who discovered that plants 'restore' the air (Oxygen discovery)?",
      back: "Joseph Priestley (1770).",
      trap: "Experiment with bell jar, candle, mouse, and mint plant.",
      hook: "Air purification.",
    },
    {
      id: 36,
      cardType: "Location",
      title: "Light reaction site",
      front: "Where does the Light Reaction occur?",
      back: "Thylakoid / Grana membrane.",
      trap: "Products (ATP/NADPH) are used in the stroma.",
      hook: "Photochemical phase.",
    },
    {
      id: 37,
      cardType: "Discovery",
      title: "Calvin cycle",
      front: "Who mapped the pathway of Carbon in the Dark Reaction?",
      back: "Melvin Calvin.",
      trap: "Used C-14 radioactive isotope in Algae.",
      hook: "Calvin Cycle (C3 pathway).",
    },
    {
      id: 38,
      cardType: "Discovery",
      title: "C4 pathway",
      front: "Identify the C4 pathway discovery team.",
      back: "Hatch and Slack.",
      trap: "Occurs in plants with Kranz Anatomy.",
      hook: "PEPcase is primary acceptor.",
    },
    {
      id: 39,
      cardType: "Organism",
      title: "Nitrogen fixation",
      front: "Which bacterium is famous for symbiotic Nitrogen Fixation?",
      back: "Rhizobium.",
      trap: "Leghemoglobin creates anaerobic conditions for Nitrogenase.",
      hook: "Legumes.",
    },
    {
      id: 40,
      cardType: "Theory",
      title: "Cohesion-Tension theory",
      front: "Who proposed the Cohesion-Tension-Transpiration Pull theory?",
      back: "Dixon and Joly.",
      trap: "Explains how water reaches heights over 100m.",
      hook: "Ascent of sap.",
    },
    {
      id: 41,
      cardType: "Criteria",
      title: "Mineral essentiality",
      front: "Who defined the criteria for 'Essentiality' of minerals?",
      back: "Arnon and Stout.",
      trap: "Elements must be irreplaceable and directly involved in metabolism.",
      hook: "Mineral nutrition.",
    },
    {
      id: 42,
      cardType: "Discovery",
      title: "Auxin isolation",
      front: "Who first isolated Auxin and from what?",
      back: "F.W. Went (1928) from Avena (oat) coleoptile tips.",
      trap: "Darwin first observed the bending, but Went isolated it.",
      hook: "Avena curvature test.",
    },
    {
      id: 43,
      cardType: "Discovery",
      title: "Gibberellins discovery",
      front: "Who discovered Gibberellins?",
      back: "E. Kurosawa.",
      trap: "Found in rice seedlings infected with fungus (Bakanae).",
      hook: "Foolish seedling.",
    },
    {
      id: 44,
      cardType: "Discovery",
      title: "Cytokinin discovery",
      front: "Who discovered Cytokinin (Kinetin)?",
      back: "Skoog and Miller.",
      trap: "Discovered from autoclaved herring sperm DNA.",
      hook: "Cell division promoter.",
    },
    {
      id: 45,
      cardType: "Discovery",
      title: "Ethylene confirmation",
      front: "Who confirmed Ethylene is a gaseous hormone?",
      back: "Cousins / Gane.",
      trap: "Ethylene is the only gaseous PGR.",
      hook: "Fruit ripening.",
    },
    {
      id: 46,
      cardType: "Discovery",
      title: "ABA discovery",
      front: "Who discovered ABA (Abscisic Acid)?",
      back: "Addicott / Wareing / Cornforth.",
      trap: "Initially named Inhibitor-B, Abscissin II, and Dormin.",
      hook: "Stress hormone.",
    },
    {
      id: 47,
      cardType: "Discovery",
      title: "Blood circulation",
      front: "Who discovered Blood Circulation?",
      back: "William Harvey.",
      trap: "Disproved the 'good humor' hypothesis of health.",
      hook: "Heart as a pump.",
    },
    {
      id: 48,
      cardType: "Molecule",
      title: "Oxygen carrier",
      front: "What is the primary carrier of Oxygen in humans?",
      back: "Hemoglobin.",
      trap: "One Hb molecule carries 4 molecules of O2.",
      hook: "Iron-containing pigment.",
    },
    {
      id: 49,
      cardType: "Experiment",
      title: "Gastric digestion",
      front:
        "Who is famous for studying gastric digestion using a patient with a stomach hole?",
      back: "William Beaumont.",
      trap: "Proved digestion is chemical, not just mechanical.",
      hook: "Gastric juice.",
    },
    {
      id: 50,
      cardType: "Concept",
      title: "Hormone term",
      front: "Who coined the term 'Hormone'?",
      back: "Starling.",
      trap: "First hormone discovered was Secretin.",
      hook: "Chemical messengers.",
    },
    {
      id: 51,
      cardType: "Discovery",
      title: "Insulin discovery",
      front: "Who discovered Insulin?",
      back: "Banting and Best.",
      trap: "Isolated from the pancreas of dogs.",
      hook: "Diabetes treatment.",
    },
    {
      id: 52,
      cardType: "Discovery",
      title: "Thyroxine isolation",
      front: "Who isolated Thyroxine?",
      back: "Kendall.",
      trap: "It is an iodine-containing hormone.",
      hook: "BMR regulation.",
    },
    {
      id: 53,
      cardType: "Theory",
      title: "Neuron Doctrine",
      front: "Who is the father of the 'Neuron Doctrine'?",
      back: "Santiago Ramón y Cajal.",
      trap: "Neurons are individual units, not a continuous net.",
      hook: "Nervous system unit.",
    },
    {
      id: 54,
      cardType: "Discovery",
      title: "Reflex action",
      front: "Who explained the mechanism of Reflex Action?",
      back: "Marshall Hall.",
      trap: "It is an involuntary response to a stimulus.",
      hook: "Spinal cord/Reflex arc.",
    },
    {
      id: 55,
      cardType: "Discovery",
      title: "Vaccine",
      front: "Who developed the first Vaccine (Smallpox)?",
      back: "Edward Jenner.",
      trap: "Used Cowpox virus to protect against Smallpox.",
      hook: "Father of Immunology.",
    },
    {
      id: 56,
      cardType: "Discovery",
      title: "Antiseptic surgery",
      front: "Who is the 'Father of Antiseptic Surgery'?",
      back: "Joseph Lister.",
      trap: "He used Carbolic Acid (Phenol) to sterilize instruments.",
      hook: "Infection control.",
    },
    {
      id: 57,
      cardType: "Theory",
      title: "Germ theory",
      front: "Who proposed the 'Germ Theory of Disease'?",
      back: "Louis Pasteur.",
      trap: "Disproved spontaneous generation using swan-neck flasks.",
      hook: "Microbes cause disease.",
    },
    {
      id: 58,
      cardType: "Discovery",
      title: "Penicillin",
      front: "Who discovered Penicillin?",
      back: "Alexander Fleming (1928).",
      trap: "It was a chance discovery from Penicillium notatum fungus.",
      hook: "First antibiotic.",
    },
    {
      id: 59,
      cardType: "Discovery",
      title: "Rh factor",
      front: "Who discovered the Rh-factor in blood?",
      back: "Landsteiner and Wiener.",
      trap: "Discovered in Rhesus monkeys.",
      hook: "Erythroblastosis foetalis.",
    },
    {
      id: 60,
      cardType: "Invention",
      title: "PCR invention",
      front: "Who invented the PCR (Polymerase Chain Reaction)?",
      back: "Kary Mullis.",
      trap: "Requires Thermostable DNA polymerase (Taq).",
      hook: "DNA amplification.",
    },
  ],
};
