/**
 * Built-in deck: Endocrine System (NEET Biology, Chapter 22)
 * 120 high-yield NCERT cards with NEET traps and NCERT hooks.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const endocrineDeck: BuiltinDeck = {
  id: "builtin-endocrine-system",
  name: "Endocrine System",
  description:
    "120 high-yield NCERT cards covering glands, hormones, disorders, and signaling mechanisms — with NEET traps and NCERT hooks on every card.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Gland",
      title: "Endocrine glands",
      front:
        "What is the primary structural characteristic of endocrine glands?",
      back: "They are ductless glands.",
      trap: "They do NOT have ducts (unlike exocrine glands).",
      hook: "They secrete hormones directly into the blood.",
    },
    {
      id: 2,
      cardType: "Hormone",
      title: "Hormones",
      front: "Define hormones based on the modern NCERT definition.",
      back: "Non-nutrient chemical messengers produced in trace amounts.",
      trap: "They are NOT nutrients and are NOT produced in large quantities.",
      hook: "They act on distant target organs.",
    },
    {
      id: 3,
      cardType: "Mechanism",
      title: "Classical hormone definition",
      front: "What is the classical definition of a hormone?",
      back: "A chemical secreted into the blood to act on a distant target organ.",
      trap: "In the classical sense, they are NOT for local action.",
      hook: "Classic endocrine signaling.",
    },
    {
      id: 4,
      cardType: "Location",
      title: "Hypothalamus location",
      front: "Where specifically is the hypothalamus located?",
      back: "The basal part of the diencephalon.",
      trap: "It is a region of the forebrain.",
      hook: "Links the nervous and endocrine systems.",
    },
    {
      id: 5,
      cardType: "Control",
      title: "Hypothalamic hormones",
      front: "Which types of hormones are produced by the hypothalamus?",
      back: "Releasing and inhibiting hormones.",
      trap: "They act specifically on the anterior pituitary.",
      hook: "Transported via the portal system.",
    },
    {
      id: 6,
      cardType: "Hormone",
      title: "GnRH",
      front: "What is the function of Gonadotropin Releasing Hormone (GnRH)?",
      back: "Stimulates the pituitary to release gonadotropins.",
      trap: "Acts on the pituitary, not directly on the gonads.",
      hook: "Key controller of reproduction.",
    },
    {
      id: 7,
      cardType: "Hormone",
      title: "Somatostatin",
      front: "What is the role of hypothalamic Somatostatin?",
      back: "Inhibits the release of Growth Hormone (GH) from the pituitary.",
      trap: "Produced in the hypothalamus (also in pancreas).",
      hook: "Growth control mechanism.",
    },
    {
      id: 8,
      cardType: "Transport",
      title: "Hypophyseal portal system",
      front: "How do hypothalamic hormones reach the anterior pituitary?",
      back: "Via the hypophyseal portal system.",
      trap: "It is a blood-link, NOT a neural connection.",
      hook: "Hormone transport system.",
    },
    {
      id: 9,
      cardType: "Transport",
      title: "Posterior pituitary control",
      front: "How is the posterior pituitary regulated by the hypothalamus?",
      back: "Under direct neural regulation.",
      trap: "It does NOT use the portal system.",
      hook: "Stores hypothalamic hormones directly.",
    },
    {
      id: 10,
      cardType: "Location",
      title: "Pituitary location",
      front: "Where is the pituitary gland located?",
      back: "In a bony cavity called Sella tursica.",
      trap: "Attached to the hypothalamus by a stalk.",
      hook: "Often called the Master Gland.",
    },
    {
      id: 11,
      cardType: "Anatomy",
      title: "Adenohypophysis",
      front: "Which two parts comprise the Adenohypophysis?",
      back: "Pars distalis and Pars intermedia.",
      trap: "Refers to the anterior and middle pituitary.",
      hook: "Site of hormone synthesis.",
    },
    {
      id: 12,
      cardType: "Anatomy",
      title: "Neurohypophysis",
      front:
        "What is another name for the Neurohypophysis and what are its contents?",
      back: "Posterior pituitary; stores Oxytocin and ADH.",
      trap: "It only stores and releases; it does NOT synthesize.",
      hook: "Direct neural link.",
    },
    {
      id: 13,
      cardType: "NEET Trap",
      title: "Posterior pituitary trap",
      front: "Does the posterior pituitary synthesize any hormones?",
      back: "No.",
      trap: "It ONLY stores and releases hormones made in the hypothalamus.",
      hook: "NEET Favorite question.",
    },
    {
      id: 14,
      cardType: "Disorder",
      title: "GH excess (child)",
      front:
        "What results from over-secretion of Growth Hormone during childhood?",
      back: "Gigantism.",
      trap: "Occurs before the epiphyseal plates close.",
      hook: "Abnormal tall stature.",
    },
    {
      id: 15,
      cardType: "Disorder",
      title: "GH deficiency",
      front: "What results from low Growth Hormone during childhood?",
      back: "Pituitary dwarfism.",
      trap: "Onset must be in childhood.",
      hook: "Stunted growth with normal proportions.",
    },
    {
      id: 16,
      cardType: "Disorder",
      title: "GH excess (adult)",
      front: "What is Acromegaly?",
      back: "GH excess in adults resulting in facial disfigurement.",
      trap: "Occurs AFTER the epiphyseal closure (no height increase).",
      hook: "Severe disfigurement of hands and face.",
    },
    {
      id: 17,
      cardType: "Hormone",
      title: "TSH",
      front: "What is the function of Thyroid Stimulating Hormone?",
      back: "Stimulates the synthesis and secretion of thyroid hormones.",
      trap: "Produced by the anterior pituitary, not the thyroid.",
      hook: "Controls overall metabolism.",
    },
    {
      id: 18,
      cardType: "Hormone",
      title: "ACTH",
      front: "Which gland and layer does ACTH target?",
      back: "Adrenal cortex.",
      trap: "Stimulates the secretion of glucocorticoids.",
      hook: "Vital for stress response.",
    },
    {
      id: 19,
      cardType: "Male",
      title: "LH (male)",
      front: "What is the role of LH in males?",
      back: "Stimulates Leydig cells to secrete androgens (testosterone).",
      trap: "Note the target: Leydig cells.",
      hook: "Testosterone production.",
    },
    {
      id: 20,
      cardType: "Male",
      title: "FSH (male)",
      front: "What is the role of FSH in males?",
      back: "Regulates spermatogenesis along with androgens.",
      trap: "FSH alone is not sufficient; it needs androgens.",
      hook: "Sperm formation.",
    },
    {
      id: 21,
      cardType: "Female",
      title: "LH (female)",
      front: "Identify two main functions of LH in females.",
      back: "Induces ovulation and maintains the corpus luteum.",
      trap: "The surge of LH is what triggers ovulation.",
      hook: "Triggers the progesterone phase.",
    },
    {
      id: 22,
      cardType: "Hormone",
      title: "ADH (Vasopressin)",
      front: "Where does ADH act in the kidney and what is its effect?",
      back: "Distal tubules and collecting ducts; stimulates water reabsorption.",
      trap: "Specifically targets water, not just salts.",
      hook: "Prevents water loss (Diuresis).",
    },
    {
      id: 23,
      cardType: "Disorder",
      title: "ADH deficiency",
      front: "What disorder is caused by low ADH levels?",
      back: "Diabetes insipidus.",
      trap: "This is NOT an insulin problem; there is no sugar in urine.",
      hook: "Causes excessive urination and thirst.",
    },
    {
      id: 24,
      cardType: "Anatomy",
      title: "Thyroid structure",
      front: "Describe the structure of the thyroid gland.",
      back: "Two lobes connected by a thin flap of tissue called the isthmus.",
      trap: "Located around the trachea.",
      hook: "A follicular gland.",
    },
    {
      id: 25,
      cardType: "Hormone",
      title: "Thyroid hormones",
      front:
        "What are the two main thyroid hormones and what element is required?",
      back: "T3 and T4; Iodine is essential.",
      trap: "Must have iodine to function.",
      hook: "Regulate Basal Metabolic Rate (BMR).",
    },
    {
      id: 26,
      cardType: "Disorder",
      title: "Iodine deficiency",
      front: "What condition results from a lack of iodine in the diet?",
      back: "Goitre (Hypothyroidism).",
      trap: "Enlargement of the thyroid gland.",
      hook: "Common in hilly areas.",
    },
    {
      id: 27,
      cardType: "Disorder",
      title: "Cretinism",
      front: "What is cretinism?",
      back: "Hypothyroidism in infancy leading to stunted growth and mental retardation.",
      trap: "Result of maternal iodine deficiency during pregnancy.",
      hook: "Mental retardation and deaf-mutism.",
    },
    {
      id: 28,
      cardType: "Disorder",
      title: "Hyperthyroidism",
      front: "What are the common symptoms of hyperthyroidism?",
      back: "Increased BMR, weight loss, and rapid heart rate.",
      trap: "Even with increased appetite, weight is lost.",
      hook: "Excessive metabolic activity.",
    },
    {
      id: 29,
      cardType: "Disorder",
      title: "Graves' disease",
      front: "Identify the signature signs of Graves' disease.",
      back: "Exophthalmic goitre (protrusion of eyeballs).",
      trap: "This is a form of hyperthyroidism.",
      hook: "Eyeball protrusion.",
    },
    {
      id: 30,
      cardType: "Hormone",
      title: "Thyrocalcitonin (TCT)",
      front: "What is the function of TCT?",
      back: "Decreases blood Calcium levels.",
      trap: "It opposes the action of Parathyroid Hormone (PTH).",
      hook: "Promotes bone deposition.",
    },
    {
      id: 31,
      cardType: "Anatomy",
      title: "Parathyroid glands",
      front: "Where are the parathyroid glands located?",
      back: "Four glands on the back side of the thyroid lobes.",
      trap: "Two glands per thyroid lobe.",
      hook: "Vital for Ca\u00b2\u207a regulation.",
    },
    {
      id: 32,
      cardType: "Hormone",
      title: "PTH",
      front: "Why is PTH called a hypercalcemic hormone?",
      back: "It increases blood Calcium levels by stimulating bone resorption.",
      trap: "It takes calcium OUT of the bones.",
      hook: "Bone resorption (demineralization).",
    },
    {
      id: 33,
      cardType: "Mechanism",
      title: "PTH kidney action",
      front: "How does PTH affect the kidneys?",
      back: "Increases Ca\u00b2\u207a reabsorption from renal tubules.",
      trap: "Occurs in the renal tubules.",
      hook: "Helps maintain calcium levels.",
    },
    {
      id: 34,
      cardType: "Anatomy",
      title: "Adrenal structure",
      front: "Describe the two parts of the adrenal gland.",
      back: "Adrenal cortex (outer) and Adrenal medulla (inner).",
      trap: "Located at the anterior part of each kidney.",
      hook: "Dual-functioning emergency gland.",
    },
    {
      id: 35,
      cardType: "Hormone",
      title: "Adrenal medulla hormones",
      front: "Name the two hormones secreted by the adrenal medulla.",
      back: "Adrenaline (Epinephrine) and Noradrenaline (Norepinephrine).",
      trap: "Commonly known as Catecholamines.",
      hook: "Fight or Flight hormones.",
    },
    {
      id: 36,
      cardType: "Effect",
      title: "Catecholamine effect",
      front: "What are the physiological effects of Catecholamines?",
      back: "Increased heart rate, BP, and breakdown of glycogen.",
      trap: "They rapidly increase blood glucose.",
      hook: "Emergency response.",
    },
    {
      id: 37,
      cardType: "Anatomy",
      title: "Adrenal cortex zones",
      front: "List the three layers of the adrenal cortex from outer to inner.",
      back: "Zona glomerulosa, Zona fasciculata, and Zona reticularis.",
      trap: "Remember the order: G \u2192 F \u2192 R.",
      hook: "Layered hormone production.",
    },
    {
      id: 38,
      cardType: "Hormone",
      title: "Glucocorticoid",
      front: "Which hormone is the primary glucocorticoid?",
      back: "Cortisol.",
      trap: "Involved in glucose metabolism (gluconeogenesis).",
      hook: "The 'Stress' hormone.",
    },
    {
      id: 39,
      cardType: "Hormone",
      title: "Mineralocorticoid",
      front: "Which hormone is the primary mineralocorticoid?",
      back: "Aldosterone.",
      trap: "Targets Na\u207a retention and K\u207a excretion.",
      hook: "Regulates blood pressure.",
    },
    {
      id: 40,
      cardType: "Disorder",
      title: "Addison's disease",
      front: "What causes Addison's disease?",
      back: "Under-secretion of adrenal cortex hormones.",
      trap: "Leads to acute weakness and fatigue.",
      hook: "Adrenal cortical failure.",
    },
    {
      id: 41,
      cardType: "Gland",
      title: "Pancreas type",
      front: "Why is the pancreas called a composite gland?",
      back: "It has both exocrine and endocrine functions.",
      trap: "98-99% is exocrine; 1-2% is endocrine.",
      hook: "Islets of Langerhans are the endocrine part.",
    },
    {
      id: 42,
      cardType: "Anatomy",
      title: "Islets of Langerhans",
      front: "What percentage of pancreatic tissue is endocrine?",
      back: "Only 1 to 2 percent.",
      trap: "There are about 1-2 million islets in a normal human pancreas.",
      hook: "Endocrine tissue.",
    },
    {
      id: 43,
      cardType: "Cell",
      title: "\u03b1-cells",
      front: "Which hormone is secreted by Alpha-cells?",
      back: "Glucagon.",
      trap: "It is a hyperglycemic hormone (increases blood sugar).",
      hook: "Acts on the liver.",
    },
    {
      id: 44,
      cardType: "Cell",
      title: "\u03b2-cells",
      front: "Which hormone is secreted by Beta-cells?",
      back: "Insulin.",
      trap: "It is a hypoglycemic hormone (decreases blood sugar).",
      hook: "Key for glucose uptake.",
    },
    {
      id: 45,
      cardType: "Mechanism",
      title: "Insulin action",
      front: "How does insulin lower blood glucose levels?",
      back: "Enhances cellular glucose uptake and stimulates glycogenesis.",
      trap: "It moves sugar FROM blood TO cells.",
      hook: "Promotes glycogenesis (glucose to glycogen).",
    },
    {
      id: 46,
      cardType: "Mechanism",
      title: "Glucagon action",
      front: "How does glucagon raise blood glucose levels?",
      back: "Stimulates glycogenolysis in hepatocytes.",
      trap: "It acts primarily on the liver (hepatocytes).",
      hook: "Promotes glycogenolysis (glycogen to glucose).",
    },
    {
      id: 47,
      cardType: "Disorder",
      title: "Diabetes mellitus",
      front: "What are the two hallmarks of Diabetes Mellitus?",
      back: "Hyperglycemia and Glycosuria (glucose in urine).",
      trap: "Result of insulin deficiency or resistance.",
      hook: "Chronic metabolic disorder.",
    },
    {
      id: 48,
      cardType: "Mechanism",
      title: "Hormone receptors",
      front: "What is required for a cell to be a 'target' for a hormone?",
      back: "Specific hormone receptors (proteins).",
      trap: "Hormones only act on cells with the correct receptors.",
      hook: "Specificity of action.",
    },
    {
      id: 49,
      cardType: "Mechanism",
      title: "Membrane receptors",
      front: "Which types of hormones use membrane-bound receptors?",
      back: "Peptide and protein hormones (Water-soluble).",
      trap: "They generate second messengers like cAMP or IP3.",
      hook: "Hormone does not enter the cell.",
    },
    {
      id: 50,
      cardType: "Mechanism",
      title: "Intracellular receptors",
      front: "Which types of hormones use intracellular receptors?",
      back: "Steroid hormones and Iodothyronines.",
      trap: "They regulate gene expression by interacting with DNA.",
      hook: "Direct effect on the genome.",
    },
    {
      id: 51,
      cardType: "Gland",
      title: "Pineal gland",
      front: "Where is the pineal gland located?",
      back: "On the dorsal side of the forebrain.",
      trap: "It is a very small endocrine gland.",
      hook: "Secretes Melatonin.",
    },
    {
      id: 52,
      cardType: "Hormone",
      title: "Melatonin",
      front: "What is the primary role of Melatonin?",
      back: "Regulates the 24-hour diurnal rhythm (sleep-wake cycle).",
      trap: "Considered the body's 'biological clock'.",
      hook: "Diurnal rhythm regulation.",
    },
    {
      id: 53,
      cardType: "Gland",
      title: "Thymus",
      front: "Describe the location and childhood status of the thymus.",
      back: "Behind the sternum; large in children, small in adults.",
      trap: "It is very prominent in children.",
      hook: "Primary role in immunity.",
    },
    {
      id: 54,
      cardType: "Hormone",
      title: "Thymosin",
      front: "What is the function of Thymosin?",
      back: "Promotes differentiation of T-lymphocytes.",
      trap: "Vital for cell-mediated immunity.",
      hook: "Immune system development.",
    },
    {
      id: 55,
      cardType: "Aging",
      title: "Thymus aging",
      front: "Why does immunity decrease in old age?",
      back: "The thymus degenerates, leading to decreased thymosin production.",
      trap: "A natural part of the aging process.",
      hook: "Reduced immune response.",
    },
    {
      id: 56,
      cardType: "Testis",
      title: "Testis endocrine cells",
      front: "Which specific cells in the testis produce hormones?",
      back: "Leydig cells (Interstitial cells).",
      trap: "Located in the interstitial spaces between tubules.",
      hook: "Secrete testosterone.",
    },
    {
      id: 57,
      cardType: "Hormone",
      title: "Testosterone",
      front: "What are the anabolic effects of testosterone?",
      back: "Growth of muscles, facial hair, and bone density.",
      trap: "It also regulates spermatogenesis.",
      hook: "Male secondary characters.",
    },
    {
      id: 58,
      cardType: "Ovary",
      title: "Ovary hormones",
      front: "Name the two steroid hormones produced by the ovary.",
      back: "Estrogen and Progesterone.",
      trap: "They are steroids, not peptides.",
      hook: "Female cycle control.",
    },
    {
      id: 59,
      cardType: "Hormone",
      title: "Estrogen",
      front: "Where is estrogen produced and what is its role?",
      back: "Produced by growing follicles; controls female secondary traits.",
      trap: "High during the pre-ovulatory phase.",
      hook: "Follicle growth and sexual behavior.",
    },
    {
      id: 60,
      cardType: "Hormone",
      title: "Progesterone",
      front: "What is the primary role of progesterone?",
      back: "Supports and maintains pregnancy.",
      trap: "Secreted mainly by the corpus luteum.",
      hook: "Uterine preparation.",
    },
    {
      id: 61,
      cardType: "Hormone",
      title: "Prolactin (PRL)",
      front: "What is the specific role of Prolactin?",
      back: "Stimulates growth of mammary glands and milk formation.",
      trap: "It does NOT cause milk ejection (that is oxytocin).",
      hook: "Milk production.",
    },
    {
      id: 62,
      cardType: "Hormone",
      title: "Oxytocin",
      front: "What is the role of Oxytocin in lactation?",
      back: "Causes milk ejection from mammary glands.",
      trap: "It is the 'milk let-down' hormone.",
      hook: "Smooth muscle contraction.",
    },
    {
      id: 63,
      cardType: "Hormone",
      title: "Oxytocin (childbirth)",
      front: "How does Oxytocin assist in childbirth?",
      back: "Stimulates vigorous uterine contractions.",
      trap: "Operates via a positive feedback loop.",
      hook: "Parturition hormone.",
    },
    {
      id: 64,
      cardType: "Hormone",
      title: "MSH",
      front: "What does MSH act on and what is its effect?",
      back: "Melanocytes; regulates skin pigmentation.",
      trap: "Secreted by the pars intermedia.",
      hook: "Melanocyte stimulating hormone.",
    },
    {
      id: 65,
      cardType: "NEET Trap",
      title: "Pars intermedia (humans)",
      front: "Is the pars intermedia a distinct lobe in humans?",
      back: "No, it is almost merged with the pars distalis.",
      trap: "Exam Trap: It still exists and secretes MSH.",
      hook: "Middle pituitary.",
    },
    {
      id: 66,
      cardType: "Location",
      title: "Pineal gland location",
      front: "Where specifically is the pineal gland found?",
      back: "Dorsal side of the forebrain.",
      trap: "Located between the two cerebral hemispheres.",
      hook: "Smallest endocrine gland.",
    },
    {
      id: 67,
      cardType: "Hormone",
      title: "Melatonin function",
      front: "Identify the rhythm Melatonin controls.",
      back: "24-hour diurnal rhythm (Sleep-wake cycle).",
      trap: "Affects sleep patterns.",
      hook: "The biological clock.",
    },
    {
      id: 68,
      cardType: "Hormone",
      title: "Melatonin additional role",
      front: "What else does Melatonin influence besides sleep?",
      back: "Menstrual cycle, metabolism, and defense capability.",
      trap: "Has a broader regulatory role than just sleep.",
      hook: "Pigmentation and metabolism.",
    },
    {
      id: 69,
      cardType: "Hormone",
      title: "Thyroid hormone function",
      front: "What is the primary role of thyroid hormones (T3/T4)?",
      back: "Regulation of the Basal Metabolic Rate (BMR).",
      trap: "They affect almost all cells in the body.",
      hook: "Energy metabolism.",
    },
    {
      id: 70,
      cardType: "Blood",
      title: "Thyroid & RBCs",
      front: "Does the thyroid gland influence blood production?",
      back: "Yes, it supports the process of RBC formation (erythropoiesis).",
      trap: "It is an indirect but significant effect.",
      hook: "Erythropoiesis support.",
    },
    {
      id: 71,
      cardType: "Disorder",
      title: "Hypothyroidism (adult female)",
      front: "What is a symptom of hypothyroidism in adult females?",
      back: "Irregular menstrual cycles.",
      trap: "Can lead to fertility issues.",
      hook: "Hormonal imbalance.",
    },
    {
      id: 72,
      cardType: "Immunity",
      title: "Thymus function",
      front: "Which specific immune cell matures in the thymus?",
      back: "T-lymphocytes.",
      trap: "Provides 'Cell-Mediated Immunity'.",
      hook: "Immune maturation.",
    },
    {
      id: 73,
      cardType: "Aging",
      title: "Thymus degeneration",
      front: "When does the thymus begin to shrink?",
      back: "With increasing age (puberty onwards).",
      trap: "Reason why old people have weaker immunity.",
      hook: "Decreased thymosin levels.",
    },
    {
      id: 74,
      cardType: "Metabolism",
      title: "Glucocorticoid effect",
      front: "How do glucocorticoids affect blood sugar?",
      back: "They stimulate gluconeogenesis.",
      trap: "They raise blood glucose levels during stress.",
      hook: "Glucose from non-carbohydrates.",
    },
    {
      id: 75,
      cardType: "Immune",
      title: "Cortisol immune role",
      front: "How does Cortisol affect the immune system?",
      back: "Suppresses the immune response.",
      trap: "Useful as an anti-inflammatory drug (prevents organ rejection).",
      hook: "Immunosuppressant.",
    },
    {
      id: 76,
      cardType: "Blood",
      title: "Cortisol RBC role",
      front: "What is Cortisol's role in blood formation?",
      back: "Stimulates the production of Red Blood Cells.",
      trap: "Indirect hematopoietic effect.",
      hook: "RBC stimulation.",
    },
    {
      id: 77,
      cardType: "Control",
      title: "Aldosterone function",
      front: "What ions does Aldosterone balance?",
      back: "Reabsorbs Na\u207a and water; excretes K\u207a and phosphate ions.",
      trap: "Important for maintaining blood volume and BP.",
      hook: "Electrolyte balance.",
    },
    {
      id: 78,
      cardType: "Hormone",
      title: "Adrenal androgen",
      front: "What is the role of adrenal cortex androgens?",
      back: "Development of pubic, axillary, and facial hair during puberty.",
      trap: "Secreted in small amounts.",
      hook: "Secondary sexual traits.",
    },
    {
      id: 79,
      cardType: "Anatomy",
      title: "Testis structure",
      front: "What are the two functional components of the testis?",
      back: "Seminiferous tubules and Interstitial tissue.",
      trap: "Acts as both an exocrine and endocrine organ.",
      hook: "Dual function.",
    },
    {
      id: 80,
      cardType: "Cells",
      title: "Leydig cells",
      front: "Where are Leydig cells found?",
      back: "In the interstitial spaces between seminiferous tubules.",
      trap: "Stimulated by LH (ICSH).",
      hook: "Testosterone source.",
    },
    {
      id: 81,
      cardType: "Traits",
      title: "Testosterone effects",
      front: "List two physical traits caused by testosterone.",
      back: "Deep voice and increased muscle growth.",
      trap: "Promotes anabolic (building) processes.",
      hook: "Male secondary traits.",
    },
    {
      id: 82,
      cardType: "Brain",
      title: "Testosterone CNS role",
      front: "Does testosterone affect the brain?",
      back: "Yes, it influences sexual behavior (libido).",
      trap: "Has a direct neural effect.",
      hook: "Libido control.",
    },
    {
      id: 83,
      cardType: "Ovary",
      title: "Ovary structure",
      front: "What is the basic functional unit of the ovary?",
      back: "Ovarian follicles.",
      trap: "Produces one ovum per cycle in humans.",
      hook: "Cyclic paired organ.",
    },
    {
      id: 84,
      cardType: "Source",
      title: "Estrogen source",
      front: "Which structure in the ovary secretes estrogen?",
      back: "Growing ovarian follicles.",
      trap: "Levels are highest before ovulation.",
      hook: "Follicular hormone.",
    },
    {
      id: 85,
      cardType: "Structure",
      title: "Corpus luteum",
      front: "When and how does the corpus luteum form?",
      back: "After ovulation from the ruptured follicle.",
      trap: "Degenerates if pregnancy doesn't occur.",
      hook: "Secretes progesterone.",
    },
    {
      id: 86,
      cardType: "Function",
      title: "Estrogen function",
      front: "What does estrogen do for the female body?",
      back: "Growth and activity of female secondary sex organs.",
      trap: "Includes breast development and high pitch voice.",
      hook: "Female sexual maturation.",
    },
    {
      id: 87,
      cardType: "Pregnancy",
      title: "Progesterone role",
      front: "Why is progesterone called the 'Pregnancy Hormone'?",
      back: "It maintains the thick uterine lining required for implantation.",
      trap: "Necessary for the duration of pregnancy.",
      hook: "Uterine support.",
    },
    {
      id: 88,
      cardType: "Lactation",
      title: "Progesterone (mammary gland)",
      front: "What is the effect of progesterone on mammary glands?",
      back: "Stimulates formation of alveoli (sac-like structures that store milk).",
      trap: "Prepares the glands for milk storage.",
      hook: "Glandular development.",
    },
    {
      id: 89,
      cardType: "Heart",
      title: "ANF",
      front: "What is ANF and where is it from?",
      back: "Atrial Natriuretic Factor from the heart's atrial wall.",
      trap: "It DECREASES blood pressure via vasodilation.",
      hook: "Opposes the RAAS system.",
    },
    {
      id: 90,
      cardType: "Kidney",
      title: "Erythropoietin",
      front: "Which kidney cells produce Erythropoietin and what is its role?",
      back: "Juxtaglomerular (JG) cells; stimulates RBC formation.",
      trap: "Secreted in response to low oxygen (hypoxia).",
      hook: "RBC production hormone.",
    },
    {
      id: 91,
      cardType: "Gut",
      title: "Gastrin",
      front: "What does Gastrin stimulate in the stomach?",
      back: "Secretion of Hydrochloric acid (HCl) and Pepsinogen.",
      trap: "Acts on the gastric glands.",
      hook: "Starts protein digestion.",
    },
    {
      id: 92,
      cardType: "Gut",
      title: "Secretin",
      front: "What is the role of Secretin?",
      back: "Stimulates the pancreas to secrete water and bicarbonate ions.",
      trap: "Acts on the exocrine pancreas.",
      hook: "Neutralizes stomach acid.",
    },
    {
      id: 93,
      cardType: "Gut",
      title: "CCK",
      front: "What are the two targets of Cholecystokinin (CCK)?",
      back: "Pancreas (for enzymes) and Gall bladder (for bile).",
      trap: "Causes gall bladder contraction.",
      hook: "Fat digestion.",
    },
    {
      id: 94,
      cardType: "Gut",
      title: "GIP",
      front: "What is the role of Gastric Inhibitory Peptide (GIP)?",
      back: "Inhibits gastric secretion and motility.",
      trap: "Slows down the stomach to allow digestion in the intestine.",
      hook: "Regulates digestion pace.",
    },
    {
      id: 95,
      cardType: "Control",
      title: "Neural vs endocrine control",
      front: "How do neural and endocrine systems differ in speed?",
      back: "Neural is fast and short-lived; Endocrine is slow and long-lasting.",
      trap: "They are complementary, not mutually exclusive.",
      hook: "Coordination systems.",
    },
    {
      id: 96,
      cardType: "Classification",
      title: "Hormone classification",
      front: "What are the three main chemical classes of hormones?",
      back: "Peptides, Steroids, and Amino-acid derivatives.",
      trap: "The chemical class determines the mechanism of action.",
      hook: "Chemical basis.",
    },
    {
      id: 97,
      cardType: "Mechanism",
      title: "Peptide hormones",
      front: "How do peptide hormones deliver their message?",
      back: "By binding to membrane-bound receptors and using second messengers.",
      trap: "They CANNOT enter the target cell.",
      hook: "Extracellular signaling.",
    },
    {
      id: 98,
      cardType: "Mechanism",
      title: "Steroid hormones",
      front: "How do steroid hormones function differently from peptides?",
      back: "They enter the cell and bind to intracellular receptors to regulate DNA.",
      trap: "They are lipid-soluble.",
      hook: "Gene regulation.",
    },
    {
      id: 99,
      cardType: "Mechanism",
      title: "Iodothyronines",
      front: "Do T3 and T4 use membrane or intracellular receptors?",
      back: "Intracellular receptors.",
      trap: "Like steroids, they regulate the genome directly.",
      hook: "Metabolic regulation.",
    },
    {
      id: 100,
      cardType: "Response",
      title: "Catecholamine action",
      front: "Identify two immediate sensory effects of Adrenaline.",
      back: "Increased alertness and pupil dilation.",
      trap: "Part of the 'fight or flight' response.",
      hook: "Emergency preparedness.",
    },
    {
      id: 101,
      cardType: "Response",
      title: "Catecholamines",
      front: "What happens to the heart and lungs during an adrenaline surge?",
      back: "Heart rate and rate of respiration both increase.",
      trap: "Prepares the body for intense physical activity.",
      hook: "Rapid physical response.",
    },
    {
      id: 102,
      cardType: "Metabolism",
      title: "Catecholamines metabolism",
      front: "What is the effect of catecholamines on energy stores?",
      back: "Stimulate breakdown of glycogen, lipids, and proteins.",
      trap: "Rapidly increases blood glucose concentration.",
      hook: "Rapid energy mobilization.",
    },
    {
      id: 103,
      cardType: "Balance",
      title: "Glucose homeostasis",
      front: "Which two hormones maintain blood glucose balance?",
      back: "Insulin and Glucagon.",
      trap: "They have opposing (antagonistic) actions.",
      hook: "Homeostasis.",
    },
    {
      id: 104,
      cardType: "Target",
      title: "Insulin target cells",
      front: "What are the two main target cells for insulin?",
      back: "Hepatocytes (liver) and Adipocytes (fat cells).",
      trap: "They store glucose as glycogen or fat.",
      hook: "Glucose storage.",
    },
    {
      id: 105,
      cardType: "Target",
      title: "Glucagon target cells",
      front: "Where does glucagon primarily act?",
      back: "Mainly on hepatocytes (liver cells).",
      trap: "It does NOT act significantly on adipocytes like insulin does.",
      hook: "Glucose release.",
    },
    {
      id: 106,
      cardType: "Disorder",
      title: "Diabetes mellitus (long-term)",
      front: "What are the characteristics of long-term diabetes mellitus?",
      back: "Hyperglycemia, glycosuria, and formation of ketone bodies.",
      trap: "Can be due to insulin deficiency or resistance.",
      hook: "Chronic metabolic failure.",
    },
    {
      id: 107,
      cardType: "Disorder",
      title: "Diabetes insipidus",
      front: "How is Diabetes Insipidus different from Mellitus?",
      back: "Insipidus is due to ADH deficiency; Mellitus is due to Insulin issues.",
      trap: "Insipidus involves dilute urine without sugar.",
      hook: "Water imbalance.",
    },
    {
      id: 108,
      cardType: "Control",
      title: "Portal vs neural regulation",
      front: "Which pituitary lobe is regulated by the portal system?",
      back: "Anterior Pituitary (Adenohypophysis).",
      trap: "Posterior is regulated neurally.",
      hook: "Pituitary control logic.",
    },
    {
      id: 109,
      cardType: "Master",
      title: "Pituitary master gland",
      front: "Why is the pituitary often called the 'Master Gland'?",
      back: "It controls the secretions of most other endocrine glands.",
      trap: "It is itself controlled by the Hypothalamus.",
      hook: "Hierarchical coordination.",
    },
    {
      id: 110,
      cardType: "Thyroid",
      title: "Goitre cause",
      front: "What is the primary dietary cause of Goitre?",
      back: "Deficiency of Iodine.",
      trap: "Causes thyroid enlargement (Hypothyroid).",
      hook: "Thyroid hypertrophy.",
    },
    {
      id: 111,
      cardType: "Calcium",
      title: "Hypercalcemic hormone",
      front: "Identify the hypercalcemic hormone.",
      back: "PTH (Parathyroid Hormone).",
      trap: "It RAISES blood Calcium.",
      hook: "Bone resorption.",
    },
    {
      id: 112,
      cardType: "Calcium",
      title: "Hypocalcemic hormone",
      front: "Identify the hypocalcemic hormone.",
      back: "TCT (Thyrocalcitonin).",
      trap: "It LOWERS blood Calcium.",
      hook: "Opposes PTH.",
    },
    {
      id: 113,
      cardType: "Cortex",
      title: "Zona glomerulosa",
      front: "What does the Zona Glomerulosa secrete?",
      back: "Mineralocorticoids (e.g., Aldosterone).",
      trap: "The outermost layer.",
      hook: "Salt balance.",
    },
    {
      id: 114,
      cardType: "Cortex",
      title: "Zona fasciculata",
      front: "What does the Zona Fasciculata secrete?",
      back: "Glucocorticoids (e.g., Cortisol).",
      trap: "The middle layer.",
      hook: "Glucose balance.",
    },
    {
      id: 115,
      cardType: "Cortex",
      title: "Zona reticularis",
      front: "What does the Zona Reticularis secrete?",
      back: "Androgens (Sex steroids).",
      trap: "The innermost layer.",
      hook: "Sex hormone support.",
    },
    {
      id: 116,
      cardType: "Failure",
      title: "Addison's disease symptoms",
      front: "Identify the main symptom of Addison's disease.",
      back: "Acute weakness and fatigue due to low cortical hormones.",
      trap: "Due to adrenal cortex failure.",
      hook: "Metabolic weakness.",
    },
    {
      id: 117,
      cardType: "Receptor",
      title: "Hormone specificity",
      front: "Why don't hormones affect every cell they touch?",
      back: "Because only target cells have the specific receptors.",
      trap: "It follows a 'lock-and-key' model.",
      hook: "Target cell specificity.",
    },
    {
      id: 118,
      cardType: "Signaling",
      title: "Second messenger",
      front: "Name three common second messengers used by peptide hormones.",
      back: "cAMP, IP3, and Calcium (Ca\u00b2\u207a).",
      trap: "They amplify the signal inside the cell.",
      hook: "Rapid metabolic response.",
    },
    {
      id: 119,
      cardType: "Action",
      title: "Hormone-receptor complex",
      front:
        "What is the ultimate target of a steroid hormone-receptor complex?",
      back: "The genome (DNA) to regulate gene expression.",
      trap: "Leads to new protein synthesis.",
      hook: "Transcriptional control.",
    },
    {
      id: 120,
      cardType: "Integration",
      title: "Overall coordination",
      front: "How is homeostasis maintained in the body?",
      back: "Through the integration of the neural and endocrine systems.",
      trap: "They complement each other's functions.",
      hook: "Body homeostasis.",
    },
  ],
};
