/**
 * Built-in deck: Microbes in Human Welfare (NEET Biology, Unit 8)
 * 130 high-yield NCERT cards with NEET traps and NCERT pro-tips.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const microbesHumanWelfareDeck: BuiltinDeck = {
  id: "builtin-microbes-human-welfare",
  name: "Microbes in Human Welfare",
  description:
    "130 high-yield NCERT cards covering Household, Industrial, Antibiotics, Sewage, Biogas, Biocontrol, and Biofertilisers — with NEET traps and pro-tips.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Introduction",
      title: "Microbes on Earth",
      front: "Microbes are major components of...",
      back: "Biological systems on Earth",
      trap: "They are NOT minor or negligible components.",
      hook: "This is the opening line of the NCERT chapter.",
    },
    {
      id: 2,
      cardType: "Introduction",
      title: "Microbial habitats",
      front: "Habitats where microbes are found",
      back: "Soil, water, air, plants, and animals",
      trap: "They aren't just in 'dirty' places; they are everywhere.",
      hook: "The scientific term for being 'everywhere' is Ubiquitous.",
    },
    {
      id: 3,
      cardType: "Introduction",
      title: "Extreme habitats",
      front: "Extreme habitats where microbes survive",
      back: "Geysers (100°C), deep soil, snow, and highly acidic areas",
      trap: "Standard organisms die here, but Extremophiles thrive.",
      hook: "Thermal vents (geysers) often reach boiling point.",
    },
    {
      id: 4,
      cardType: "Introduction",
      title: "Groups of microbes",
      front: "Groups included under microbes",
      back: "Bacteria, fungi, protozoa, viruses, viroids, and prions",
      trap: "Prions and Viroids are included even though they aren't 'cells'.",
      hook: "NCERT includes both cellular and non-cellular agents here.",
    },
    {
      id: 5,
      cardType: "Introduction",
      title: "What are Prions?",
      front: "What are Prions?",
      back: "Proteinaceous infectious agents",
      trap: "Prions contain NO nucleic acid (DNA/RNA).",
      hook: "High-yield MCQ: They are just misfolded proteins.",
    },
    {
      id: 6,
      cardType: "Introduction",
      title: "Colonies on media",
      front: "What do microbes form on nutritive media?",
      back: "Colonies",
      trap: "Media grows 'colonies', not just individual visible cells.",
      hook: "This allows for macroscopic study of microscopic organisms.",
    },
    {
      id: 7,
      cardType: "Introduction",
      title: "Visibility of colonies",
      front: "Are microbial colonies visible to the naked eye?",
      back: "Yes",
      trap: "Individual cells are invisible, but colonies (millions of cells) are visible.",
      hook: "Seen typically on Petri dishes in labs.",
    },
    {
      id: 8,
      cardType: "Introduction",
      title: "Studying microbes",
      front: "Primary requirement for studying microbes",
      back: "Culturing techniques on nutritive media",
      trap: "Microscopy alone isn't enough for functional study.",
      hook: "Growth-based study is essential for industrial use.",
    },
    {
      id: 9,
      cardType: "Introduction",
      title: "Microbes in the body",
      front: "Nature of microbes inside the human body",
      back: "Both beneficial and harmful",
      trap: "Don't assume all microbes are 'germs' or pathogens.",
      hook: "Think of Gut Flora (beneficial) vs. Pathogens (harmful).",
    },
    {
      id: 10,
      cardType: "Introduction",
      title: "Microbial diversity",
      front: "Level of microbial diversity on Earth",
      back: "Extremely High",
      trap: "It is often underestimated in general science.",
      hook: "They represent a massive portion of Earth's biomass.",
    },
    {
      id: 11,
      cardType: "Household",
      title: "Milk to curd",
      front: "Microbe converting milk to curd",
      back: "Lactobacillus (and others)",
      trap: "It's a group called LAB, not just one species.",
      hook: "Stands for Lactic Acid Bacteria.",
    },
    {
      id: 12,
      cardType: "Household",
      title: "LAB full form",
      front: "What does LAB stand for?",
      back: "Lactic Acid Bacteria",
      trap: "It refers to a functional group, not a taxonomic genus name.",
      hook: "Essential for dairy and probiotics.",
    },
    {
      id: 13,
      cardType: "Household",
      title: "LAB in curd formation",
      front: "LAB's role in curd formation",
      back: "Produces acids that coagulate and partially digest milk proteins.",
      trap: "It does NOT completely digest the protein.",
      hook: "The acid denatures the 'Casein' protein in milk.",
    },
    {
      id: 14,
      cardType: "Household",
      title: "LAB starter",
      front: "Source of LAB for starting curd",
      back: "Inoculum or 'starter' (previous curd)",
      trap: "Milk does not turn to curd 'spontaneously' without bacteria.",
      hook: "The starter contains millions of LAB.",
    },
    {
      id: 15,
      cardType: "Household",
      title: "Nutritional value of curd",
      front: "Nutritional improvement in curd",
      back: "Increased Vitamin B12",
      trap: "NCERT specifically mentions B12, not Vitamin C or D.",
      hook: "Frequent NEET question target.",
    },
    {
      id: 16,
      cardType: "Household",
      title: "LAB in stomach",
      front: "Role of LAB in the human stomach",
      back: "Checks/suppresses disease-causing microbes.",
      trap: "It's not primarily for digesting our food, but for protection.",
      hook: "This is a 'Probiotic' effect.",
    },
    {
      id: 17,
      cardType: "Household",
      title: "Dosa/Idli fermentation",
      front: "Fermentation of Dosa/Idli batter is by...",
      back: "Bacteria",
      trap: "Batter fermentation is Bacteria; Bread is Yeast.",
      hook: "The puffiness comes from CO2 produced by these bacteria.",
    },
    {
      id: 18,
      cardType: "Household",
      title: "Puffed-up dough",
      front: "Cause of 'puffed-up' appearance in dough",
      back: "Production of CO2 gas",
      trap: "It's NOT Oxygen or Nitrogen gas.",
      hook: "Gas bubbles get trapped in the gluten/starch matrix.",
    },
    {
      id: 19,
      cardType: "Household",
      title: "Bread making microbe",
      front: "Microbe used for bread making",
      back: "Saccharomyces cerevisiae (Baker's Yeast)",
      trap: "Make sure to use the scientific name correctly.",
      hook: "Also known as Brewer's Yeast.",
    },
    {
      id: 20,
      cardType: "Household",
      title: "Toddy drink",
      front: "Source and process for 'Toddy' drink",
      back: "Fermenting sap from palms",
      trap: "It's a traditional drink of South India, not North.",
      hook: "A natural fermentation process.",
    },
    {
      id: 21,
      cardType: "Household",
      title: "Swiss Cheese holes",
      front: "Cause of large holes in Swiss Cheese",
      back: "Production of a large amount of CO2",
      trap: "The holes are not for 'breathing' or decoration.",
      hook: "High gas production = Large 'eyes' in cheese.",
    },
    {
      id: 22,
      cardType: "Household",
      title: "Swiss Cheese bacterium",
      front: "Bacterium used in Swiss Cheese",
      back: "Propionibacterium sharmanii",
      trap: "It is a BACTERIUM, not a fungus.",
      hook: "Memory Aid: 'Sharmanii' loves Swiss Cheese.",
    },
    {
      id: 23,
      cardType: "Household",
      title: "Roquefort Cheese",
      front: "How is Roquefort Cheese ripened?",
      back: "By growing specific fungi on them",
      trap: "It's NOT bacteria for Roquefort.",
      hook: "Fungi give it a specific flavor/texture.",
    },
    {
      id: 24,
      cardType: "Household",
      title: "Food fermentation benefit",
      front: "Primary benefit of food fermentation",
      back: "Improved flavor, texture, and nutritional value",
      trap: "It's not just for 'preservation'.",
      hook: "Makes nutrients more bioavailable.",
    },
    {
      id: 25,
      cardType: "Household",
      title: "Fermentation temperature",
      front: "Temperature condition for household fermentation",
      back: "Warm/Ambient temperatures",
      trap: "Refrigeration stops fermentation.",
      hook: "Warmth speeds up microbial metabolism.",
    },
    {
      id: 26,
      cardType: "Household",
      title: "LAB on milk protein",
      front: "Effect of LAB on milk protein",
      back: "Partial digestion",
      trap: "NCERT uses the word 'Partial', not 'Complete'.",
      hook: "Makes curd easier to digest than milk.",
    },
    {
      id: 27,
      cardType: "Household",
      title: "Traditional food microbes",
      front: "Nature of traditional microbes in food",
      back: "Non-pathogenic, safe strains",
      trap: "Pathogens cause spoilage, not useful fermentation.",
      hook: "Centuries of human selection.",
    },
    {
      id: 28,
      cardType: "Household",
      title: "CO2 in food",
      front: "Significance of CO2 in food products",
      back: "Indicates active fermentation",
      trap: "It is usually anaerobic respiration (fermentation).",
      hook: "Gas release creates the 'rise'.",
    },
    {
      id: 29,
      cardType: "Household",
      title: "Fermentation condition",
      front: "Condition under which fermentation occurs",
      back: "Anaerobic (Absence of Oxygen)",
      trap: "Oxygen would lead to aerobic respiration, not fermentation.",
      hook: "Pasteur called it 'Life without air'.",
    },
    {
      id: 30,
      cardType: "Household",
      title: "LAB verdict",
      front: "Final verdict on LAB",
      back: "Beneficial microbes",
      trap: "They are NOT pathogens.",
      hook: "Essential for human gut health.",
    },
    {
      id: 31,
      cardType: "Industrial",
      title: "Fermentors",
      front: "Large vessels for industrial microbial growth",
      back: "Fermentors",
      trap: "Small flasks cannot produce industrial quantities.",
      hook: "Designed for optimal aeration and temp control.",
    },
    {
      id: 32,
      cardType: "Industrial",
      title: "Yeast in alcohol",
      front: "Yeast used in the alcohol industry",
      back: "Saccharomyces cerevisiae (Brewer's Yeast)",
      trap: "It's the same species as Baker's Yeast.",
      hook: "Converts sugars into Ethanol.",
    },
    {
      id: 33,
      cardType: "Industrial",
      title: "Alcohol substrates",
      front: "Substrates for alcohol production",
      back: "Malted cereals and fruit juices",
      trap: "They need sugar/starch sources.",
      hook: "Substrate determines the type of drink.",
    },
    {
      id: 34,
      cardType: "Industrial",
      title: "Alcohol type",
      front: "The alcohol produced by yeast",
      back: "Ethanol",
      trap: "Methanol is toxic and not produced by S. cerevisiae.",
      hook: "Standard drinking alcohol.",
    },
    {
      id: 35,
      cardType: "Industrial",
      title: "Non-distilled drinks",
      front: "Alcoholic drinks produced without distillation",
      back: "Wine and Beer",
      trap: "Major NEET Trap: Wine/Beer are NOT distilled.",
      hook: "Lower alcohol content because of this.",
    },
    {
      id: 36,
      cardType: "Industrial",
      title: "Distilled drinks",
      front: "Alcoholic drinks produced by distillation",
      back: "Whisky, Brandy, and Rum",
      trap: "Distillation happens AFTER fermentation.",
      hook: "Higher alcohol concentration.",
    },
    {
      id: 37,
      cardType: "Antibiotics",
      title: "Definition of Antibiotics",
      front: "Definition of Antibiotics",
      back: "Chemical substances produced by some microbes to kill/retard others.",
      trap: "They are NOT effective against viruses.",
      hook: "Term means 'Against Life' (of pathogens).",
    },
    {
      id: 38,
      cardType: "Antibiotics",
      title: "First antibiotic",
      front: "First antibiotic discovered",
      back: "Penicillin",
      trap: "It was not a synthetic drug.",
      hook: "Extracted from a mold.",
    },
    {
      id: 39,
      cardType: "Antibiotics",
      title: "Fleming's discovery",
      front: "Who discovered Penicillin?",
      back: "Alexander Fleming",
      trap: "It was a 'Chance Discovery' (Serendipity).",
      hook: "Year: 1928.",
    },
    {
      id: 40,
      cardType: "Antibiotics",
      title: "Penicillin source",
      front: "Organism producing Penicillin",
      back: "Penicillium notatum (a fungus)",
      trap: "It is a MOLD/FUNGUS, not a bacterium.",
      hook: "Named after its source.",
    },
    {
      id: 41,
      cardType: "Antibiotics",
      title: "Fleming's bacteria",
      front: "What bacteria was Fleming working on?",
      back: "Staphylococci",
      trap: "Penicillin inhibited Staph, not the other way around.",
      hook: "He saw a 'mold' inhibiting bacterial growth.",
    },
    {
      id: 42,
      cardType: "Antibiotics",
      title: "Chain and Florey",
      front: "Who established Penicillin as a full potential drug?",
      back: "Ernest Chain and Howard Florey",
      trap: "Fleming discovered it, but these two made it usable.",
      hook: "Crucial for treating WWII soldiers.",
    },
    {
      id: 43,
      cardType: "Antibiotics",
      title: "Nobel Prize year",
      front: "When was the Nobel Prize for Penicillin awarded?",
      back: "1945",
      trap: "Awarded to Fleming, Chain, AND Florey.",
      hook: "Post-WWII recognition.",
    },
    {
      id: 44,
      cardType: "Antibiotics",
      title: "Antibiotic uses",
      front: "Antibiotics are used to treat...",
      back: "Bacterial diseases (Plague, Diphtheria, etc.)",
      trap: "Ineffective against Viral diseases like Flu or COVID.",
      hook: "Saves millions from bacterial infections.",
    },
    {
      id: 45,
      cardType: "Chemicals",
      title: "Citric Acid source",
      front: "Source of Citric Acid",
      back: "Aspergillus niger (a fungus)",
      trap: "It's NOT a bacterium.",
      hook: "Memory: A. niger is a 'Sour' fungus.",
    },
    {
      id: 46,
      cardType: "Chemicals",
      title: "Acetic Acid source",
      front: "Source of Acetic Acid",
      back: "Acetobacter aceti (a bacterium)",
      trap: "This is a bacterium, not a fungus.",
      hook: "Used for Vinegar production.",
    },
    {
      id: 47,
      cardType: "Chemicals",
      title: "Butyric Acid source",
      front: "Source of Butyric Acid",
      back: "Clostridium butylicum (a bacterium)",
      trap: "It is an Anaerobic bacterium.",
      hook: "Name sounds like the product.",
    },
    {
      id: 48,
      cardType: "Chemicals",
      title: "Lactic Acid source",
      front: "Source of Lactic Acid",
      back: "Lactobacillus (a bacterium)",
      trap: "Already covered in curd, but vital for industry too.",
      hook: "Simple memory: Lacto = Milk/Lactic.",
    },
    {
      id: 49,
      cardType: "Chemicals",
      title: "Detergent enzymes",
      front: "Enzymes used in detergents",
      back: "Lipases",
      trap: "They remove 'oily' stains specifically.",
      hook: "Lipids = Fats/Oils; Lipase breaks them.",
    },
    {
      id: 50,
      cardType: "Chemicals",
      title: "Juice clarification",
      front: "Enzymes for clarifying bottled juices",
      back: "Pectinases and Proteases",
      trap: "Home-made juices are cloudy because they lack these.",
      hook: "Clears out the pulp fibers.",
    },
    {
      id: 51,
      cardType: "Medical",
      title: "Streptokinase source",
      front: "Source of Streptokinase",
      back: "Streptococcus (a bacterium)",
      trap: "Modified by genetic engineering for medical use.",
      hook: "Named directly after its source.",
    },
    {
      id: 52,
      cardType: "Medical",
      title: "Streptokinase use",
      front: "Medical use of Streptokinase",
      back: "Clot buster (removes blood clots)",
      trap: "Used for patients with Myocardial Infarction (Heart Attack).",
      hook: "Dissolves clots in blood vessels.",
    },
    {
      id: 53,
      cardType: "Medical",
      title: "Cyclosporin A use",
      front: "Use of Cyclosporin A",
      back: "Immunosuppressive agent",
      trap: "Used in organ-transplant patients to prevent rejection.",
      hook: "NOT an antibiotic.",
    },
    {
      id: 54,
      cardType: "Medical",
      title: "Cyclosporin A source",
      front: "Source of Cyclosporin A",
      back: "Trichoderma polysporum (a fungus)",
      trap: "It's a fungus, NOT a bacterium.",
      hook: "High-yield NCERT name.",
    },
    {
      id: 55,
      cardType: "Medical",
      title: "Statins",
      front: "Source and use of Statins",
      back: "Monascus purpureus (yeast); Lowers blood cholesterol",
      trap: "It acts by competitively inhibiting the cholesterol-synthesis enzyme.",
      hook: "Statins = Stop Cholesterol.",
    },
    {
      id: 56,
      cardType: "Sewage",
      title: "Sewage components",
      front: "Primary components of Sewage",
      back: "Human excreta, organic matter, and pathogenic microbes",
      trap: "It is mostly water, but the 'solids' are the problem.",
      hook: "Major source of water pollution.",
    },
    {
      id: 57,
      cardType: "Sewage",
      title: "Why treat sewage?",
      front: "Why can't sewage be released directly?",
      back: "High organic matter and pathogens cause BOD depletion.",
      trap: "It leads to mass fish kills due to lack of Oxygen.",
      hook: "Must be treated in STPs.",
    },
    {
      id: 58,
      cardType: "Sewage",
      title: "STP full form",
      front: "What does STP stand for?",
      back: "Sewage Treatment Plant",
      trap: "Not to be confused with standard temperature/pressure.",
      hook: "The 'Engine' of city waste management.",
    },
    {
      id: 59,
      cardType: "Sewage",
      title: "Primary treatment",
      front: "Nature of Primary Treatment",
      back: "Physical removal of particles",
      trap: "It is NOT biological yet.",
      hook: "Involves filtration and sedimentation.",
    },
    {
      id: 60,
      cardType: "Sewage",
      title: "Removing debris",
      front: "How is floating debris removed?",
      back: "Sequential Filtration",
      trap: "It is the very first step.",
      hook: "Mechanical process.",
    },
    {
      id: 61,
      cardType: "Sewage",
      title: "Removing grit",
      front: "How are grit (soil/pebbles) removed?",
      back: "Sedimentation",
      trap: "Heavy things sink; light things float.",
      hook: "Uses gravity.",
    },
    {
      id: 62,
      cardType: "Sewage",
      title: "Primary Sludge",
      front: "What is Primary Sludge?",
      back: "The solids that settle during primary treatment.",
      trap: "It is NOT the liquid part.",
      hook: "Mainly grit and organic solids.",
    },
    {
      id: 63,
      cardType: "Sewage",
      title: "Primary Effluent",
      front: "What is the Primary Effluent?",
      back: "The supernatant (liquid) after primary sedimentation.",
      trap: "This is what moves to secondary treatment.",
      hook: "Still contains high organic load.",
    },
    {
      id: 64,
      cardType: "Sewage",
      title: "Secondary treatment",
      front: "Nature of Secondary Treatment",
      back: "Biological treatment using microbes",
      trap: "Crucial NEET Point: Secondary = Biological.",
      hook: "Uses the effluent from primary treatment.",
    },
    {
      id: 65,
      cardType: "Sewage",
      title: "Aeration Tanks",
      front: "Purpose of Aeration Tanks",
      back: "Allows vigorous growth of useful aerobic microbes.",
      trap: "Air (Oxygen) must be pumped in constantly.",
      hook: "Encourages 'Flocs' formation.",
    },
    {
      id: 66,
      cardType: "Sewage",
      title: "What are Flocs?",
      front: "What are 'Flocs'?",
      back: "Masses of bacteria associated with fungal filaments",
      trap: "They are NOT algae.",
      hook: "Form a mesh-like structure to consume waste.",
    },
    {
      id: 67,
      cardType: "Sewage",
      title: "Flocs consume",
      front: "What do Flocs consume?",
      back: "Major part of organic matter in effluent",
      trap: "They eat the 'pollution'.",
      hook: "This reduces the BOD.",
    },
    {
      id: 68,
      cardType: "Sewage",
      title: "BOD full form",
      front: "What does BOD stand for?",
      back: "Biochemical Oxygen Demand",
      trap: "NCERT uses 'Biochemical', not 'Biological'.",
      hook: "Measures organic strength of waste.",
    },
    {
      id: 69,
      cardType: "Sewage",
      title: "High BOD meaning",
      front: "What does a high BOD indicate?",
      back: "High polluting potential / High organic matter",
      trap: "BOD and Water Quality are inversely proportional.",
      hook: "High BOD = Very Dirty Water.",
    },
    {
      id: 70,
      cardType: "Sewage",
      title: "BOD definition",
      front: "Definition of BOD",
      back: "Amount of O2 consumed if all organic matter in 1L is oxidized by bacteria.",
      trap: "It's an indirect measure, not a direct count of bacteria.",
      hook: "Standard test for water pollution.",
    },
    {
      id: 71,
      cardType: "Sewage",
      title: "Activated Sludge",
      front: "What is Activated Sludge?",
      back: "The sediment of bacterial 'flocs' after secondary treatment.",
      trap: "Very high-yield term.",
      hook: "It is 'activated' because it's full of hungry microbes.",
    },
    {
      id: 72,
      cardType: "Sewage",
      title: "Inoculum role",
      front: "Role of Inoculum in secondary treatment",
      back: "A small part of activated sludge pumped back to aeration tank.",
      trap: "Don't throw it all away; you need the 'starter'.",
      hook: "Works like curd inoculum.",
    },
    {
      id: 73,
      cardType: "Sewage",
      title: "Sludge destination",
      front: "Where is the bulk of activated sludge pumped?",
      back: "Anaerobic Sludge Digesters",
      trap: "This is where gas is produced.",
      hook: "Final stage of solids handling.",
    },
    {
      id: 74,
      cardType: "Sewage",
      title: "Digester gases",
      front: "Gases produced in Anaerobic Digesters",
      back: "Methane, CO2, and H2S",
      trap: "This mixture forms Biogas.",
      hook: "Inflammable and useful as fuel.",
    },
    {
      id: 75,
      cardType: "Sewage",
      title: "After secondary treatment",
      front: "What happens to effluent after secondary treatment?",
      back: "Released into natural water bodies (rivers/streams).",
      trap: "Only released once BOD is significantly reduced.",
      hook: "Safe for the environment now.",
    },
    {
      id: 76,
      cardType: "Sewage",
      title: "Age of method",
      front: "Age of microbial sewage treatment method",
      back: "More than a century",
      trap: "No man-made technology has replaced it yet.",
      hook: "Natural and efficient.",
    },
    {
      id: 77,
      cardType: "Sewage",
      title: "Best sewage technology",
      front: "Best current technology for sewage",
      back: "Microbial Treatment",
      trap: "Chemical treatment is too expensive/toxic for bulk sewage.",
      hook: "Relies on natural cycles.",
    },
    {
      id: 78,
      cardType: "Sewage",
      title: "Ganga Action Plan",
      front: "Objective of Ganga Action Plan",
      back: "To save the river from pollution by building STPs.",
      trap: "A government initiative to stop raw sewage discharge.",
      hook: "Initiated by Ministry of Environment & Forests.",
    },
    {
      id: 79,
      cardType: "Sewage",
      title: "Yamuna Action Plan",
      front: "Objective of Yamuna Action Plan",
      back: "Same as Ganga: building STPs for the Yamuna river.",
      trap: "Often asked as a pair.",
      hook: "Targets major North Indian rivers.",
    },
    {
      id: 80,
      cardType: "Biogas",
      title: "Biogas component",
      front: "Major component of Biogas",
      back: "Methane (CH4)",
      trap: "It's about 50-70% Methane.",
      hook: "Fuel for cooking/lighting.",
    },
    {
      id: 81,
      cardType: "Biogas",
      title: "Methanogens",
      front: "Name for methane-producing bacteria",
      back: "Methanogens",
      trap: "They are strictly ANAEROBIC.",
      hook: "Grow on cellulosic material.",
    },
    {
      id: 82,
      cardType: "Biogas",
      title: "Methanogen example",
      front: "Specific example of a Methanogen",
      back: "Methanobacterium",
      trap: "Found in anaerobic sludge and cattle rumen.",
      hook: "NCERT specific name.",
    },
    {
      id: 83,
      cardType: "Biogas",
      title: "Methanogens in cattle",
      front: "Where are methanogens found in cattle?",
      back: "Rumen (part of stomach)",
      trap: "NOT in the human stomach.",
      hook: "Helps cows digest grass/cellulose.",
    },
    {
      id: 84,
      cardType: "Biogas",
      title: "Human cellulose digestion",
      front: "Can humans digest cellulose?",
      back: "No",
      trap: "Common 'True/False' question in NEET.",
      hook: "We lack the necessary methanogens/enzymes in our gut.",
    },
    {
      id: 85,
      cardType: "Biogas",
      title: "Gobar Gas",
      front: "Why is cattle dung (Gobar) used for biogas?",
      back: "It is rich in methanogens from the rumen.",
      trap: "The bacteria are already in the poop!",
      hook: "Hence called 'Gobar Gas'.",
    },
    {
      id: 86,
      cardType: "Biogas",
      title: "Spent slurry use",
      front: "Use of spent slurry from biogas plant",
      back: "Used as Fertilizer",
      trap: "It's not waste; it's nutrient-rich.",
      hook: "Perfect circle of recycling.",
    },
    {
      id: 87,
      cardType: "Biogas",
      title: "Biogas developers",
      front: "Institutes that developed biogas tech in India",
      back: "IARI and KVIC",
      trap: "Know the full forms: Indian Agricultural Research Inst. & Khadi and Village Industries Commission.",
      hook: "Indigenously developed.",
    },
    {
      id: 88,
      cardType: "Biocontrol",
      title: "Definition of Biocontrol",
      front: "Definition of Biocontrol",
      back: "Use of biological methods for controlling plant diseases/pests.",
      trap: "It's the opposite of using chemical pesticides.",
      hook: "Uses natural predation.",
    },
    {
      id: 89,
      cardType: "Biocontrol",
      title: "Chemical pesticide problem",
      front: "Problem with chemical pesticides",
      back: "Toxic, harmful to humans, and pollute environment.",
      trap: "They also kill 'useful' insects, not just pests.",
      hook: "Lead to biomagnification.",
    },
    {
      id: 90,
      cardType: "Biocontrol",
      title: "Organic farming basis",
      front: "Basis of Organic Farming",
      back: "Creating a system where pests are kept at manageable levels by predators.",
      trap: "The goal is NOT 'Eradication' of all insects.",
      hook: "Believes in biodiversity/balance.",
    },
    {
      id: 91,
      cardType: "Biocontrol",
      title: "Why not eradicate pests?",
      front: "Why is 'Eradication' of pests undesirable?",
      back: "Beneficial predatory insects would starve without their prey.",
      trap: "NCERT highlights this ecosystem balance.",
      hook: "Keep them, but control them.",
    },
    {
      id: 92,
      cardType: "Biocontrol",
      title: "Ladybird beetle",
      front: "Ladybird beetle controls...",
      back: "Aphids",
      trap: "Common MCQ: Ladybird = Aphids.",
      hook: "Natural predator.",
    },
    {
      id: 93,
      cardType: "Biocontrol",
      title: "Dragonflies control",
      front: "Dragonflies control...",
      back: "Mosquitoes",
      trap: "Helps reduce vector-borne diseases.",
      hook: "Effective in water-logged areas.",
    },
    {
      id: 94,
      cardType: "Biocontrol",
      title: "Bt full form",
      front: "What does 'Bt' stand for?",
      back: "Bacillus thuringiensis",
      trap: "It's a soil bacterium.",
      hook: "The 'T' is lowercase in species name.",
    },
    {
      id: 95,
      cardType: "Biocontrol",
      title: "Bt toxin mechanism",
      front: "How does Bt toxin work?",
      back: "Kills insect larvae by creating pores in their midgut.",
      trap: "Only becomes active in the Alkaline pH of the insect gut.",
      hook: "Selective and safe for others.",
    },
    {
      id: 96,
      cardType: "Biocontrol",
      title: "Bt Cotton",
      front: "What is 'Bt Cotton'?",
      back: "Genetically engineered cotton containing Bt toxin genes.",
      trap: "It doesn't need to be sprayed; the plant is the pesticide.",
      hook: "Major biotech success.",
    },
    {
      id: 97,
      cardType: "Biocontrol",
      title: "Bt cotton resistance",
      front: "What is Bt cotton resistant to?",
      back: "Butterfly caterpillars and other insect pests.",
      trap: "It's NOT resistant to herbicides or viruses.",
      hook: "Pest-resistant crop.",
    },
    {
      id: 98,
      cardType: "Biocontrol",
      title: "Trichoderma",
      front: "What is Trichoderma?",
      back: "A free-living fungus found in the root ecosystem.",
      trap: "It's a FUNGUS, not a bacterium.",
      hook: "Very effective biocontrol for several plant pathogens.",
    },
    {
      id: 99,
      cardType: "Biocontrol",
      title: "Baculoviruses",
      front: "What do Baculoviruses attack?",
      back: "Insects and other arthropods",
      trap: "They are species-specific and narrow spectrum.",
      hook: "Safe for non-target organisms like birds/mammals.",
    },
    {
      id: 100,
      cardType: "Biocontrol",
      title: "Baculovirus genus",
      front: "Genus of Baculoviruses used in biocontrol",
      back: "Nucleopolyhedrovirus",
      trap: "Memorize this long name; it's NCERT direct.",
      hook: "Used in Integrated Pest Management (IPM).",
    },
    {
      id: 101,
      cardType: "Biofertilisers",
      title: "Definition of Biofertilisers",
      front: "Definition of Biofertilisers",
      back: "Organisms that enrich the nutrient quality of the soil.",
      trap: "They are LIVING organisms, unlike chemical NPK.",
      hook: "Eco-friendly and sustainable.",
    },
    {
      id: 102,
      cardType: "Biofertilisers",
      title: "Sources of Biofertilisers",
      front: "Main sources of Biofertilisers",
      back: "Bacteria, Fungi, and Cyanobacteria",
      trap: "Know all three groups.",
      hook: "The 'Trinity' of organic soil health.",
    },
    {
      id: 103,
      cardType: "Biofertilisers",
      title: "Rhizobium",
      front: "Symbiotic N2 fixer in Leguminous plants",
      back: "Rhizobium",
      trap: "Found in root nodules.",
      hook: "Fixes atmospheric N2 into organic forms.",
    },
    {
      id: 104,
      cardType: "Biofertilisers",
      title: "Role of Rhizobium",
      front: "Role of Rhizobium",
      back: "Fixes atmospheric Nitrogen into organic forms for the plant.",
      trap: "It's a Mutualistic relationship.",
      hook: "Plant gives sugar; Bacteria gives Nitrogen.",
    },
    {
      id: 105,
      cardType: "Biofertilisers",
      title: "Free-living N2 fixers",
      front: "Free-living N2 fixers in soil",
      back: "Azospirillum and Azotobacter",
      trap: "They don't need a plant host to fix nitrogen.",
      hook: "Enrich the soil N-content independently.",
    },
    {
      id: 106,
      cardType: "Biofertilisers",
      title: "What is Mycorrhiza?",
      front: "What is Mycorrhiza?",
      back: "Symbiotic association between Fungi and Roots of higher plants.",
      trap: "Fungus = Myco; Root = Rhiza.",
      hook: "Mutualistic benefit.",
    },
    {
      id: 107,
      cardType: "Biofertilisers",
      title: "Mycorrhiza genus",
      front: "Which fungal genus forms Mycorrhiza?",
      back: "Glomus",
      trap: "Specific NCERT genus name.",
      hook: "Forms 'Endomycorrhiza'.",
    },
    {
      id: 108,
      cardType: "Biofertilisers",
      title: "Mycorrhiza nutrient",
      front: "Mycorrhiza helps the plant absorb...",
      back: "Phosphorus",
      trap: "NOT primarily Nitrogen. Major MCQ Trap!",
      hook: "Phosphorus (P) is the key nutrient here.",
    },
    {
      id: 109,
      cardType: "Biofertilisers",
      title: "Mycorrhiza extra benefits",
      front: "Additional benefits of Mycorrhiza",
      back: "Resistance to root pathogens, salinity, and drought.",
      trap: "It does more than just nutrient absorption.",
      hook: "Overall plant growth increases.",
    },
    {
      id: 110,
      cardType: "Biofertilisers",
      title: "What are Cyanobacteria?",
      front: "What are Cyanobacteria?",
      back: "Autotrophic microbes found in aquatic/terrestrial habitats.",
      trap: "Also called Blue Green Algae (BGA).",
      hook: "Many can fix atmospheric Nitrogen.",
    },
    {
      id: 111,
      cardType: "Biofertilisers",
      title: "N2-fixing Cyanobacteria",
      front: "Examples of N2-fixing Cyanobacteria",
      back: "Anabaena, Nostoc, and Oscillatoria",
      trap: "Very common in paddy (rice) fields.",
      hook: "A, N, O.",
    },
    {
      id: 112,
      cardType: "Biofertilisers",
      title: "Cyanobacteria in paddy",
      front: "Role of Cyanobacteria in Paddy fields",
      back: "Serve as important biofertilisers by adding organic matter.",
      trap: "Reduces dependence on Urea/Chemicals.",
      hook: "Vital for Asian agriculture.",
    },
    {
      id: 113,
      cardType: "Biofertilisers",
      title: "Why use Biofertilisers?",
      front: "Why use Biofertilisers?",
      back: "To reduce pressure on chemical fertilisers and prevent pollution.",
      trap: "Sustainable and cheaper in the long run.",
      hook: "Protect soil texture and health.",
    },
    {
      id: 114,
      cardType: "Biofertilisers",
      title: "Biofertilisers backbone",
      front: "Biofertilisers are the backbone of...",
      back: "Organic Farming",
      trap: "Cannot do organic farming with synthetic chemicals.",
      hook: "Natural nutrient cycle.",
    },
    {
      id: 115,
      cardType: "Biofertilisers",
      title: "Over-fertilisation effect",
      front: "Negative effect of chemical over-fertilisation",
      back: "Environmental pollution and loss of soil biodiversity.",
      trap: "Eutrophication of water bodies is a major result.",
      hook: "Chemicals leach into groundwater.",
    },
    {
      id: 116,
      cardType: "Final",
      title: "Probiotics",
      front: "Another name for LAB used as supplements",
      back: "Probiotics",
      trap: "Antibiotics kill; Probiotics help.",
      hook: "Meaning 'For Life'.",
    },
    {
      id: 117,
      cardType: "Final",
      title: "Goal of Probiotics",
      front: "Main goal of Probiotics",
      back: "To maintain/improve 'good' bacteria in the gut.",
      trap: "Doesn't replace antibiotics, but supports health.",
      hook: "Yogurt/Kefir are examples.",
    },
    {
      id: 118,
      cardType: "Final",
      title: "Fermentation biochemistry",
      front: "Core biochemical process of fermentation",
      back: "Sugar -> Alcohol or Organic Acids + CO2",
      trap: "Requires anaerobic environment.",
      hook: "Energy yield is low but useful for microbes.",
    },
    {
      id: 119,
      cardType: "Final",
      title: "Industrial fermentors",
      front: "Requirements for industrial fermentors",
      back: "Strictly controlled temperature, pH, and sterility.",
      trap: "A tiny contamination can ruin thousands of liters.",
      hook: "Precision engineering.",
    },
    {
      id: 120,
      cardType: "Final",
      title: "Antibiotic resistance",
      front: "Why does antibiotic resistance happen?",
      back: "Overuse and misuse (not finishing courses).",
      trap: "Bacteria evolve to survive the drug.",
      hook: "Major global health threat.",
    },
    {
      id: 121,
      cardType: "Final",
      title: "Antibiotics vs viruses",
      front: "Antibiotics are ineffective against...",
      back: "Viruses",
      trap: "Biggest common misconception. Viruses have no cell wall/metabolism to target.",
      hook: "Don't take antibiotics for a cold!",
    },
    {
      id: 122,
      cardType: "Final",
      title: "Secondary treatment target",
      front: "Primary target of secondary treatment",
      back: "Reduction of BOD",
      trap: "It is NOT about removing grit or floating plastic.",
      hook: "Cleaning the organic 'load'.",
    },
    {
      id: 123,
      cardType: "Final",
      title: "Activated sludge microbes",
      front: "Microbes in activated sludge are...",
      back: "Aerobic",
      trap: "They need the O2 from aeration tanks to eat waste.",
      hook: "Unlike methanogens (anaerobic).",
    },
    {
      id: 124,
      cardType: "Final",
      title: "Methanogens classification",
      front: "Biological classification of Methanogens",
      back: "Archaebacteria",
      trap: "They are NOT Eubacteria.",
      hook: "Live in extreme anaerobic environments.",
    },
    {
      id: 125,
      cardType: "Final",
      title: "Biogas environment",
      front: "Biogas production environment",
      back: "Strictly Anaerobic",
      trap: "Oxygen stops methane production.",
      hook: "Digesters must be sealed.",
    },
    {
      id: 126,
      cardType: "Final",
      title: "Biogas pollution-free?",
      front: "Is Biogas completely pollution-free?",
      back: "No, but it is considered 'clean' compared to wood/coal.",
      trap: "It still produces CO2, but it's carbon-neutral.",
      hook: "Efficient use of waste.",
    },
    {
      id: 127,
      cardType: "Final",
      title: "Biocontrol vs chemicals",
      front: "Why prefer biocontrol over chemicals?",
      back: "They are highly specific and don't harm non-targets.",
      trap: "Chemicals are 'broad spectrum' (kill everything).",
      hook: "Safe for the ecosystem.",
    },
    {
      id: 128,
      cardType: "Final",
      title: "Baculovirus safety",
      front: "Safety profile of Baculoviruses",
      back: "Safe for plants, mammals, birds, and fish.",
      trap: "Species-specific to target insects only.",
      hook: "Ideal for IPM.",
    },
    {
      id: 129,
      cardType: "Final",
      title: "Mycorrhiza and water stress",
      front: "Mycorrhiza and Water stress",
      back: "Increases tolerance to drought and salinity.",
      trap: "Doesn't just give nutrients; gives 'strength'.",
      hook: "Helps survival in harsh soils.",
    },
    {
      id: 130,
      cardType: "Final",
      title: "Big picture of Biofertilisers",
      front: "The 'Big Picture' of Biofertilisers",
      back: "Sustainable Agriculture",
      trap: "Not about instant massive yields, but long-term soil health.",
      hook: "Future of eco-friendly farming.",
    },
  ],
};
