/**
 * Built-in deck: Molecular Basis of Inheritance (NEET Biology)
 * High-yield NCERT cards with category filters and NEET tips.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const molecularBasisDeck: BuiltinDeck = {
  id: "builtin-molecular-basis",
  name: "Molecular Basis of Inheritance",
  description:
    "120 high-yield NCERT cards covering DNA structure, replication, transcription, translation, lac operon, HGP, and DNA fingerprinting.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "History",
      title: "Nuclein",
      front:
        "Who identified DNA as an acidic substance in the nucleus in 1869?",
      back: "Friedrich Miescher",
      trap: "He named it 'Nuclein'. Don't confuse him with Griffith or Watson/Crick.",
      hook: "He named it 'Nuclein'.",
    },
    {
      id: 2,
      cardType: "Structure",
      title: "Nucleotide",
      front: "What are the three components of a nucleotide?",
      back: "Nitrogenous base, Pentose sugar, and Phosphate group",
      trap: "Nucleoside = Base + Sugar (No Phosphate).",
      hook: "Remember: Nucleoside has no phosphate.",
    },
    {
      id: 3,
      cardType: "Structure",
      title: "N-glycosidic linkage",
      front: "Which linkage joins a nitrogenous base to the pentose sugar?",
      back: "N-glycosidic linkage",
      trap: "This occurs at the 1' carbon of the sugar.",
      hook: "Glycosidic bond at C-1'.",
    },
    {
      id: 4,
      cardType: "Structure",
      title: "Phosphodiester linkage",
      front: "Which linkage joins two nucleotides in a chain?",
      back: "3'-5' phosphodiester linkage",
      trap: "NEET loves the polarity! It's 3'-5' on the chain, 5'-3' for the strand growth.",
      hook: "Polarity: chain is 3'-5', growth is 5'-3'.",
    },
    {
      id: 5,
      cardType: "Structure",
      title: "Uracil vs Thymine",
      front: "What replaces Thymine in RNA?",
      back: "Uracil",
      trap: "Uracil is 5-methyl uracil's 'unmethylated' version (Thymine is 5-Me Uracil).",
      hook: "Thymine = 5-methyl Uracil.",
    },
    {
      id: 6,
      cardType: "Structure",
      title: "Purines",
      front: "Which nitrogenous bases are Purines?",
      back: "Adenine and Guanine",
      trap: "Pure As Gold (Purine = Adenine, Gold = Guanine).",
      hook: "Purines have a double-ring structure.",
    },
    {
      id: 7,
      cardType: "Structure",
      title: "Pyrimidines",
      front: "Which nitrogenous bases are Pyrimidines?",
      back: "Cytosine, Uracil, and Thymine",
      trap: "CUT the Py (Pyrimidines = Cytosine, Uracil, Thymine).",
      hook: "Pyrimidines have a single-ring structure.",
    },
    {
      id: 8,
      cardType: "Structure",
      title: "2'-OH in RNA",
      front:
        "At which carbon of the ribose sugar is the -OH group present in RNA but absent in DNA?",
      back: "2' carbon",
      trap: "This 2'-OH makes RNA more reactive and less stable than DNA.",
      hook: "2'-OH = RNA instability.",
    },
    {
      id: 9,
      cardType: "Structure",
      title: "Phosphate attachment",
      front: "Where is the phosphate group attached to the nucleoside?",
      back: "5'-OH of the pentose sugar",
      trap: "Attached via a phosphoester linkage.",
      hook: "5'-OH is the phosphate attachment site.",
    },
    {
      id: 10,
      cardType: "History",
      title: "X-ray diffraction",
      front: "Who provided the X-ray diffraction data for DNA structure?",
      back: "Maurice Wilkins and Rosalind Franklin",
      trap: "Watson and Crick used THEIR data to build the model.",
      hook: "Franklin's Photo 51 was key.",
    },
    {
      id: 11,
      cardType: "Structure",
      title: "Helix pitch",
      front: "What is the pitch of the DNA double helix?",
      back: "3.4 nm",
      trap: "Remember: 1 nm = 10^-9 meters or 10 Angstroms.",
      hook: "3.4 nm pitch with 10 bp per turn.",
    },
    {
      id: 12,
      cardType: "Structure",
      title: "Base pairs per turn",
      front:
        "How many base pairs are typically found in one turn of the helix?",
      back: "10 base pairs",
      trap: "This means the distance between base pairs is 0.34 nm.",
      hook: "10 bp per 3.4 nm turn.",
    },
    {
      id: 13,
      cardType: "Structure",
      title: "Chargaff's rule",
      front: "State Chargaff's rule.",
      back: "[A+G] = [T+C] (Purines = Pyrimidines)",
      trap: "Only applicable to double-stranded DNA (dsDNA). Ratio A/T and G/C is 1.",
      hook: "Purines always equal Pyrimidines in dsDNA.",
    },
    {
      id: 14,
      cardType: "Structure",
      title: "G-C H-bonds",
      front: "How many hydrogen bonds are between Guanine and Cytosine?",
      back: "Three (G ≡ C)",
      trap: "More G-C content means a higher melting temperature (Tm) for DNA.",
      hook: "3 H-bonds in G-C, 2 in A-T.",
    },
    {
      id: 15,
      cardType: "Structure",
      title: "DNA backbone",
      front: "What is the backbone of the DNA double helix made of?",
      back: "Sugar and Phosphate",
      trap: "The nitrogenous bases are projected inside.",
      hook: "Bases point inward; backbone is outside.",
    },
    {
      id: 16,
      cardType: "Structure",
      title: "Antiparallel",
      front: "What is the nature of the two strands in a DNA helix?",
      back: "Antiparallel polarity",
      trap: "One strand is 5' → 3', the other is 3' → 5'.",
      hook: "Antiparallel = opposite polarities.",
    },
    {
      id: 17,
      cardType: "Structure",
      title: "Base pair distance",
      front:
        "What is the plane distance between two consecutive base pairs in B-DNA?",
      back: "0.34 nm",
      trap: "Crucial for calculating DNA length if total bp is known.",
      hook: "0.34 nm = 3.4 Å per base pair.",
    },
    {
      id: 18,
      cardType: "Packaging",
      title: "Human DNA length",
      front: "What is the total length of DNA in a human diploid cell?",
      back: "2.2 meters",
      trap: "Calculation: 6.6 x 10^9 bp x 0.34 x 10^-9 m.",
      hook: "2.2 m of DNA fits in a microscopic nucleus.",
    },
    {
      id: 19,
      cardType: "Packaging",
      title: "Histone amino acids",
      front: "Which amino acids are histones rich in?",
      back: "Lysine and Arginine",
      trap: "Both are basic amino acids with positive charges, attracting negative DNA.",
      hook: "Positive histones attract negative DNA.",
    },
    {
      id: 20,
      cardType: "Packaging",
      title: "Histone octamer",
      front: "How many molecules of histone make up a histone octamer?",
      back: "8 molecules (Two each of H2A, H2B, H3, H4)",
      trap: "H1 is NOT part of the octamer; it's the 'linker' histone.",
      hook: "Octamer = 8 histones, H1 is the linker.",
    },
    {
      id: 21,
      cardType: "Packaging",
      title: "Nucleosome bp",
      front: "How many base pairs of DNA are wrapped around one nucleosome?",
      back: "Approx. 200 bp",
      trap: "Standard NCERT value for eukaryotic packaging calculation.",
      hook: "200 bp wrap around 1 nucleosome.",
    },
    {
      id: 22,
      cardType: "Packaging",
      title: "Euchromatin vs Heterochromatin",
      front: "Distinguish between Euchromatin and Heterochromatin.",
      back: "Euchromatin: Loose, Light, Active. Heterochromatin: Dense, Dark, Inactive.",
      trap: "Heterochromatin = 'Halt' (Inactive). Euchromatin = 'Easy' (Active).",
      hook: "Hetero = dense and inactive; Eu = loose and active.",
    },
    {
      id: 23,
      cardType: "Packaging",
      title: "Nucleosomes",
      front: "What are the repeating units of chromatin called?",
      back: "Nucleosomes",
      trap: "Visualized as 'beads-on-string' under an electron microscope.",
      hook: "Beads-on-string = nucleosomes.",
    },
    {
      id: 24,
      cardType: "Packaging",
      title: "NHC proteins",
      front:
        "What kind of proteins are required for higher-level packaging of chromatin?",
      back: "Non-histone Chromosomal (NHC) proteins",
      trap: "Often asked in 'Choose the correct statement' questions.",
      hook: "NHC proteins drive higher-order chromatin packaging.",
    },
    {
      id: 25,
      cardType: "Experiments",
      title: "Griffith experiment",
      front: "What was the 'Transforming Principle' experiment year?",
      back: "1928",
      trap: "Conducted by Frederick Griffith using Streptococcus pneumoniae.",
      hook: "Griffith 1928 — first hint of genetic material.",
    },
    {
      id: 26,
      cardType: "Experiments",
      title: "Virulent strain",
      front: "Which strain of Streptococcus is virulent (has a capsule)?",
      back: "S-strain (Smooth)",
      trap: "S = Smooth = Sugar coat = Survive (Virulent). R = Rough = No coat.",
      hook: "S = Smooth capsule = virulent.",
    },
    {
      id: 27,
      cardType: "Experiments",
      title: "Heat-killed S + live R",
      front:
        "What happened when heat-killed S-strain was mixed with live R-strain?",
      back: "Mice died; live S-strain was recovered",
      trap: "Griffith concluded something 'transformed' the R into S.",
      hook: "Transformation: R becomes S-like.",
    },
    {
      id: 28,
      cardType: "Experiments",
      title: "Avery MacLeod McCarty",
      front:
        "What did Avery, MacLeod, and McCarty use to prove DNA is the transforming factor?",
      back: "Purified enzymes (Proteases, RNases, DNases)",
      trap: "Only DNase inhibited transformation. This was the biochemical proof.",
      hook: "DNase stops transformation → DNA is the agent.",
    },
    {
      id: 29,
      cardType: "Experiments",
      title: "Hershey-Chase isotopes",
      front:
        "Which isotope was used to label DNA in the Hershey-Chase experiment?",
      back: "32P (Radioactive Phosphorus)",
      trap: "Phosphorus is in DNA; Sulfur (35S) is in Protein capsids.",
      hook: "32P for DNA; 35S for protein.",
    },
    {
      id: 30,
      cardType: "Experiments",
      title: "Hershey-Chase proof",
      front:
        "Who provided the 'unequivocal proof' that DNA is genetic material?",
      back: "Alfred Hershey and Martha Chase (1952)",
      trap: "They used Bacteriophages (viruses that infect bacteria).",
      hook: "Blender experiment with T2 phage.",
    },
    {
      id: 31,
      cardType: "Experiments",
      title: "35S labeling",
      front: "Why was 35S used to label proteins in the Blender Experiment?",
      back: "Sulfur is present in proteins (cysteine/methionine) but not in DNA.",
      trap: "Commonly swapped with 32P in tricky questions.",
      hook: "Sulfur = protein marker.",
    },
    {
      id: 32,
      cardType: "Properties",
      title: "DNA vs RNA stability",
      front: "Why is DNA chemically more stable than RNA?",
      back: "Absence of 2'-OH group and presence of Thymine",
      trap: "The 2'-OH in RNA makes it susceptible to hydrolysis.",
      hook: "No 2'-OH + Thymine = DNA stability.",
    },
    {
      id: 33,
      cardType: "Properties",
      title: "Genetic material storage",
      front:
        "Which molecule is preferred for the storage of genetic information?",
      back: "DNA",
      trap: "RNA is preferred for the transmission of genetic information (translation).",
      hook: "DNA stores; RNA transmits.",
    },
    {
      id: 34,
      cardType: "RNA World",
      title: "First genetic material",
      front: "Which was the first genetic material to evolve?",
      back: "RNA",
      trap: "RNA can act as both genetic material and a catalyst (ribozyme).",
      hook: "RNA World hypothesis.",
    },
    {
      id: 35,
      cardType: "RNA World",
      title: "DNA from RNA",
      front: "Why did DNA evolve from RNA?",
      back: "For more stability and better storage",
      trap: "Chemical modifications like deoxygenation and methylation (Thymine) aided this.",
      hook: "DNA evolved from RNA for stability.",
    },
    {
      id: 36,
      cardType: "Replication",
      title: "Meselson-Stahl",
      front: "Who proved semi-conservative replication in E. coli?",
      back: "Meselson and Stahl (1958)",
      trap: "They used 15N (Heavy Nitrogen), NOT a radioactive isotope. It's a density isotope.",
      hook: "15N density gradient = semi-conservative proof.",
    },
    {
      id: 37,
      cardType: "Replication",
      title: "CsCl gradient",
      front:
        "What medium was used to separate DNA based on density in the Meselson-Stahl experiment?",
      back: "Cesium Chloride (CsCl) density gradient",
      trap: "Centrifugation speed and density of CsCl are the key factors.",
      hook: "CsCl separates DNA by density.",
    },
    {
      id: 38,
      cardType: "Replication",
      title: "DNA polymerase",
      front: "Which enzyme is the main catalyst for DNA replication?",
      back: "DNA-dependent DNA Polymerase",
      trap: "It requires a primer to start and works 5' → 3'.",
      hook: "Requires primer; works 5'→3'.",
    },
    {
      id: 39,
      cardType: "Replication",
      title: "Energy source",
      front: "What is the source of energy for DNA polymerization?",
      back: "Deoxyribonucleoside triphosphates (dNTPs)",
      trap: "They act as both substrate and energy provider (dual role).",
      hook: "dNTPs = substrate + energy.",
    },
    {
      id: 40,
      cardType: "Replication",
      title: "Okazaki fragments",
      front: "What are Okazaki fragments?",
      back: "Small DNA pieces synthesized on the lagging strand",
      trap: "Synthesis is discontinuous because polymerase only moves 5' → 3'.",
      hook: "Lagging strand = discontinuous Okazaki fragments.",
    },
    {
      id: 41,
      cardType: "Replication",
      title: "DNA Ligase",
      front: "Which enzyme joins Okazaki fragments?",
      back: "DNA Ligase",
      trap: "Creates the final phosphodiester bond. Essential for the lagging strand.",
      hook: "Ligase seals the nicks.",
    },
    {
      id: 42,
      cardType: "Replication",
      title: "Taylor experiment",
      front: "Who proved semi-conservative replication in plants (Vicia faba)?",
      back: "Taylor and colleagues",
      trap: "They used radioactive thymidine, unlike Meselson-Stahl who used heavy N.",
      hook: "Taylor used radioactive thymidine in plants.",
    },
    {
      id: 43,
      cardType: "Replication",
      title: "S-phase",
      front: "In which phase of the cell cycle does DNA replication occur?",
      back: "S-phase (Synthesis phase)",
      trap: "A failure in cell division after DNA replication results in polyploidy.",
      hook: "S-phase = DNA synthesis.",
    },
    {
      id: 44,
      cardType: "Replication",
      title: "DNA Helicase",
      front: "What is the function of DNA Helicase?",
      back: "Unwinding the DNA double helix",
      trap: "Creates the replication fork.",
      hook: "Helicase unwinds → replication fork.",
    },
    {
      id: 45,
      cardType: "Replication",
      title: "Primase",
      front: "Which enzyme synthesizes the RNA primer?",
      back: "Primase",
      trap: "Required because DNA polymerase cannot initiate synthesis.",
      hook: "Primase makes the RNA primer.",
    },
    {
      id: 46,
      cardType: "Transcription",
      title: "Coding strand",
      front: "What defines the 'coding strand' in a transcription unit?",
      back: "The strand with 5' → 3' polarity (identical to mRNA sequence except T/U)",
      trap: "RNA Polymerase actually reads the 'Template' strand (3' → 5').",
      hook: "Coding strand ≈ mRNA sequence (T→U).",
    },
    {
      id: 47,
      cardType: "Transcription",
      title: "Promoter reference",
      front:
        "What is the reference point for defining the promoter and terminator?",
      back: "The Coding Strand",
      trap: "Promoter is at 5' end of coding strand; Terminator is at 3' end.",
      hook: "Coding strand defines upstream/downstream.",
    },
    {
      id: 48,
      cardType: "Transcription",
      title: "Sigma factor",
      front: "What is the function of the Sigma (σ) factor?",
      back: "Initiation of transcription in prokaryotes",
      trap: "Enables RNA polymerase to recognize and bind to the promoter.",
      hook: "Sigma = start signal for transcription.",
    },
    {
      id: 49,
      cardType: "Transcription",
      title: "Rho factor",
      front: "What is the function of the Rho (ρ) factor?",
      back: "Termination of transcription in prokaryotes",
      trap: "Helps the nascent RNA and polymerase fall off the DNA.",
      hook: "Rho = stop signal for transcription.",
    },
    {
      id: 50,
      cardType: "Transcription",
      title: "Splicing",
      front: "What is splicing?",
      back: "Removal of Introns and joining of Exons",
      trap: "Introns = Intervening (non-coding). Exons = Expressed (coding).",
      hook: "Splicing: cut introns, join exons.",
    },
    {
      id: 51,
      cardType: "Transcription",
      title: "Capping",
      front: "What is added during 'Capping' of hnRNA?",
      back: "Methyl guanosine triphosphate (at 5' end)",
      trap: "Occurs during eukaryotic transcription processing.",
      hook: "5' cap = methyl guanosine triphosphate.",
    },
    {
      id: 52,
      cardType: "Transcription",
      title: "Tailing",
      front: "What is 'Tailing' in mRNA processing?",
      back: "Poly-A tail (200-300 adenylate residues) added to 3' end",
      trap: "Done in a template-independent manner.",
      hook: "3' poly-A tail added without template.",
    },
    {
      id: 53,
      cardType: "Transcription",
      title: "RNA Pol I",
      front: "Which RNA polymerase transcribes rRNAs (28S, 18S, 5.8S)?",
      back: "RNA Polymerase I",
      trap: "Found in the nucleolus.",
      hook: "RNA Pol I → rRNA (nucleolus).",
    },
    {
      id: 54,
      cardType: "Transcription",
      title: "RNA Pol III",
      front: "Which RNA polymerase transcribes tRNA, 5S rRNA, and snRNAs?",
      back: "RNA Polymerase III",
      trap: "Think: 3 categories (tRNA, 5S, snRNA).",
      hook: "RNA Pol III → tRNA, 5S, snRNA.",
    },
    {
      id: 55,
      cardType: "Transcription",
      title: "RNA Pol II",
      front: "Which RNA polymerase transcribes hnRNA (pre-mRNA)?",
      back: "RNA Polymerase II",
      trap: "The most important one for protein-coding genes.",
      hook: "RNA Pol II → mRNA.",
    },
    {
      id: 56,
      cardType: "Code",
      title: "Gamow triplet",
      front:
        "Who proposed the triplet code based on 4 bases and 20 amino acids?",
      back: "George Gamow",
      trap: "A physicist who mathematically deduced the code length.",
      hook: "Gamow: mathematician-turned-biologist.",
    },
    {
      id: 57,
      cardType: "Code",
      title: "AUG dual function",
      front: "What is the dual function of AUG codon?",
      back: "Initiator codon AND codes for Methionine",
      trap: "AUG is always the start signal for translation.",
      hook: "AUG = start + Methionine.",
    },
    {
      id: 58,
      cardType: "Code",
      title: "Stop codons",
      front: "Which codons are 'Stop Codons'?",
      back: "UAA, UAG, UGA",
      trap: "UAA (Ochre), UAG (Amber), UGA (Opal). They don't code for amino acids.",
      hook: "UAA=Ochre, UAG=Amber, UGA=Opal.",
    },
    {
      id: 59,
      cardType: "Code",
      title: "Degeneracy",
      front: "What does 'Degeneracy' of genetic code mean?",
      back: "One amino acid can be coded by more than one codon",
      trap: "E.g., Valine is coded by GUA, GUG, GUC, GUU.",
      hook: "Multiple codons → same amino acid.",
    },
    {
      id: 60,
      cardType: "Translation",
      title: "Aminoacyl-tRNA synthetase",
      front: "Which enzyme catalyzes the charging of tRNA?",
      back: "Aminoacyl-tRNA synthetase",
      trap: "Also known as aminoacylation. Requires ATP.",
      hook: "Charging tRNA requires ATP.",
    },
    {
      id: 61,
      cardType: "Translation",
      title: "Ribozyme in bacteria",
      front:
        "What is the 'Ribozyme' in bacteria responsible for peptide bond formation?",
      back: "23S rRNA",
      trap: "Shows that ribosomes are essentially ribozymes.",
      hook: "23S rRNA catalyzes peptide bonds.",
    },
    {
      id: 62,
      cardType: "Translation",
      title: "Translation direction",
      front: "What is the direction of translation along the mRNA?",
      back: "5' → 3'",
      trap: "Matches the direction of mRNA synthesis.",
      hook: "Translation reads mRNA 5'→3'.",
    },
    {
      id: 63,
      cardType: "Translation",
      title: "P-site",
      front: "What is the P-site in a ribosome?",
      back: "Peptidyl site (where the growing chain is held)",
      trap: "Initiator tRNA binds directly to the P-site.",
      hook: "P-site = Peptidyl (growing chain).",
    },
    {
      id: 64,
      cardType: "Translation",
      title: "UTRs",
      front: "What are UTRs (Untranslated Regions)?",
      back: "Sequences on mRNA not translated, but required for efficient translation",
      trap: "Present before start codon and after stop codon.",
      hook: "UTRs regulate translation efficiency.",
    },
    {
      id: 65,
      cardType: "Regulation",
      title: "Lac operon structural genes",
      front: "What are the structural genes of the Lac Operon?",
      back: "z, y, and a",
      trap: "z=Beta-gal, y=Permease, a=Transacetylase.",
      hook: "z, y, a encode 3 enzymes for lactose metabolism.",
    },
    {
      id: 66,
      cardType: "Regulation",
      title: "y gene",
      front: "What is the function of the 'y' gene in Lac Operon?",
      back: "Codes for Permease",
      trap: "Increases cell permeability to Beta-galactosides.",
      hook: "Permease lets lactose into the cell.",
    },
    {
      id: 67,
      cardType: "Regulation",
      title: "Lac operon inducer",
      front: "What acts as the 'inducer' in the Lac Operon?",
      back: "Lactose (or Allolactose)",
      trap: "Inactivates the repressor by binding to it.",
      hook: "Lactose induces its own metabolism.",
    },
    {
      id: 68,
      cardType: "Regulation",
      title: "Negative regulation",
      front: "Is Lac Operon regulation usually positive or negative?",
      back: "Negative regulation",
      trap: "Because the default state is 'off' due to a repressor.",
      hook: "Default is OFF — repressor blocks transcription.",
    },
    {
      id: 69,
      cardType: "Regulation",
      title: "i gene",
      front: "What does the 'i' gene stand for in the Lac Operon?",
      back: "Inhibitor gene (not Inducer!)",
      trap: "It codes for the repressor protein constitutively.",
      hook: "i = Inhibitor, always expressed.",
    },
    {
      id: 70,
      cardType: "HGP",
      title: "HGP duration",
      front: "What was the duration of the Human Genome Project?",
      back: "1990 - 2003 (13 years)",
      trap: "It was a 'Mega Project' involving multiple countries.",
      hook: "13-year international collaboration.",
    },
    {
      id: 71,
      cardType: "HGP",
      title: "ESTs",
      front:
        "What is the term for identifying all genes expressed as RNA in HGP?",
      back: "ESTs (Expressed Sequence Tags)",
      trap: "Focuses only on the coding part of the genome.",
      hook: "ESTs = expressed/coding genome regions.",
    },
    {
      id: 72,
      cardType: "HGP",
      title: "Protein-coding percentage",
      front: "What percentage of the human genome codes for proteins?",
      back: "Less than 2%",
      trap: "A surprising finding of the HGP.",
      hook: "Only <2% of human DNA codes for proteins.",
    },
    {
      id: 73,
      cardType: "HGP",
      title: "Gene-richest chromosome",
      front: "Which chromosome has the most genes?",
      back: "Chromosome 1 (2968 genes)",
      trap: "The sequence of Chromosome 1 was completed last (May 2006).",
      hook: "Chr 1 = most genes, sequenced last.",
    },
    {
      id: 74,
      cardType: "HGP",
      title: "SNPs",
      front: "What are SNPs (Snips)?",
      back: "Single Nucleotide Polymorphisms",
      trap: "Found at 1.4 million locations in humans. Useful for disease mapping.",
      hook: "SNPs map human variation and disease.",
    },
    {
      id: 75,
      cardType: "Fingerprinting",
      title: "Basis of fingerprinting",
      front: "What is the basis of DNA Fingerprinting?",
      back: "Polymorphism in repetitive DNA (VNTR)",
      trap: "VNTRs are a type of mini-satellite DNA.",
      hook: "VNTR variation = unique DNA fingerprint.",
    },
    {
      id: 76,
      cardType: "Fingerprinting",
      title: "Developer",
      front: "Who developed the technique of DNA Fingerprinting?",
      back: "Alec Jeffreys",
      trap: "He used a satellite DNA as a probe that shows high polymorphism.",
      hook: "Alec Jeffreys — inventor of DNA fingerprinting.",
    },
    {
      id: 77,
      cardType: "Fingerprinting",
      title: "Steps",
      front: "What are the steps of DNA Fingerprinting?",
      back: "Isolation → Digestion → Electrophoresis → Blotting → Hybridization → Autoradiography",
      trap: "Southern Blotting is the specific blotting technique used.",
      hook: "6 steps; Southern Blotting is key.",
    },
    {
      id: 78,
      cardType: "Fingerprinting",
      title: "VNTR size",
      front: "What is the size range of VNTR?",
      back: "0.1 to 20 kb",
      trap: "The number of repeats varies from person to person.",
      hook: "VNTR repeat number varies per individual.",
    },
    {
      id: 79,
      cardType: "Fingerprinting",
      title: "Probe",
      front: "What is a 'Probe' in DNA Fingerprinting?",
      back: "A radiolabeled VNTR sequence",
      trap: "Used to hybridize with the DNA on the membrane.",
      hook: "Probe hybridizes to VNTR bands.",
    },
    {
      id: 80,
      cardType: "Structure",
      title: "A-T H-bonds",
      front: "Number of H-bonds between A and T?",
      back: "2",
      trap: "Compared to 3 in G-C.",
      hook: "A-T has 2 H-bonds; G-C has 3.",
    },
    {
      id: 81,
      cardType: "Structure",
      title: "Base pair distance (Å)",
      front: "Distance between two base pairs in Angstroms?",
      back: "3.4 Å",
      trap: "0.34 nm = 3.4 Angstroms.",
      hook: "3.4 Å = 0.34 nm between base pairs.",
    },
    {
      id: 82,
      cardType: "Structure",
      title: "Sugar orientation",
      front: "Orientation of sugar in the two strands?",
      back: "Opposite (5'-3' and 3'-5')",
      trap: "Creates the anti-parallel nature.",
      hook: "Opposite sugar orientation = antiparallel.",
    },
    {
      id: 83,
      cardType: "History",
      title: "Levene",
      front: "Constituent of DNA discovered by Levene?",
      back: "Nucleotide components (Phosphate, Sugar, Base)",
      trap: "Levene identified the chemical structure unit.",
      hook: "Levene defined the nucleotide building block.",
    },
    {
      id: 84,
      cardType: "Structure",
      title: "Helix handedness",
      front: "Is the DNA helix right-handed or left-handed?",
      back: "Right-handed",
      trap: "B-DNA is right-handed.",
      hook: "B-DNA = right-handed helix.",
    },
    {
      id: 85,
      cardType: "Structure",
      title: "Helix diameter",
      front: "Diameter of the DNA helix?",
      back: "2 nm (20 Å)",
      trap: "Constant due to purine-pyrimidine pairing.",
      hook: "Constant 2 nm diameter in B-DNA.",
    },
    {
      id: 86,
      cardType: "Packaging",
      title: "H1 histone",
      front: "Which histone is not part of the nucleosome core?",
      back: "H1 histone",
      trap: "It acts as a linker between nucleosomes.",
      hook: "H1 = linker, not in octamer.",
    },
    {
      id: 87,
      cardType: "Packaging",
      title: "Histone charge",
      front: "Charge on Histones?",
      back: "Positive",
      trap: "Due to basic amino acids.",
      hook: "Positive histones bind negative DNA.",
    },
    {
      id: 88,
      cardType: "Packaging",
      title: "DNA charge",
      front: "Charge on DNA?",
      back: "Negative",
      trap: "Due to the phosphate group.",
      hook: "Phosphates make DNA negatively charged.",
    },
    {
      id: 89,
      cardType: "Replication",
      title: "E. coli genome",
      front: "Total number of nucleotides in E. coli?",
      back: "4.6 x 10^6 bp",
      trap: "Often compared with human genome size.",
      hook: "E. coli genome: 4.6 million bp.",
    },
    {
      id: 90,
      cardType: "Replication",
      title: "Polymerization rate",
      front: "Rate of polymerization in E. coli?",
      back: "2000 bp per second",
      trap: "Incredible speed and accuracy.",
      hook: "E. coli replicates at 2000 bp/sec.",
    },
    {
      id: 91,
      cardType: "Replication",
      title: "Origin of replication",
      front: "Term for DNA replication requiring an origin?",
      back: "Ori (Origin of Replication)",
      trap: "Vectors in biotech must have an 'ori'.",
      hook: "Ori = replication start point.",
    },
    {
      id: 92,
      cardType: "Transcription",
      title: "RNA Pol initiation",
      front: "Can RNA polymerase initiate transcription without help?",
      back: "No, it needs Sigma factor in prokaryotes",
      trap: "For initiation specifically.",
      hook: "Sigma factor needed for initiation.",
    },
    {
      id: 93,
      cardType: "Translation",
      title: "tRNA function",
      front: "Type of RNA that carries amino acids?",
      back: "tRNA (Transfer RNA)",
      trap: "Also called soluble RNA (sRNA).",
      hook: "tRNA = adaptor molecule for amino acids.",
    },
    {
      id: 94,
      cardType: "Translation",
      title: "rRNA function",
      front: "Type of RNA that forms the structural part of ribosomes?",
      back: "rRNA (Ribosomal RNA)",
      trap: "Most abundant type of RNA.",
      hook: "rRNA = most abundant RNA type.",
    },
    {
      id: 95,
      cardType: "Transcription",
      title: "snRNA function",
      front: "Function of snRNAs?",
      back: "Splicing of hnRNA",
      trap: "Part of the spliceosome complex.",
      hook: "snRNAs form the spliceosome.",
    },
    {
      id: 96,
      cardType: "HGP",
      title: "Dystrophin gene",
      front: "Largest known human gene?",
      back: "Dystrophin (2.4 million bases)",
      trap: "Located on the X chromosome.",
      hook: "Dystrophin — largest gene on X chromosome.",
    },
    {
      id: 97,
      cardType: "HGP",
      title: "Human genome size",
      front: "Total number of bases in human genome?",
      back: "3.1647 billion (3.3 x 10^9 roughly)",
      trap: "Memorize 3164.7 for accurate MCQs.",
      hook: "~3.2 billion base pairs in human genome.",
    },
    {
      id: 98,
      cardType: "HGP",
      title: "Average gene size",
      front: "Average gene size in humans?",
      back: "3000 bases",
      trap: "Size varies greatly; some are huge, some small.",
      hook: "Average gene = 3000 bases.",
    },
    {
      id: 99,
      cardType: "HGP",
      title: "Sequence annotation",
      front: "What is 'Sequence Annotation' in HGP?",
      back: "Sequencing the whole genome (coding and non-coding)",
      trap: "Then assigning functions to regions.",
      hook: "Sequence then annotate = function mapping.",
    },
    {
      id: 100,
      cardType: "Fingerprinting",
      title: "Satellite DNA",
      front: "What is 'Satellite DNA'?",
      back: "Repetitive DNA that forms small peaks in density gradient",
      trap: "Classified into mini and micro satellites.",
      hook: "Satellite DNA = repetitive sequences.",
    },
    {
      id: 101,
      cardType: "Fingerprinting",
      title: "Mini vs Micro satellites",
      front: "Main difference between Micro and Mini satellites?",
      back: "Length of the repeat unit and total length",
      trap: "Mini-satellites (VNTR) are used for fingerprinting.",
      hook: "Mini-satellites (VNTRs) used for fingerprinting.",
    },
    {
      id: 102,
      cardType: "Fingerprinting",
      title: "Fingerprint consistency",
      front: "Does every cell of an individual have the same DNA fingerprint?",
      back: "Yes",
      trap: "Except for monozygotic (identical) twins.",
      hook: "Same fingerprint in all cells (except twins).",
    },
    {
      id: 103,
      cardType: "Code",
      title: "Severo Ochoa",
      front: "Who synthesized RNA in a template-independent manner?",
      back: "Severo Ochoa (Polynucleotide phosphorylase)",
      trap: "Essential for deciphering the genetic code.",
      hook: "Ochoa's enzyme helped crack the genetic code.",
    },
    {
      id: 104,
      cardType: "Code",
      title: "Single-codon amino acids",
      front: "Amino acid with only one codon?",
      back: "Methionine (AUG) and Tryptophan (UGG)",
      trap: "Most others are degenerate.",
      hook: "Met and Trp each have only 1 codon.",
    },
    {
      id: 105,
      cardType: "Translation",
      title: "Wobble hypothesis",
      front: "Wobble hypothesis was given by?",
      back: "Francis Crick",
      trap: "Explains why 61 tRNAs are not needed for 61 codons.",
      hook: "Wobble = fewer tRNAs needed than codons.",
    },
    {
      id: 106,
      cardType: "Translation",
      title: "Translation energy",
      front: "Is translation an endergonic or exergonic process?",
      back: "Endergonic (Requires ATP/GTP)",
      trap: "Charging and translocation both require energy.",
      hook: "Translation requires energy input (ATP/GTP).",
    },
    {
      id: 107,
      cardType: "Regulation",
      title: "Eukaryotic regulation",
      front: "Primary level of gene regulation in eukaryotes?",
      back: "Transcriptional level",
      trap: "Regulation happens at multiple levels, but this is primary.",
      hook: "Transcription is the primary control point.",
    },
    {
      id: 108,
      cardType: "Translation",
      title: "Peptide bond site",
      front: "Site of ribosome where peptide bond is formed?",
      back: "Between P and A sites",
      trap: "The chain is transferred to the A-site tRNA.",
      hook: "P-A site junction = peptide bond formation.",
    },
    {
      id: 109,
      cardType: "Structure",
      title: "ATP sugar",
      front: "Which sugar is found in ATP?",
      back: "Ribose",
      trap: "ATP is a ribonucleotide.",
      hook: "ATP = ribonucleotide (ribose sugar).",
    },
    {
      id: 110,
      cardType: "Code",
      title: "Coding codons",
      front: "How many codons code for amino acids?",
      back: "61",
      trap: "Total 64, minus 3 stop codons.",
      hook: "61 sense codons + 3 stop = 64 total.",
    },
    {
      id: 111,
      cardType: "Regulation",
      title: "Operon structure",
      front: "What is the structural unit of an Operon?",
      back: "Promoter + Operator + Structural Genes",
      trap: "Regulation happens as a single coordinated unit.",
      hook: "Operon = promoter + operator + genes.",
    },
    {
      id: 112,
      cardType: "Regulation",
      title: "Lac operon promoter",
      front:
        "How many promoters does the lac operon have for structural genes?",
      back: "One single promoter",
      trap: "This is why the resulting mRNA is polycistronic.",
      hook: "One promoter → polycistronic mRNA.",
    },
    {
      id: 113,
      cardType: "Regulation",
      title: "z gene reaction",
      front: "What specific reaction does the 'z' gene catalyze?",
      back: "Hydrolysis of Lactose into Glucose and Galactose",
      trap: "Beta-galactosidase is the primary metabolic enzyme.",
      hook: "z gene = Beta-galactosidase = lactose hydrolysis.",
    },
    {
      id: 114,
      cardType: "Regulation",
      title: "Leaky expression",
      front:
        "Why is a low level of lac operon expression always required in the cell?",
      back: "To allow Permease to be present so lactose can enter the cell",
      trap: "Known as the 'leaky' nature of the operon.",
      hook: "Leaky expression ensures lactose entry.",
    },
    {
      id: 115,
      cardType: "Regulation",
      title: "Actual inducer",
      front: "What molecule is the 'actual' inducer that binds the repressor?",
      back: "Allolactose",
      trap: "Beta-gal converts some lactose to allolactose which then acts as the inducer.",
      hook: "Allolactose (not lactose) binds the repressor.",
    },
    {
      id: 116,
      cardType: "Regulation",
      title: "Glucose + Lactose",
      front:
        "In the presence of both Glucose and Lactose, which will the bacteria use first?",
      back: "Glucose",
      trap: "The lac operon remains inactive until glucose is depleted.",
      hook: "Glucose is preferred over lactose.",
    },
    {
      id: 117,
      cardType: "Regulation",
      title: "Polycistronic mRNA",
      front: "Transcription of the lac operon leads to what kind of mRNA?",
      back: "Polycistronic mRNA",
      trap: "One mRNA contains info for three different proteins (z, y, a).",
      hook: "Polycistronic = one mRNA, multiple proteins.",
    },
    {
      id: 118,
      cardType: "Translation",
      title: "A-site function",
      front: "What is the function of the A-site in the ribosome?",
      back: "Acceptor site for incoming charged tRNA",
      trap: "The P-site holds the growing chain.",
      hook: "A-site accepts new charged tRNA.",
    },
    {
      id: 119,
      cardType: "Fingerprinting",
      title: "Polymorphism threshold",
      front: "What is the frequency threshold for DNA polymorphism?",
      back: "Greater than 0.01 at a locus",
      trap: "If frequency is lower, it's just a mutation, not polymorphism.",
      hook: ">1% frequency = polymorphism, not mutation.",
    },
    {
      id: 120,
      cardType: "Experiments",
      title: "Hershey-Chase organism",
      front: "Which organism was used by Hershey and Chase?",
      back: "Bacteriophage T2 and E. coli",
      trap: "Specific phage name is T2.",
      hook: "T2 phage + E. coli = Hershey-Chase experiment.",
    },
  ],
};
