/**
 * Built-in deck: Morphology of Flowering Plants (NEET Biology)
 * 40 high-yield NCERT cards covering roots, stems, leaves, flowers, fruits, and seeds.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const morphologyFloweringPlantsDeck: BuiltinDeck = {
  id: "builtin-morphology-flowering-plants",
  name: "Morphology of Flowering Plants",
  description:
    "40 high-yield NCERT cards on roots, stems, leaves, inflorescence, flowers, fruits, and seeds.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Roots",
      title: "Taproot example",
      front: "Example of a Taproot system?",
      back: "Mustard",
      trap: "Taproot = main root from radicle. Seen in most dicots.",
      hook: "Mustard is the classic NCERT taproot example.",
    },
    {
      id: 2,
      cardType: "Roots",
      title: "Fibrous root example",
      front: "Example of a Fibrous root system?",
      back: "Wheat",
      trap: "Fibrous roots arise from the base of the stem, not the radicle.",
      hook: "Wheat — fibrous root system in monocots.",
    },
    {
      id: 3,
      cardType: "Roots",
      title: "Adventitious roots",
      front: "Plants with Adventitious roots?",
      back: "Grass, Banyan tree, Monstera, Sugarcane",
      trap: "Adventitious roots arise from any part other than the radicle.",
      hook: "Adventitious = from non-root parts.",
    },
    {
      id: 4,
      cardType: "Roots",
      title: "Storage adventitious root",
      front: "Example of an Adventitious root modified for storage?",
      back: "Sweet potato",
      trap: "Carrot and radish are modified taproots, not adventitious.",
      hook: "Sweet potato = modified adventitious storage root.",
    },
    {
      id: 5,
      cardType: "Roots",
      title: "Pneumatophores",
      front: "Roots for respiration (Pneumatophores) are found in?",
      back: "Rhizophora",
      trap: "Found in mangrove swamps. Grow upward (negatively geotropic).",
      hook: "Rhizophora — pneumatophores for gas exchange.",
    },
    {
      id: 6,
      cardType: "Roots",
      title: "Prop vs Stilt roots",
      front: "Prop roots vs. Stilt roots examples?",
      back: "Prop: Banyan; Stilt: Sugarcane, Maize",
      trap: "Prop roots hang from branches; Stilt roots arise from lower nodes.",
      hook: "Prop = Banyan; Stilt = Sugarcane/Maize.",
    },
    {
      id: 7,
      cardType: "Stem",
      title: "Underground stems",
      front: "Five examples of underground stems for storage/perennation?",
      back: "Potato, Ginger, Turmeric, Zaminkand, Colocasia",
      trap: "These are stems (have nodes/internodes/buds), not roots.",
      hook: "PGTZC — Potato, Ginger, Turmeric, Zaminkand, Colocasia.",
    },
    {
      id: 8,
      cardType: "Stem",
      title: "Stem tendrils",
      front: "Stem tendrils are found in which gourds?",
      back: "Cucumber, Pumpkin, Watermelon",
      trap: "Pea tendrils are leaf tendrils, not stem tendrils.",
      hook: "Gourds use stem tendrils to climb.",
    },
    {
      id: 9,
      cardType: "Stem",
      title: "Thorns",
      front: "Thorns (modified axillary buds) examples?",
      back: "Citrus (Lemon/Orange), Bougainvillea",
      trap: "Spines are modified leaves (Cactus); Thorns are modified stems.",
      hook: "Bougainvillea thorns = modified axillary buds.",
    },
    {
      id: 10,
      cardType: "Stem",
      title: "Photosynthetic stems",
      front: "Flattened vs. Cylindrical photosynthetic stems?",
      back: "Flattened: Opuntia; Cylindrical: Euphorbia",
      trap: "Cladodes/Phylloclade are flattened, fleshy stems.",
      hook: "Opuntia = flat cladode; Euphorbia = cylindrical.",
    },
    {
      id: 11,
      cardType: "Leaf",
      title: "Pulvinus",
      front: "The swollen leaf base in legumes is called?",
      back: "Pulvinus",
      trap: "Responsible for nyctinastic (sleep) movements in some legumes.",
      hook: "Pulvinus = swollen leaf base in legumes.",
    },
    {
      id: 12,
      cardType: "Leaf",
      title: "Reticulate venation",
      front: "Reticulate venation is characteristic of...?",
      back: "Dicots",
      trap: "Exception: Smilax (monocot) has reticulate venation.",
      hook: "Reticulate = net-like = dicots.",
    },
    {
      id: 13,
      cardType: "Leaf",
      title: "Parallel venation",
      front: "Parallel venation is characteristic of...?",
      back: "Monocots",
      trap: "Exception: Calophyllum (dicot) has parallel venation.",
      hook: "Parallel = parallel rows = monocots.",
    },
    {
      id: 14,
      cardType: "Leaf",
      title: "Pinnate compound leaf",
      front: "Example of Pinnately compound leaf?",
      back: "Neem (has a rachis)",
      trap: "Rachis is the extended midrib. Pinnate = feather-like arrangement.",
      hook: "Neem — pinnately compound with rachis.",
    },
    {
      id: 15,
      cardType: "Leaf",
      title: "Palmate compound leaf",
      front: "Example of Palmately compound leaf?",
      back: "Silk cotton",
      trap: "Leaflets arise from a common point (tip of petiole).",
      hook: "Silk cotton — palmate like a hand.",
    },
    {
      id: 16,
      cardType: "Leaf",
      title: "Alternate phyllotaxy",
      front: "Alternate phyllotaxy examples (MCS)?",
      back: "Mustard, China rose, Sunflower",
      trap: "One leaf per node, alternating sides.",
      hook: "MCS: Mustard, China rose, Sunflower.",
    },
    {
      id: 17,
      cardType: "Leaf",
      title: "Opposite phyllotaxy",
      front: "Opposite phyllotaxy examples (CG)?",
      back: "Calotropis, Guava",
      trap: "Two leaves per node, opposite each other.",
      hook: "CG: Calotropis, Guava.",
    },
    {
      id: 18,
      cardType: "Leaf",
      title: "Whorled phyllotaxy",
      front: "Whorled phyllotaxy example?",
      back: "Alstonia",
      trap: "More than two leaves per node arranged in a whorl.",
      hook: "Alstonia — whorled phyllotaxy.",
    },
    {
      id: 19,
      cardType: "Leaf",
      title: "Phyllode",
      front: "What is a Phyllode? Give an example.",
      back: "A photosynthetic petiole; Australian Acacia",
      trap: "Leaf blade is absent; petiole becomes flat and photosynthetic.",
      hook: "Phyllode = flat photosynthetic petiole in Acacia.",
    },
    {
      id: 20,
      cardType: "Leaf",
      title: "Leaf modifications",
      front: "Leaf modifications in Pea and Cactus?",
      back: "Pea: Tendrils (climbing); Cactus: Spines (defense)",
      trap: "Pea tendrils are modified leaflets; Cactus spines are modified leaves.",
      hook: "Pea climbs; Cactus defends — both use modified leaves.",
    },
    {
      id: 21,
      cardType: "Inflorescence",
      title: "Racemose inflorescence",
      front: "Inflorescence where the main axis continues to grow?",
      back: "Racemose (Acropetal order)",
      trap: "Oldest flowers are at the base; youngest at the top (Acropetal).",
      hook: "Racemose = main axis keeps growing, acropetal.",
    },
    {
      id: 22,
      cardType: "Inflorescence",
      title: "Cymose inflorescence",
      front: "Inflorescence where the main axis ends in a flower?",
      back: "Cymose (Basipetal order)",
      trap: "Oldest flower is at the apex; youngest at the base (Basipetal).",
      hook: "Cymose = main axis ends in flower, basipetal.",
    },
    {
      id: 23,
      cardType: "Flower",
      title: "Perianth",
      front: "What is a Perianth? Give an example.",
      back: "Undifferentiated calyx and corolla; Lily",
      trap: "When tepals are present (calyx and corolla look alike).",
      hook: "Lily has perianth (undifferentiated tepals).",
    },
    {
      id: 24,
      cardType: "Flower",
      title: "Actinomorphic symmetry",
      front: "Actinomorphic (Radial) symmetry examples (MDC)?",
      back: "Mustard, Datura, Chilli",
      trap: "Can be cut into equal halves in multiple planes.",
      hook: "MDC: Mustard, Datura, Chilli — radial symmetry.",
    },
    {
      id: 25,
      cardType: "Flower",
      title: "Zygomorphic symmetry",
      front: "Zygomorphic (Bilateral) symmetry examples (PCGB)?",
      back: "Pea, Cassia, Gulmohar, Bean",
      trap: "Can be cut into equal halves in only ONE plane.",
      hook: "PCGB: Pea, Cassia, Gulmohar, Bean — bilateral.",
    },
    {
      id: 26,
      cardType: "Flower",
      title: "Asymmetric flower",
      front: "Example of an Asymmetric flower?",
      back: "Canna",
      trap: "Cannot be divided into two equal halves in any plane.",
      hook: "Canna — asymmetric, no plane of symmetry.",
    },
    {
      id: 27,
      cardType: "Flower",
      title: "Hypogynous",
      front: "Hypogynous (Superior ovary) examples?",
      back: "Mustard, China rose, Brinjal",
      trap: "Calyx, corolla and stamens are below the ovary.",
      hook: "Hypo = below; ovary is superior (above).",
    },
    {
      id: 28,
      cardType: "Flower",
      title: "Perigynous",
      front: "Perigynous (Half-inferior ovary) examples?",
      back: "Plum, Rose, Peach",
      trap: "Floral parts are at the same level as the ovary.",
      hook: "Peri = around; ovary half-inferior.",
    },
    {
      id: 29,
      cardType: "Flower",
      title: "Epigynous",
      front: "Epigynous (Inferior ovary) examples?",
      back: "Guava, Cucumber, Ray florets of Sunflower",
      trap: "Floral parts arise above the ovary.",
      hook: "Epi = above; ovary is inferior.",
    },
    {
      id: 30,
      cardType: "Flower",
      title: "Valvate aestivation",
      front: "Valvate aestivation example?",
      back: "Calotropis",
      trap: "Petals/sepals touch each other without overlapping.",
      hook: "Calotropis — valvate (touch, no overlap).",
    },
    {
      id: 31,
      cardType: "Flower",
      title: "Twisted aestivation",
      front: "Twisted aestivation examples?",
      back: "China rose, Lady's finger, Cotton",
      trap: "Each petal overlaps the next in one direction.",
      hook: "China rose, Cotton — twisted aestivation.",
    },
    {
      id: 32,
      cardType: "Flower",
      title: "Vexillary aestivation",
      front: "Vexillary (Papilionaceous) aestivation examples?",
      back: "Pea, Bean",
      trap: "Standard aestivation in Fabaceae. Large posterior petal (vexillum) overlaps wings.",
      hook: "Pea, Bean — vexillary/papilionaceous aestivation.",
    },
    {
      id: 33,
      cardType: "Flower",
      title: "Epipetalous vs Epiphyllous",
      front: "Epipetalous vs. Epiphyllous stamens?",
      back: "Epipetalous: Brinjal; Epiphyllous: Lily",
      trap: "Epipetalous = attached to petals; Epiphyllous = attached to perianth.",
      hook: "Brinjal = epipetalous; Lily = epiphyllous.",
    },
    {
      id: 34,
      cardType: "Flower",
      title: "Stamen fusion",
      front: "Monadelphous, Diadelphous, and Polyadelphous examples?",
      back: "Mon: China rose; Di: Pea; Poly: Citrus",
      trap: "Mono = all filaments fused; Di = 2 bundles; Poly = many bundles.",
      hook: "China rose (mono), Pea (di), Citrus (poly).",
    },
    {
      id: 35,
      cardType: "Flower",
      title: "Apocarpous",
      front: "Apocarpous (Free carpels) examples?",
      back: "Lotus, Rose",
      trap: "Apocarpous = free carpels; Syncarpous = fused carpels.",
      hook: "Lotus, Rose — free carpels (apocarpous).",
    },
    {
      id: 36,
      cardType: "Flower",
      title: "Marginal vs Basal placentation",
      front: "Marginal vs. Basal placentation examples?",
      back: "Marginal: Pea; Basal: Sunflower, Marigold",
      trap: "Marginal = ovules on margin of ovary wall; Basal = base of ovary.",
      hook: "Pea = marginal; Sunflower = basal.",
    },
    {
      id: 37,
      cardType: "Flower",
      title: "Axile placentation",
      front: "Axile placentation examples?",
      back: "China rose, Tomato, Lemon",
      trap: "Ovules attached to central axis in multilocular ovary.",
      hook: "China rose, Tomato, Lemon — axile placentation.",
    },
    {
      id: 38,
      cardType: "Flower",
      title: "Parietal placentation",
      front: "Parietal placentation (with Replum) examples?",
      back: "Mustard, Argemone",
      trap: "Ovules on inner wall; false septum (replum) present in Mustard.",
      hook: "Mustard has parietal placentation with replum.",
    },
    {
      id: 39,
      cardType: "Fruit",
      title: "Edible part of Mango",
      front: "The edible part of a Mango is the...?",
      back: "Mesocarp",
      trap: "Drupe = fleshy pericarp with hard endocarp (stone).",
      hook: "Mango mesocarp = the juicy edible part.",
    },
    {
      id: 40,
      cardType: "Seed",
      title: "Scutellum",
      front: "The single cotyledon in Monocots is called...?",
      back: "Scutellum",
      trap: "Present in grass (maize) seeds; absorbs endosperm nutrients.",
      hook: "Scutellum = single monocot cotyledon.",
    },
  ],
};
