/**
 * Built-in deck: Plant Growth & Development (NEET Biology, Chapter 15)
 * 70 high-yield NCERT cards with NEET traps and NCERT hooks.
 */

import type { BuiltinDeck } from "./reproductiveHealth";

export const plantGrowthDeck: BuiltinDeck = {
  id: "builtin-plant-growth",
  name: "Plant Growth & Development",
  description:
    "70 high-yield NCERT cards covering growth phases, PGRs, photoperiodism, and vernalization — with NEET traps and NCERT hooks on every card.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Definition",
      title: "Growth definition",
      front: "Define 'Growth' based on NCERT.",
      back: "An irreversible permanent increase in size of an organ or its parts or even of an individual cell.",
      trap: "Temporary swelling by water is NOT growth.",
      hook: "Involves cell division + elongation.",
    },
    {
      id: 2,
      cardType: "Characteristic",
      title: "Indeterminate growth",
      front: "Why is plant growth 'Indeterminate'?",
      back: "Plants retain the capacity for unlimited growth throughout their life.",
      trap: "Growth is not fixed like in animals.",
      hook: "Due to meristems at specific locations.",
    },
    {
      id: 3,
      cardType: "Anatomy",
      title: "Meristems",
      front: "Identify: Regions of actively dividing cells in plants.",
      back: "Meristems / Meristematic tissue.",
      trap: "These are not permanent tissues.",
      hook: "Growth regions.",
    },
    {
      id: 4,
      cardType: "Meristem",
      title: "Apical meristem",
      front:
        "Which meristem is responsible for the primary growth (length) of root and shoot?",
      back: "Apical Meristem.",
      trap: "Does not contribute to lateral growth.",
      hook: "Root & shoot tips.",
    },
    {
      id: 5,
      cardType: "Meristem",
      title: "Intercalary meristem",
      front:
        "Identify: Meristem responsible for regrowth of grass after herbivory.",
      back: "Intercalary Meristem.",
      trap: "Not present in most dicots; found in internodes/leaf bases.",
      hook: "Regrowth mechanism.",
    },
    {
      id: 6,
      cardType: "Meristem",
      title: "Lateral meristem",
      front:
        "Which meristems are responsible for the increase in girth (secondary growth)?",
      back: "Lateral Meristems (Vascular cambium & cork cambium).",
      trap: "Seen in gymnosperms & dicots, not monocots.",
      hook: "Secondary growth.",
    },
    {
      id: 7,
      cardType: "Phases",
      title: "Three phases of growth",
      front: "Name the three phases of growth in order.",
      back: "1. Meristematic → 2. Elongation → 3. Maturation.",
      trap: "These are sequential zones in a root tip.",
      hook: "Root tip zones.",
    },
    {
      id: 8,
      cardType: "Phase",
      title: "Meristematic phase",
      front:
        "Identify the phase: Cells are rich in protoplasm, thin-walled, and have large nuclei.",
      back: "Meristematic Phase.",
      trap: "No cell enlargement occurs here.",
      hook: "Rapid mitosis.",
    },
    {
      id: 9,
      cardType: "Phase",
      title: "Elongation phase",
      front:
        "Identify the phase: Characterized by vacuole enlargement and cell enlargement.",
      back: "Elongation Phase.",
      trap: "No cell division occurs here.",
      hook: "Not division.",
    },
    {
      id: 10,
      cardType: "Phase",
      title: "Maturation phase",
      front:
        "Identify the phase: Cells attain maximal size and structural modifications.",
      back: "Maturation Phase.",
      trap: "No further growth occurs.",
      hook: "Permanent tissues.",
    },
    {
      id: 11,
      cardType: "Measurement",
      title: "Growth parameters",
      front: "List four parameters for measuring growth.",
      back: "Increase in fresh weight, dry weight, length, area, volume, or cell number.",
      trap: "Fresh weight is variable; Dry weight is more reliable.",
      hook: "Quantitative.",
    },
    {
      id: 12,
      cardType: "Growth type",
      title: "Arithmetic growth",
      front:
        "Identify the growth: Constant growth rate where only one daughter cell continues to divide.",
      back: "Arithmetic Growth.",
      trap: "Rate is constant, not increasing exponentially.",
      hook: "Linear graph.",
    },
    {
      id: 13,
      cardType: "Formula",
      title: "Arithmetic growth formula",
      front: "Formula for Arithmetic Growth?",
      back: "Lt = L0 + rt.",
      trap: "'r' is elongation per unit time (constant).",
      hook: "Straight line graph.",
    },
    {
      id: 14,
      cardType: "Example",
      title: "Arithmetic growth example",
      front: "Give an NCERT example of Arithmetic Growth.",
      back: "Root elongation at constant rate.",
      trap: "Limited by resources eventually.",
      hook: "Single cell division.",
    },
    {
      id: 15,
      cardType: "Growth type",
      title: "Geometric growth",
      front:
        "Identify the growth: Both daughter cells divide; characterized by exponential increase.",
      back: "Geometric Growth.",
      trap: "Not linear; typical of log phase.",
      hook: "Exponential growth.",
    },
    {
      id: 16,
      cardType: "Formula",
      title: "Geometric growth formula",
      front: "Formula for Geometric Growth?",
      back: "Wt = W0 e^rt.",
      trap: "'r' is the relative growth rate.",
      hook: "Sigmoid curve.",
    },
    {
      id: 17,
      cardType: "Graph",
      title: "Sigmoid curve phases",
      front: "Name the phases of a Sigmoid growth curve.",
      back: "Lag phase → Log phase (exponential) → Stationary phase.",
      trap: "It is S-shaped, not J-shaped.",
      hook: "S-shaped curve.",
    },
    {
      id: 18,
      cardType: "Definition",
      title: "Absolute growth rate",
      front: "Define 'Absolute Growth Rate'.",
      back: "Measurement and comparison of total growth per unit time.",
      trap: "Size-dependent; bigger organs grow 'more' in total.",
      hook: "Total growth.",
    },
    {
      id: 19,
      cardType: "Definition",
      title: "Relative growth rate",
      front: "Define 'Relative Growth Rate'.",
      back: "Growth of the system per unit time expressed on a common basis (initial size).",
      trap: "Smaller organs often show faster relative rates.",
      hook: "Initial size basis.",
    },
    {
      id: 20,
      cardType: "NEET Trap",
      title: "RGR vs AGR",
      front:
        "Example: Leaf A (5 to 10 cm²) vs Leaf B (50 to 55 cm²). Which has higher Relative Growth Rate?",
      back: "Leaf A (100% vs 10%).",
      trap: "Both have the same Absolute growth (5 cm²).",
      hook: "Figure-based trap.",
    },
    {
      id: 21,
      cardType: "Definition",
      title: "Development",
      front: "Development = _______ + _______.",
      back: "Growth + Differentiation.",
      trap: "Includes all lifecycle changes.",
      hook: "Morphogenesis.",
    },
    {
      id: 22,
      cardType: "Definition",
      title: "Differentiation",
      front: "Define 'Differentiation'.",
      back: "Process where cells specialize structurally and functionally.",
      trap: "Involves loss of protoplasm in some cases (e.g., tracheids).",
      hook: "Function specific.",
    },
    {
      id: 23,
      cardType: "Definition",
      title: "Dedifferentiation",
      front: "Identify: Differentiated cells regain the capacity to divide.",
      back: "Dedifferentiation.",
      trap: "Rare in plants; essential for healing.",
      hook: "Cork cambium / Interfascicular cambium.",
    },
    {
      id: 24,
      cardType: "Definition",
      title: "Redifferentiation",
      front:
        "Identify: Dedifferentiated cells lose division capacity again to specialize.",
      back: "Redifferentiation.",
      trap: "Not reverse growth to primary state.",
      hook: "Secondary tissues.",
    },
    {
      id: 25,
      cardType: "Definition",
      title: "Morphogenesis",
      front: "Define 'Morphogenesis'.",
      back: "Development of the form/shape of an organism.",
      trap: "Controlled by gene expression.",
      hook: "Shape formation.",
    },
    {
      id: 26,
      cardType: "PGR",
      title: "PGR definition",
      front: "What are Plant Growth Regulators (PGRs)?",
      back: "Small, simple organic molecules that control growth.",
      trap: "They are not nutrients.",
      hook: "Hormonal control.",
    },
    {
      id: 27,
      cardType: "PGR",
      title: "Five PGR classes",
      front: "List the 5 classes of PGRs.",
      back: "Auxins, Gibberellins, Cytokinins, Ethylene, Abscisic acid (ABA).",
      trap: "Vitamins are NOT PGRs.",
      hook: "Five classes.",
    },
    {
      id: 28,
      cardType: "PGR",
      title: "Auxin function",
      front: "Primary function of Auxins?",
      back: "Promotion of cell elongation.",
      trap: "Does not inhibit growth.",
      hook: "Indole compounds.",
    },
    {
      id: 29,
      cardType: "PGR",
      title: "Auxin chemistry",
      front: "Chemical nature of Auxin?",
      back: "Indole compounds (IAA, IBA).",
      trap: "Kinetin is adenine based.",
      hook: "IAA.",
    },
    {
      id: 30,
      cardType: "PGR",
      title: "Auxin synthesis site",
      front: "Primary site of Auxin synthesis?",
      back: "Young leaves and apical buds.",
      trap: "Not found in mature roots.",
      hook: "Polar transport.",
    },
    {
      id: 31,
      cardType: "Mechanism",
      title: "Auxin elongation",
      front: "How does Auxin cause cell elongation?",
      back: "Acid growth hypothesis (acidifying the cell wall to allow expansion).",
      trap: "Not via cell division.",
      hook: "Elongation hormone.",
    },
    {
      id: 32,
      cardType: "Effect",
      title: "Apical dominance",
      front: "Identify: Auxin produced by apical bud inhibits lateral buds.",
      back: "Apical Dominance.",
      trap: "Decapitation promotes bushy growth.",
      hook: "Shoot tip control.",
    },
    {
      id: 33,
      cardType: "Effect",
      title: "Auxin root initiation",
      front: "Effect of Auxin on root initiation?",
      back: "Promotes root initiation in stem cuttings.",
      trap: "High conc inhibits main root.",
      hook: "Propagation use.",
    },
    {
      id: 34,
      cardType: "Mechanism",
      title: "Auxin tropism",
      front: "How does Auxin contribute to Tropism?",
      back: "Unequal distribution (shaded side) causes bending toward light.",
      trap: "Distribution is the key, not creation of more cells.",
      hook: "Darwin experiment.",
    },
    {
      id: 35,
      cardType: "Application",
      title: "2,4-D weedicide",
      front: "Which synthetic auxin is a selective dicot weedicide?",
      back: "2,4-D.",
      trap: "Does not affect monocots.",
      hook: "Selective herbicide.",
    },
    {
      id: 36,
      cardType: "PGR",
      title: "Gibberellin function",
      front: "Primary function of Gibberellins?",
      back: "Promotion of stem/internode elongation.",
      trap: "Not an inhibitor.",
      hook: "GA3.",
    },
    {
      id: 37,
      cardType: "PGR",
      title: "Gibberellin chemistry",
      front: "Chemical nature of Gibberellins?",
      back: "Terpenes (Diterpenes).",
      trap: "More than 100 types exist.",
      hook: "Acidic PGR.",
    },
    {
      id: 38,
      cardType: "Discovery",
      title: "Bakanae disease",
      front: "Disease associated with Gibberellin discovery?",
      back: "Bakanae (Foolish seedling) disease of rice.",
      trap: "Caused by fungus Gibberella fujikuroi.",
      hook: "E. Kurosawa.",
    },
    {
      id: 39,
      cardType: "Effect",
      title: "Bolting",
      front: "What is 'Bolting'?",
      back: "Internode elongation prior to flowering in rosette plants.",
      trap: "Not root elongation.",
      hook: "GA effect.",
    },
    {
      id: 40,
      cardType: "Effect",
      title: "GA vernalization substitute",
      front: "PGR that acts as a substitute for Vernalization?",
      back: "Gibberellins (GA).",
      trap: "Not Auxin.",
      hook: "Long-day replacement.",
    },
    {
      id: 41,
      cardType: "Mechanism",
      title: "GA seed germination",
      front: "How does GA help in seed germination?",
      back: "Stimulates alpha-amylase synthesis to mobilize food.",
      trap: "Not ABA.",
      hook: "Aleurone layer.",
    },
    {
      id: 42,
      cardType: "Application",
      title: "GA brewing",
      front: "Role of GA in brewing industry?",
      back: "Speeds up the malting process in barley.",
      trap: "Increases enzyme activity.",
      hook: "Malting.",
    },
    {
      id: 43,
      cardType: "PGR",
      title: "Cytokinin function",
      front: "Primary function of Cytokinins?",
      back: "Promotion of cell division (cytokinesis).",
      trap: "Not cell elongation.",
      hook: "Zeatin.",
    },
    {
      id: 44,
      cardType: "PGR",
      title: "Cytokinin chemistry",
      front: "Chemical nature of Cytokinins?",
      back: "Adenine derivatives (N6-furfurylamino purine).",
      trap: "First found as Kinetin from DNA.",
      hook: "Kinetin.",
    },
    {
      id: 45,
      cardType: "PGR",
      title: "Cytokinin synthesis site",
      front: "Primary sites of Cytokinin synthesis?",
      back: "Roots, developing seeds, and fruits.",
      trap: "Transported upward in xylem.",
      hook: "Root tips.",
    },
    {
      id: 46,
      cardType: "Mechanism",
      title: "Cytokinin tissue culture",
      front: "Requirement for Cytokinin action in tissue culture?",
      back: "Needs Auxin (Auxin:Cytokinin ratio).",
      trap: "Does not act alone.",
      hook: "Callus formation.",
    },
    {
      id: 47,
      cardType: "Effect",
      title: "Cytokinin senescence",
      front: "How do Cytokinins delay Senescence?",
      back: "By promoting nutrient mobilization (Richmond-Lang effect).",
      trap: "Antagonistic to ABA.",
      hook: "Anti-aging.",
    },
    {
      id: 48,
      cardType: "Effect",
      title: "Cytokinin apical dominance",
      front: "Effect of Cytokinin on Apical Dominance?",
      back: "Promotes lateral bud growth; overcomes apical dominance.",
      trap: "Opposes Auxin.",
      hook: "Bushy growth.",
    },
    {
      id: 49,
      cardType: "PGR",
      title: "Ethylene gaseous",
      front: "Identify: The only gaseous plant growth regulator.",
      back: "Ethylene.",
      trap: "Simple hydrocarbon (C2H4).",
      hook: "Gaseous hormone.",
    },
    {
      id: 50,
      cardType: "Effect",
      title: "Ethylene fruit ripening",
      front: "PGR responsible for 'Climacteric' fruit ripening?",
      back: "Ethylene.",
      trap: "Causes a burst in respiration rate.",
      hook: "Tomato/Banana.",
    },
    {
      id: 51,
      cardType: "Effect",
      title: "Triple response",
      front: "What is the Ethylene 'Triple Response'?",
      back: "Shortening of hypocotyl, horizontal growth, and thickening of axis.",
      trap: "Test for ethylene in seedlings.",
      hook: "Dark grown seedlings.",
    },
    {
      id: 52,
      cardType: "Effect",
      title: "Ethylene senescence",
      front: "How does Ethylene affect Senescence?",
      back: "Promotes senescence and abscission of leaves/flowers.",
      trap: "Opposes cytokinins.",
      hook: "Leaf fall.",
    },
    {
      id: 53,
      cardType: "Application",
      title: "Ethylene pineapple",
      front: "Commercial use of Ethylene in Pineapples?",
      back: "Synchronized flowering and fruit set.",
      trap: "Also used for mango flowering.",
      hook: "Commercial use.",
    },
    {
      id: 54,
      cardType: "PGR",
      title: "ABA stress hormone",
      front: "Identify: The 'Stress Hormone' of plants.",
      back: "Abscisic Acid (ABA).",
      trap: "Primarily a growth inhibitor.",
      hook: "Stress response.",
    },
    {
      id: 55,
      cardType: "Effect",
      title: "ABA dormancy",
      front: "How does ABA affect seed/bud state?",
      back: "Promotes Dormancy.",
      trap: "Antagonist to GA.",
      hook: "Survival strategy.",
    },
    {
      id: 56,
      cardType: "Effect",
      title: "ABA stomata",
      front: "Effect of ABA on stomata during drought?",
      back: "Triggers stomatal closure.",
      trap: "Conserves water.",
      hook: "Guard cells.",
    },
    {
      id: 57,
      cardType: "Effect",
      title: "ABA abscission",
      front: "How does ABA affect abscission?",
      back: "Promotes separation of parts (abscission).",
      trap: "Acts against Auxin.",
      hook: "Abscission.",
    },
    {
      id: 58,
      cardType: "Definition",
      title: "Photoperiodism",
      front: "Define Photoperiodism.",
      back: "Plant response to day/night duration to induce flowering.",
      trap: "Not based on light intensity.",
      hook: "Site of perception is leaves.",
    },
    {
      id: 59,
      cardType: "Classification",
      title: "Plant day-length types",
      front: "Name the three types of plants based on day length.",
      back: "Short Day (SDP), Long Day (LDP), Day Neutral (DNP).",
      trap: "Critical night length is key.",
      hook: "Photoperiodism.",
    },
    {
      id: 60,
      cardType: "Plant type",
      title: "Short day plants",
      front: "Identify: Flower only when light is below critical duration.",
      back: "Short Day Plants (SDP).",
      trap: "Night interruption prevents flowering.",
      hook: "Rice.",
    },
    {
      id: 61,
      cardType: "Plant type",
      title: "Long day plants",
      front: "Identify: Flower only when light exceeds critical duration.",
      back: "Long Day Plants (LDP).",
      trap: "Night break promotes flowering.",
      hook: "Wheat.",
    },
    {
      id: 62,
      cardType: "Plant type",
      title: "Day neutral plants",
      front: "Identify: Flowering independent of day length.",
      back: "Day Neutral Plants (DNP).",
      trap: "Flowering is age-dependent.",
      hook: "Tomato.",
    },
    {
      id: 63,
      cardType: "Definition",
      title: "Vernalization",
      front: "Define Vernalization.",
      back: "Promotion of flowering by low-temperature treatment.",
      trap: "Not photoperiodic.",
      hook: "Cold treatment.",
    },
    {
      id: 64,
      cardType: "Example",
      title: "Vernalization examples",
      front: "NCERT examples of biennial plants needing vernalization?",
      back: "Sugar beet, Cabbage, Carrot.",
      trap: "Flower in second year after cold winter.",
      hook: "Biennials.",
    },
    {
      id: 65,
      cardType: "Definition",
      title: "Senescence",
      front: "Define Senescence.",
      back: "Programmed aging leading to death of parts/organism.",
      trap: "Involves nutrient recycling.",
      hook: "Nutrient recycling.",
    },
    {
      id: 66,
      cardType: "Mechanism",
      title: "Abscission mechanism",
      front: "Mechanism of Abscission?",
      back: "Enzymatic breakdown of cell walls at the separation layer.",
      trap: "Triggered by ethylene/ABA.",
      hook: "Cell wall breakdown.",
    },
    {
      id: 67,
      cardType: "Strategy",
      title: "Dormancy strategy",
      front: "Why is Dormancy an evolutionary strategy?",
      back: "Allows plants to survive unfavorable conditions.",
      trap: "It is metabolic inactivity, not death.",
      hook: "Survival.",
    },
    {
      id: 68,
      cardType: "PGR",
      title: "Seed dormancy PGR",
      front: "PGR that regulates seed dormancy?",
      back: "Abscisic Acid (ABA).",
      trap: "Prevents precocious germination.",
      hook: "Desert plants.",
    },
    {
      id: 69,
      cardType: "Comparison",
      title: "Growth vs Development",
      front: "Differentiate Growth vs Development.",
      back: "Growth: Quantitative (Size). Development: Qualitative (Lifecycle changes).",
      trap: "Development includes growth.",
      hook: "Comparison.",
    },
    {
      id: 70,
      cardType: "NEET Trap",
      title: "PGR concentration",
      front: "True/False: PGRs act in high concentrations.",
      back: "False.",
      trap: "Act in trace amounts; overdose can be toxic.",
      hook: "Concentration balance.",
    },
  ],
};
