/**
 * Built-in deck: Reproductive Health (NEET Biology)
 * 109 high-yield NCERT cards with NEET traps and NCERT hooks.
 */

export interface BuiltinCard {
  id: number;
  cardType: string;
  title: string;
  front: string;
  back: string;
  trap?: string;
  hook?: string;
}

export interface BuiltinDeck {
  id: string;
  name: string;
  description: string;
  isBuiltin: true;
  section: "Biology" | "Physics" | "Chemistry";
  cards: BuiltinCard[];
}

export const reproductiveHealthDeck: BuiltinDeck = {
  id: "builtin-reproductive-health",
  name: "Reproductive Health",
  description:
    "109 high-yield NCERT concepts with NEET traps and hooks — covering contraception, STIs, ARTs, and more.",
  isBuiltin: true,
  section: "Biology",
  cards: [
    {
      id: 1,
      cardType: "Definition",
      title: "Reproductive health (WHO)",
      front: "How does the WHO define reproductive health?",
      back: "Total physical, emotional, behavioural, and social well-being.",
      trap: "It is not merely the absence of disease or infirmity.",
      hook: "A holistic concept of health.",
    },
    {
      id: 2,
      cardType: "General",
      title: "Reproductive health (General)",
      front: "What does reproductive health imply in general terms?",
      back: "Healthy reproductive organs with normal functions.",
      trap: "Includes social aspects, not just biological ones.",
      hook: "Operates at both individual and societal levels.",
    },
    {
      id: 3,
      cardType: "Goal",
      title: "Reproductively healthy society",
      front: "What characterizes a reproductively healthy society?",
      back: "Physically normal organs and normal emotional/behavioural interactions.",
      trap: "Emotional health is often ignored but is strictly included in NCERT.",
      hook: "Primary public health goal.",
    },
    {
      id: 4,
      cardType: "Abbreviation",
      title: "MTP",
      front: "What is MTP?",
      back: "Medical Termination of Pregnancy (Induced Abortion).",
      trap: "It was legalized in India in 1971 with strict conditions.",
      hook: "Voluntary termination before full term.",
    },
    {
      id: 5,
      cardType: "Abbreviation",
      title: "STIs",
      front: "What are STIs?",
      back: "Sexually Transmitted Infections.",
      trap: "Also referred to as VD (Venereal Diseases) or RTI (Reproductive Tract Infections).",
      hook: "Spread primarily via sexual contact.",
    },
    {
      id: 6,
      cardType: "Technology",
      title: "ART",
      front: "What does ART stand for in infertility treatment?",
      back: "Assisted Reproductive Technologies.",
      trap: "Used only when natural conception is not possible.",
      hook: "Advanced laboratory-based methods.",
    },
    {
      id: 7,
      cardType: "Condition",
      title: "Infertility",
      front: "Define medical infertility.",
      back: "Inability to conceive despite 2 years of unprotected coitus.",
      trap: "The problem is often with the male partner, not just the female.",
      hook: "Requires specialized diagnosis.",
    },
    {
      id: 8,
      cardType: "Procedure",
      title: "Amniocentesis",
      front: "What is the primary medical use of Amniocentesis?",
      back: "Analysis of amniotic fluid to detect genetic disorders.",
      trap: "Its use for sex determination is legally banned in India.",
      hook: "Detects chromosomal abnormalities like Down syndrome.",
    },
    {
      id: 9,
      cardType: "Contraception",
      title: "Lactational amenorrhea",
      front: "What is the basis of Lactational amenorrhea?",
      back: "Absence of menstruation during intense lactation.",
      trap: "Effective only up to a maximum of 6 months post-delivery.",
      hook: "A natural method with zero side effects.",
    },
    {
      id: 10,
      cardType: "History",
      title: "Family planning (India)",
      front: "When did India initiate its national family planning program?",
      back: "In the year 1951.",
      trap: "India was among the first countries in the world to do so.",
      hook: "Aimed at population stabilization.",
    },
    {
      id: 11,
      cardType: "Program",
      title: "RCH Programme",
      front: "What is the RCH program?",
      back: "Reproductive and Child Health Care program.",
      trap: "Focuses on both creating awareness and providing medical facilities.",
      hook: "Major evolution of family planning.",
    },
    {
      id: 12,
      cardType: "Contraception",
      title: "Saheli",
      front: "What is unique about the contraceptive pill 'Saheli'?",
      back: "It is a 'once-a-week' non-steroidal oral pill.",
      trap: "Developed by CDRI, Lucknow.",
      hook: "High contraceptive value with very few side effects.",
    },
    {
      id: 13,
      cardType: "Demographics",
      title: "Population explosion cause",
      front: "What is the main driver of the population explosion?",
      back: "Rapid decline in death rate, MMR, and IMR.",
      trap: "Also due to an increase in the number of people in reproductive age.",
      hook: "Improved health facilities led to this.",
    },
    {
      id: 14,
      cardType: "Legal",
      title: "Marriageable age",
      front: "What is the legal marriageable age in India?",
      back: "Female: 18 years; Male: 21 years.",
      trap: "Raising this age is a strategy for population control.",
      hook: "Legislative check on population.",
    },
    {
      id: 15,
      cardType: "Contraception",
      title: "Ideal contraceptive",
      front: "List qualities of an ideal contraceptive.",
      back: "User-friendly, effective, reversible, with no/least side effects.",
      trap: "It should NOT interfere with the sexual drive or desire of the user.",
      hook: "Patient compliance is key.",
    },
    {
      id: 16,
      cardType: "Natural",
      title: "Periodic abstinence",
      front: "Describe the 'fertile window' in periodic abstinence.",
      back: "Days 10 to 17 of the menstrual cycle.",
      trap: "Assumes a regular 28-day cycle; high failure risk if irregular.",
      hook: "Avoiding coitus when ovulation is expected.",
    },
    {
      id: 17,
      cardType: "Natural",
      title: "Withdrawal method",
      front: "What is the withdrawal method (Coitus interruptus)?",
      back: "Withdrawing the penis from the vagina just before ejaculation.",
      trap: "Very high failure rate due to pre-ejaculatory fluid containing sperm.",
      hook: "One of the oldest natural methods.",
    },
    {
      id: 18,
      cardType: "Natural",
      title: "Natural methods",
      front: "What is the common principle of all natural methods?",
      back: "Avoiding the chances of ovum and sperm meeting.",
      trap: "Does not use any devices or chemicals; entirely behavior-dependent.",
      hook: "High failure rate.",
    },
    {
      id: 19,
      cardType: "Barrier",
      title: "Barrier method principle",
      front: "How do barrier methods work?",
      back: "They prevent physical meeting of sperm and ovum.",
      trap: "Provides a physical block; some are disposable, some reusable.",
      hook: "Simple and effective.",
    },
    {
      id: 20,
      cardType: "Barrier",
      title: "Male condom",
      front: "What is a major advantage of using condoms?",
      back: "Protection against STIs and AIDS.",
      trap: "Disposable and self-inserted, providing privacy.",
      hook: "Most popular barrier method.",
    },
    {
      id: 21,
      cardType: "Barrier",
      title: "Female condom",
      front: "What are female condoms called?",
      back: "Femidoms.",
      trap: "They cover the vagina and cervix; self-inserted.",
      hook: "Allows female-controlled STI protection.",
    },
    {
      id: 22,
      cardType: "Brand",
      title: "Nirodh",
      front: "What is Nirodh?",
      back: "A popular brand of condoms for males.",
      trap: "Promoted heavily by the Government of India.",
      hook: "Increased the use of barriers.",
    },
    {
      id: 23,
      cardType: "Barrier",
      title: "Diaphragm",
      front: "How is a diaphragm used?",
      back: "Inserted into the female tract to cover the cervix.",
      trap: "Usually used along with spermicidal creams/jellies.",
      hook: "Reusable barrier.",
    },
    {
      id: 24,
      cardType: "Barrier",
      title: "Cervical cap",
      front: "What is a cervical cap?",
      back: "A small rubber cap that fits over the cervix.",
      trap: "Must be fitted by a professional initially.",
      hook: "Barrier method.",
    },
    {
      id: 25,
      cardType: "Chemical",
      title: "Spermicides",
      front: "How do spermicidal foams/jellies work?",
      back: "They kill sperms chemically.",
      trap: "Rarely used alone; they increase the efficiency of barriers.",
      hook: "Chemical adjunct.",
    },
    {
      id: 26,
      cardType: "IUD",
      title: "IUD",
      front: "Where are IUDs inserted?",
      back: "In the uterus by doctors or expert nurses.",
      trap: "Most widely accepted method of contraception in India.",
      hook: "Intra-Uterine Device.",
    },
    {
      id: 27,
      cardType: "IUD",
      title: "Lippes loop",
      front: "What is Lippes loop?",
      back: "A non-medicated IUD.",
      trap: "Works by increasing phagocytosis of sperm within the uterus.",
      hook: "Plastic/Stainless steel device.",
    },
    {
      id: 28,
      cardType: "IUD",
      title: "Copper-T",
      front: "Main function of Copper-T?",
      back: "Releases Cu ions that suppress sperm motility.",
      trap: "Also reduces the fertilizing capacity of sperms.",
      hook: "Copper-releasing IUD.",
    },
    {
      id: 29,
      cardType: "IUD",
      title: "Multiload 375",
      front: "What type of IUD is Multiload 375?",
      back: "A copper-releasing IUD.",
      trap: "The '375' refers to the surface area of copper wire.",
      hook: "Long-term spacing method.",
    },
    {
      id: 30,
      cardType: "IUD",
      title: "Hormonal IUD",
      front: "Give examples of hormone-releasing IUDs.",
      back: "Progestasert and LNG-20.",
      trap: "They make the uterus unsuitable for implantation.",
      hook: "Progesterone-based.",
    },
    {
      id: 31,
      cardType: "Mechanism",
      title: "IUD mechanism 1",
      front: "How do all IUDs affect sperm in the uterus?",
      back: "Increase phagocytosis of sperms.",
      trap: "This is a local inflammatory response.",
      hook: "Uterine environment change.",
    },
    {
      id: 32,
      cardType: "Mechanism",
      title: "IUD mechanism 2",
      front: "How do Cu ions specifically prevent pregnancy?",
      back: "They are toxic to sperms; they decrease motility.",
      trap: "Prevents sperm from reaching the fallopian tube.",
      hook: "Anti-fertility action.",
    },
    {
      id: 33,
      cardType: "Mechanism",
      title: "Hormonal IUD effect",
      front: "How do hormonal IUDs affect the cervix?",
      back: "They make the cervical mucus thick and hostile to sperm.",
      trap: "Prevents sperm entry into the uterine cavity.",
      hook: "Double barrier effect.",
    },
    {
      id: 34,
      cardType: "Hormonal",
      title: "Oral pills",
      front: "What do oral contraceptive pills contain?",
      back: "Small doses of progestogens or progestogen-estrogen combinations.",
      trap: "Must be taken daily for a period of 21 days.",
      hook: "Inhibits ovulation.",
    },
    {
      id: 35,
      cardType: "Hormonal",
      title: "Pill schedule",
      front: "Describe the typical 28-day pill cycle.",
      back: "21 days of hormones followed by a 7-day gap.",
      trap: "The gap is usually for menstruation (withdrawal bleeding).",
      hook: "Cyclic administration.",
    },
    {
      id: 36,
      cardType: "Mechanism",
      title: "Pill action 1",
      front: "What is the primary mode of action for oral pills?",
      back: "Inhibition of ovulation.",
      trap: "They suppress the FSH and LH surge.",
      hook: "No egg release.",
    },
    {
      id: 37,
      cardType: "Mechanism",
      title: "Pill action 2",
      front: "How do pills affect the endometrium?",
      back: "They alter the quality of the endometrium to prevent implantation.",
      trap: "This is a 'fail-safe' if ovulation occurs.",
      hook: "Implantation block.",
    },
    {
      id: 38,
      cardType: "Mechanism",
      title: "Pill action 3",
      front: "How do pills affect cervical mucus?",
      back: "They increase its thickness/viscosity.",
      trap: "Blocks or retards the entry of sperms.",
      hook: "Sperm barrier.",
    },
    {
      id: 39,
      cardType: "Hormonal",
      title: "Injectables",
      front: "What are injectable contraceptives?",
      back: "Progestogens used as injections under the skin.",
      trap: "Mode of action is similar to pills but duration is longer.",
      hook: "Longer effective period.",
    },
    {
      id: 40,
      cardType: "Hormonal",
      title: "Implants",
      front: "Describe contraceptive implants.",
      back: "Small rods/capsules placed subdermally.",
      trap: "Provide protection for much longer periods (years).",
      hook: "Slow-release hormones.",
    },
    {
      id: 41,
      cardType: "Emergency",
      title: "Emergency contraception",
      front: "When should emergency contraceptives be used?",
      back: "Within 72 hours of unprotected intercourse.",
      trap: "Can be progestogens or IUD insertion.",
      hook: "Post-coital contraception.",
    },
    {
      id: 42,
      cardType: "Emergency",
      title: "Emergency pill limitation",
      front: "Can emergency pills be used as regular contraception?",
      back: "No, they are for emergencies only (rape/casual sex).",
      trap: "High hormone dose; not for routine use.",
      hook: "Prevents unwanted pregnancy.",
    },
    {
      id: 43,
      cardType: "Surgical",
      title: "Sterilisation",
      front: "What is sterilisation?",
      back: "Terminal method to prevent any more pregnancies.",
      trap: "Reversibility is very poor.",
      hook: "Permanent method.",
    },
    {
      id: 44,
      cardType: "Surgical",
      title: "Vasectomy",
      front: "What happens in a vasectomy?",
      back: "Small part of the vas deferens is removed or tied up.",
      trap: "Sperm production continues, but they cannot reach the semen.",
      hook: "Male sterilisation.",
    },
    {
      id: 45,
      cardType: "Surgical",
      title: "Tubectomy",
      front: "What happens in a tubectomy?",
      back: "Small part of the fallopian tube is removed or tied up.",
      trap: "Prevents the ovum from meeting the sperm.",
      hook: "Female sterilisation.",
    },
    {
      id: 46,
      cardType: "Side Effects",
      title: "Contraceptive side effects",
      front: "What are potential side effects of hormonal contraceptives?",
      back: "Nausea, abdominal pain, breakthrough bleeding.",
      trap: "They are not natural states for the body; use under medical advice.",
      hook: "Hormonal interference.",
    },
    {
      id: 47,
      cardType: "Stats",
      title: "MTP statistics",
      front: "How many MTPs are performed annually worldwide?",
      back: "45 to 50 million.",
      trap: "Accounts for nearly 1/5th of total conceived pregnancies.",
      hook: "Significant global impact.",
    },
    {
      id: 48,
      cardType: "Legal",
      title: "MTP safe period",
      front: "When is MTP considered relatively safe?",
      back: "During the first trimester (up to 12 weeks).",
      trap: "NEET Exam favorite: Second trimester abortions are much riskier.",
      hook: "Safe vs Risky window.",
    },
    {
      id: 49,
      cardType: "Risk",
      title: "MTP risky period",
      front: "Why is MTP after 12 weeks dangerous?",
      back: "The fetus becomes intimately associated with maternal tissues.",
      trap: "Risk of maternal hemorrhage and death increases.",
      hook: "Complication risk.",
    },
    {
      id: 50,
      cardType: "Legal",
      title: "MTP 2017 amendment",
      front: "What does the 2017 MTP amendment state?",
      back: "1 doctor for <12 weeks; 2 doctors for 12-24 weeks.",
      trap: "Updated from the original 1971 act.",
      hook: "Legal stringency.",
    },
    {
      id: 51,
      cardType: "Legal",
      title: "MTP ground 1",
      front: "One valid ground for MTP in India?",
      back: "Danger to the life or physical/mental health of the mother.",
      trap: "Requires medical certification.",
      hook: "Health-based legal ground.",
    },
    {
      id: 52,
      cardType: "Legal",
      title: "MTP ground 2",
      front: "Another valid ground for MTP?",
      back: "Substantial risk of serious physical/mental fetal abnormalities.",
      trap: "Allows termination of 'unfit' fetuses legally.",
      hook: "Genetic-based ground.",
    },
    {
      id: 53,
      cardType: "Risk",
      title: "Illegal abortion",
      front: "What is the danger of illegal abortions?",
      back: "Often performed by unqualified quacks; unsafe/fatal.",
      trap: "Major cause of maternal mortality in rural areas.",
      hook: "Public health threat.",
    },
    {
      id: 54,
      cardType: "Social",
      title: "Female foeticide",
      front: "How is amniocentesis misused?",
      back: "For sex-selective abortion of female fetuses.",
      trap: "Illegal and punishable by law.",
      hook: "Severe social imbalance.",
    },
    {
      id: 55,
      cardType: "STI",
      title: "Gonorrhoea",
      front: "What causes Gonorrhoea?",
      back: "Bacterium (Neisseria gonorrhoeae).",
      trap: "It is a curable STI if detected early.",
      hook: "Bacterial infection.",
    },
    {
      id: 56,
      cardType: "STI",
      title: "Syphilis",
      front: "What is the causative agent of Syphilis?",
      back: "Treponema pallidum.",
      trap: "Has primary, secondary, and tertiary stages.",
      hook: "Bacterial STI.",
    },
    {
      id: 57,
      cardType: "STI",
      title: "Genital herpes",
      front: "Is Genital herpes curable?",
      back: "No, it is not completely curable.",
      trap: "Viral infection that can recur.",
      hook: "Lifelong infection.",
    },
    {
      id: 58,
      cardType: "STI",
      title: "Chlamydiasis",
      front: "What is Chlamydiasis?",
      back: "A bacterial STI caused by Chlamydia trachomatis.",
      trap: "Often asymptomatic; leads to silent damage.",
      hook: "Most common bacterial STI.",
    },
    {
      id: 59,
      cardType: "STI",
      title: "Genital warts",
      front: "What causes Genital warts?",
      back: "Human Papilloma Virus (HPV).",
      trap: "Linked to cervical cancer in females.",
      hook: "Viral spread.",
    },
    {
      id: 60,
      cardType: "STI",
      title: "Trichomoniasis",
      front: "What type of infection is Trichomoniasis?",
      back: "Protozoan infection.",
      trap: "Causes foul-smelling vaginal discharge.",
      hook: "Curable STI.",
    },
    {
      id: 61,
      cardType: "STI",
      title: "Hepatitis-B",
      front: "How can Hepatitis-B spread besides sex?",
      back: "Sharing needles, blood transfusion, mother to child.",
      trap: "It is not completely curable once established.",
      hook: "Blood-borne/Sexual.",
    },
    {
      id: 62,
      cardType: "STI",
      title: "HIV",
      front: "What is the most dangerous STI?",
      back: "HIV (Human Immunodeficiency Virus).",
      trap: "Leads to AIDS; currently incurable.",
      hook: "Retroviral attack.",
    },
    {
      id: 63,
      cardType: "STI",
      title: "HIV transmission",
      front: "Main modes of HIV transmission?",
      back: "Sexual contact, infected blood, shared needles.",
      trap: "Cannot spread through casual touch or social contact.",
      hook: "Fluid exchange.",
    },
    {
      id: 64,
      cardType: "STI",
      title: "STI curability rule",
      front: "Which STIs are NOT completely curable?",
      back: "Hepatitis-B, Genital Herpes, and HIV.",
      trap: "All others are curable if detected early and treated.",
      hook: "NCERT Exception list.",
    },
    {
      id: 65,
      cardType: "STI",
      title: "STI high-risk group",
      front: "Which age group is most vulnerable to STIs?",
      back: "15 to 24 years.",
      trap: "This is the 'youth' group that needs maximum awareness.",
      hook: "Demographic risk.",
    },
    {
      id: 66,
      cardType: "STI",
      title: "PID",
      front: "What is a major complication of untreated STIs?",
      back: "Pelvic Inflammatory Diseases (PID).",
      trap: "Can lead to permanent infertility.",
      hook: "Internal scarring.",
    },
    {
      id: 67,
      cardType: "STI",
      title: "STI early symptoms",
      front: "List early symptoms of STIs.",
      back: "Itching, fluid discharge, slight pain, swelling.",
      trap: "Symptoms are often mild and ignored by patients.",
      hook: "Silent onset.",
    },
    {
      id: 68,
      cardType: "STI",
      title: "Female STI issue",
      front: "Why are STIs more dangerous for females?",
      back: "They are often asymptomatic for a long time.",
      trap: "Leads to late detection and complications like ectopic pregnancy.",
      hook: "Silent progression.",
    },
    {
      id: 69,
      cardType: "STI",
      title: "STI prevention",
      front: "What are the three rules of STI prevention?",
      back: "No multiple partners, use condoms, early medical help.",
      trap: "Behavioral change is the best prevention.",
      hook: "Prevention is better than cure.",
    },
    {
      id: 70,
      cardType: "ART",
      title: "IVF",
      front: "What is IVF?",
      back: "In-vitro Fertilisation (fertilisation outside the body).",
      trap: "Conditions must simulate the body (lab mimicry).",
      hook: "Test-tube baby program.",
    },
    {
      id: 71,
      cardType: "ART",
      title: "ZIFT",
      front: "What is ZIFT?",
      back: "Zygote Intra-Fallopian Transfer.",
      trap: "Zygote/embryo with up to 8 blastomeres is transferred.",
      hook: "Early embryo transfer.",
    },
    {
      id: 72,
      cardType: "ART",
      title: "IUT",
      front: "What is IUT?",
      back: "Intra-Uterine Transfer.",
      trap: "Embryos with more than 8 blastomeres are transferred.",
      hook: "Uterine transfer.",
    },
    {
      id: 73,
      cardType: "ART",
      title: "GIFT",
      front: "What is GIFT?",
      back: "Gamete Intra-Fallopian Transfer.",
      trap: "For females who can't produce ovum but can provide environment.",
      hook: "Gamete transfer.",
    },
    {
      id: 74,
      cardType: "ART",
      title: "ICSI",
      front: "What happens in ICSI?",
      back: "Sperm is directly injected into the ovum.",
      trap: "Used for severe male factor infertility.",
      hook: "Intracytoplasmic injection.",
    },
    {
      id: 75,
      cardType: "ART",
      title: "AI",
      front: "What is Artificial Insemination (AI)?",
      back: "Semen collected and introduced into vagina/uterus.",
      trap: "Used when sperm count is low (Oligospermia).",
      hook: "In-vivo fertilisation.",
    },
    {
      id: 76,
      cardType: "ART",
      title: "ART limitation 1",
      front: "Why is ART not available to everyone?",
      back: "Very expensive and limited to few centers.",
      trap: "High cost makes it inaccessible for many.",
      hook: "Economic barrier.",
    },
    {
      id: 77,
      cardType: "ART",
      title: "ART limitation 2",
      front: "What technical expertise is required for ART?",
      back: "Extremely high precision handling and expensive instrumentation.",
      trap: "Requires highly specialized embryologists.",
      hook: "Technical barrier.",
    },
    {
      id: 78,
      cardType: "Social",
      title: "Legal adoption",
      front: "What is a major alternative to ART?",
      back: "Legal adoption of orphans.",
      trap: "India has many parentless children; it is socially/emotionally rewarding.",
      hook: "Social solution.",
    },
    {
      id: 79,
      cardType: "Health",
      title: "MMR",
      front: "What is MMR?",
      back: "Maternal Mortality Rate.",
      trap: "Reduction in MMR is an indicator of improved reproductive health.",
      hook: "Health indicator.",
    },
    {
      id: 80,
      cardType: "Health",
      title: "IMR",
      front: "What is IMR?",
      back: "Infant Mortality Rate.",
      trap: "Death of child before 1 year per 1000 live births.",
      hook: "Development index.",
    },
    {
      id: 81,
      cardType: "Health",
      title: "Child immunisation",
      front: "How does child immunization help reproductive health?",
      back: "It significantly reduces IMR.",
      trap: "A core part of the RCH program.",
      hook: "Survival rate increase.",
    },
    {
      id: 82,
      cardType: "Health",
      title: "Breastfeeding",
      front: "Why is breastfeeding promoted by RCH?",
      back: "Provides natural immunity to the infant.",
      trap: "Exclusive breastfeeding recommended for first 6 months.",
      hook: "Colostrum benefit.",
    },
    {
      id: 83,
      cardType: "Social",
      title: "Sex education",
      front: "Why introduce sex education in schools?",
      back: "To provide right information and dispel myths.",
      trap: "Prevents youth from falling for misinformation.",
      hook: "Awareness strategy.",
    },
    {
      id: 84,
      cardType: "Social",
      title: "Adolescence changes",
      front: "Why is adolescence awareness important?",
      back: "Body undergoes rapid hormonal and emotional changes.",
      trap: "Prevents exploitation and promotes hygiene.",
      hook: "Transition phase.",
    },
    {
      id: 85,
      cardType: "Social",
      title: "Reproductive education",
      front: "What should reproductive education cover?",
      back: "Safe and hygienic sexual practices, STDs, and pregnancy care.",
      trap: "Empowers individuals to make informed choices.",
      hook: "Social responsibility.",
    },
    {
      id: 86,
      cardType: "Program",
      title: "Population slogan",
      front: "What was the popular population control slogan?",
      back: "Hum Do Hamare Do (We two, our two).",
      trap: "Aimed at popularizing the two-child norm.",
      hook: "Govt communication.",
    },
    {
      id: 87,
      cardType: "Policy",
      title: "Incentives",
      front: "What are incentives in family planning?",
      back: "Rewards/support given to couples with small families.",
      trap: "Includes tax benefits or prioritize services.",
      hook: "Stabilization strategy.",
    },
    {
      id: 88,
      cardType: "Trend",
      title: "Urban trend",
      front: "What is the 'one-child norm'?",
      back: "Urban couples voluntarily having only one child.",
      trap: "A result of economic pressure and awareness.",
      hook: "Demographic shift.",
    },
    {
      id: 89,
      cardType: "IUD",
      title: "IUD advantage",
      front: "Why are IUDs considered reliable?",
      back: "Long-term (3-10 years) and highly reversible.",
      trap: "Does not require daily user compliance like pills.",
      hook: "Set and forget method.",
    },
    {
      id: 90,
      cardType: "IUD",
      title: "Copper IUD effect",
      front: "How do Cu ions specifically affect sperm?",
      back: "They reduce motility and fertilizing capacity.",
      trap: "Toxic effect on sperm physiology.",
      hook: "Anti-motility.",
    },
    {
      id: 91,
      cardType: "IUD",
      title: "Hormonal IUD effect",
      front: "How do hormonal IUDs prevent implantation?",
      back: "By making the endometrium hostile (thinning it).",
      trap: "Prevents the blastocyst from attaching.",
      hook: "Anti-implantation.",
    },
    {
      id: 92,
      cardType: "Surgical",
      title: "Sterilisation advantage",
      front: "Why is sterilization effective?",
      back: "Failure rate is almost zero.",
      trap: "No daily or monthly effort required by user.",
      hook: "Highest efficacy.",
    },
    {
      id: 93,
      cardType: "Surgical",
      title: "Sterilisation drawback",
      front: "What is the main drawback of sterilization?",
      back: "Poor reversibility.",
      trap: "Cannot be easily undone if the couple changes their mind.",
      hook: "Terminal decision.",
    },
    {
      id: 94,
      cardType: "Natural",
      title: "Lactational method condition",
      front: "What is required for the lactational method to work?",
      back: "Intense, exclusive breastfeeding.",
      trap: "Fails once supplemental feeding begins.",
      hook: "Natural spacing.",
    },
    {
      id: 95,
      cardType: "Barrier",
      title: "Condom advantage",
      front: "What makes condoms unique among contraceptives?",
      back: "They provide dual protection: pregnancy + STIs.",
      trap: "The only method that effectively prevents HIV.",
      hook: "Safety first.",
    },
    {
      id: 96,
      cardType: "Hormonal",
      title: "Pill disadvantage",
      front: "Common hormonal pill side effect?",
      back: "Irregular menstrual bleeding or nausea.",
      trap: "Should be avoided by smokers or those with clotting risks.",
      hook: "Hormonal side effect.",
    },
    {
      id: 97,
      cardType: "Emergency",
      title: "Emergency IUD",
      front: "Can an IUD be an emergency contraceptive?",
      back: "Yes, if inserted within 72 hours.",
      trap: "Highly effective at preventing implantation post-intercourse.",
      hook: "Emergency use.",
    },
    {
      id: 98,
      cardType: "Risk",
      title: "Unsafe abortion risk",
      front: "Major health risk of unsafe abortion?",
      back: "Septicemia or Hemorrhage.",
      trap: "Can lead to permanent loss of fertility or death.",
      hook: "Maternal mortality.",
    },
    {
      id: 99,
      cardType: "Procedure",
      title: "Amniocentesis use",
      front: "What is a legitimate use of amniocentesis?",
      back: "Detecting Down syndrome or metabolic disorders.",
      trap: "Measures biochemical and chromosomal status of fetus.",
      hook: "Prenatal diagnosis.",
    },
    {
      id: 100,
      cardType: "Condition",
      title: "Down syndrome",
      front: "What causes Down syndrome?",
      back: "Trisomy of chromosome 21.",
      trap: "Can be detected prenatally via amniotic fluid cells.",
      hook: "Chromosomal disorder.",
    },
    {
      id: 101,
      cardType: "Condition",
      title: "Hemophilia",
      front: "What is Hemophilia?",
      back: "A genetic blood clotting disorder.",
      trap: "X-linked recessive; detected via genetic screening.",
      hook: "Inherited disease.",
    },
    {
      id: 102,
      cardType: "Condition",
      title: "Sickle-cell anemia",
      front: "What is Sickle-cell anemia?",
      back: "Autosomal recessive blood disorder.",
      trap: "Causes RBCs to become sickle-shaped under low oxygen.",
      hook: "Genetic mutation.",
    },
    {
      id: 103,
      cardType: "Health",
      title: "Improved RH indicator",
      front: "List an indicator of improved reproductive health.",
      back: "Increased number of assisted deliveries.",
      trap: "Shows better access to medical facilities.",
      hook: "Health progress.",
    },
    {
      id: 104,
      cardType: "Health",
      title: "Improved RH indicator 2",
      front: "Another indicator of RH progress?",
      back: "Decrease in the total fertility rate and better awareness.",
      trap: "Couples choosing smaller families.",
      hook: "Stabilization indicator.",
    },
    {
      id: 105,
      cardType: "STI",
      title: "STI complication",
      front: "How can STIs cause ectopic pregnancy?",
      back: "By causing scarring and blockages in the fallopian tubes.",
      trap: "Fertilised egg gets stuck in the tube.",
      hook: "Tube damage.",
    },
    {
      id: 106,
      cardType: "STI",
      title: "STI complication",
      front: "What is a 'stillbirth' in relation to STIs?",
      back: "Death of a fetus after 20 weeks of pregnancy.",
      trap: "Untreated syphilis is a major cause.",
      hook: "Pregnancy loss.",
    },
    {
      id: 107,
      cardType: "STI",
      title: "STI complication",
      front: "Which STI is linked to reproductive tract cancer?",
      back: "Human Papilloma Virus (HPV).",
      trap: "Primary cause of cervical cancer.",
      hook: "Malignancy risk.",
    },
    {
      id: 108,
      cardType: "ART",
      title: "ART embryo stage rule",
      front: "What is the '8-cell' rule for ART transfer?",
      back: "≤8 cells go to the tube (ZIFT); >8 cells go to the uterus (IUT).",
      trap: "Exam favorite: They often swap these two in options.",
      hook: "Stage-specific transfer.",
    },
    {
      id: 109,
      cardType: "Goal",
      title: "Contraception goal",
      front: "What is the fundamental goal of contraception?",
      back: "To prevent, delay, or space pregnancies.",
      trap: "It is not a cure for any reproductive disease.",
      hook: "Family planning basis.",
    },
  ],
};

import { animalKingdomDeck } from "./animalKingdom";
import { biomoleculesDeck } from "./biomolecules";
import { electrostaticsDeck } from "./electrostatics";
import { endocrineDeck } from "./endocrine";
import { gravitationDeck } from "./gravitation";
import { lawsOfMotionDeck } from "./lawsOfMotion";
import { microbesHumanWelfareDeck } from "./microbesHumanWelfare";
import { shmDeck } from "./shm";

/** All built-in decks — extend this array to add more */
export const BUILTIN_DECKS: BuiltinDeck[] = [
  reproductiveHealthDeck,
  microbesHumanWelfareDeck,
  biomoleculesDeck,
  animalKingdomDeck,
  endocrineDeck,
  lawsOfMotionDeck,
  gravitationDeck,
  shmDeck,
  electrostaticsDeck,
];
