/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Card = IDL.Record({
  'id' : IDL.Nat,
  'front' : IDL.Text,
  'title' : IDL.Text,
  'cardType' : IDL.Text,
  'back' : IDL.Text,
  'hook' : IDL.Opt(IDL.Text),
  'trap' : IDL.Opt(IDL.Text),
});
export const Deck = IDL.Record({
  'id' : IDL.Text,
  'cards' : IDL.Vec(Card),
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'appendCards' : IDL.Func([IDL.Text, IDL.Vec(Card)], [], []),
  'deleteDeck' : IDL.Func([IDL.Text], [], []),
  'initDeck' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'listDecks' : IDL.Func([], [IDL.Vec(Deck)], ['query']),
  'renameDeck' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveDeck' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Card)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Card = IDL.Record({
    'id' : IDL.Nat,
    'front' : IDL.Text,
    'title' : IDL.Text,
    'cardType' : IDL.Text,
    'back' : IDL.Text,
    'hook' : IDL.Opt(IDL.Text),
    'trap' : IDL.Opt(IDL.Text),
  });
  const Deck = IDL.Record({
    'id' : IDL.Text,
    'cards' : IDL.Vec(Card),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'appendCards' : IDL.Func([IDL.Text, IDL.Vec(Card)], [], []),
    'deleteDeck' : IDL.Func([IDL.Text], [], []),
    'initDeck' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'listDecks' : IDL.Func([], [IDL.Vec(Deck)], ['query']),
    'renameDeck' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveDeck' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Card)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };