/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Card {
    id: bigint;
    front: string;
    title: string;
    cardType: string;
    back: string;
    hook?: string;
    trap?: string;
}
export interface Deck {
    id: string;
    cards: Array<Card>;
    name: string;
    description: string;
}
export interface backendInterface {
    appendCards(id: string, newCards: Array<Card>): Promise<void>;
    deleteDeck(id: string): Promise<void>;
    initDeck(id: string, name: string, description: string): Promise<void>;
    listDecks(): Promise<Array<Deck>>;
    renameDeck(id: string, newName: string): Promise<void>;
    saveDeck(id: string, name: string, description: string, cards: Array<Card>): Promise<void>;
}
import type { Card as _Card, Deck as _Deck } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async appendCards(arg0: string, arg1: Array<Card>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.appendCards(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appendCards(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDeck(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeck(arg0);
            return result;
        }
    }
    async initDeck(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initDeck(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDeck(arg0, arg1, arg2);
            return result;
        }
    }
    async listDecks(): Promise<Array<Deck>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDecks();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDecks();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameDeck(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameDeck(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameDeck(arg0, arg1);
            return result;
        }
    }
    async saveDeck(arg0: string, arg1: string, arg2: string, arg3: Array<Card>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDeck(arg0, arg1, arg2, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDeck(arg0, arg1, arg2, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_Card_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Deck_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deck): Deck {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    cards: Array<_Card>;
    name: string;
    description: string;
}): {
    id: string;
    cards: Array<Card>;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        cards: from_candid_vec_n7(_uploadFile, _downloadFile, value.cards),
        name: value.name,
        description: value.description
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    front: string;
    title: string;
    cardType: string;
    back: string;
    hook: [] | [string];
    trap: [] | [string];
}): {
    id: bigint;
    front: string;
    title: string;
    cardType: string;
    back: string;
    hook?: string;
    trap?: string;
} {
    return {
        id: value.id,
        front: value.front,
        title: value.title,
        cardType: value.cardType,
        back: value.back,
        hook: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.hook)),
        trap: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.trap))
    };
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deck>): Array<Deck> {
    return value.map((x)=>from_candid_Deck_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Card_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Card): _Card {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    front: string;
    title: string;
    cardType: string;
    back: string;
    hook?: string;
    trap?: string;
}): {
    id: bigint;
    front: string;
    title: string;
    cardType: string;
    back: string;
    hook: [] | [string];
    trap: [] | [string];
} {
    return {
        id: value.id,
        front: value.front,
        title: value.title,
        cardType: value.cardType,
        back: value.back,
        hook: value.hook ? candid_some(value.hook) : candid_none(),
        trap: value.trap ? candid_some(value.trap) : candid_none()
    };
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Card>): Array<_Card> {
    return value.map((x)=>to_candid_Card_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
